# Optional overrides. Leave commented to auto-detect from %KVEM_HOME%.
#kvem.home=C:/Java_ME_platform_SDK_3.0
#cldc.jar=C:/Java_ME_platform_SDK_3.0/lib/cldcapi11.jar
#midp.jar=C:/Java_ME_platform_SDK_3.0/lib/midpapi21.jar
#preverify.exe=C:/Java_ME_platform_SDK_3.0/bin/preverify.exe
#app.name=PokeAutoChess
