package pac;
import javax.microedition.lcdui.Graphics;

/** Small real-time 1v1 encounter with HP-dependent capture odds. */
public final class ExploreCatchBattleScreen extends Screen{
 private static final int FIGHT=0,THROW=1,RESULT=2,OPPORTUNITY=3;
 private final WorldScreen world;private final int enemy,wx,wy,hero;private final Rng rng;
 private int hp,ehp,maxHp,maxEhp,attackT,enemyT,time,throwCount,state,resultT,fxT,fxSp,throwT,heroHits,enemyHits,opportunityChoice;private int hc=1,hr=4,ec=4,er=1,hvx=hc*256,hvy=hr*256,evx=ec*256,evy=er*256,moveT,heroDmg,enemyDmg,heroDmgT,enemyDmgT,heroTotal,enemyTotal;private String msg="";private boolean remove,retry,caughtVisual,opportunityShown;
 public ExploreCatchBattleScreen(Game g,WorldScreen w,int sp,int x,int y){super(g);world=w;enemy=sp;wx=x;wy=y;rng=new Rng((int)System.currentTimeMillis()^sp*7919);hero=pickHero();maxHp=hp=Data.hp[hero];maxEhp=ehp=Data.hp[enemy];attackT=450;enemyT=720;}
 private int pickHero(){int d=Data.speciesForDex(Save.profileAvatarDex);if(d>=0&&Save.usable(d))return d;if(Save.hero>=0&&Save.usable(Save.hero))return Save.hero;for(int i=0;i<Data.N;i++)if(Save.usable(i))return i;return 0;}
 private int damage(int a,int d,boolean skill){return ExploreBattleRules.damage(a,d,skill);}
 private int interval(int sp){return Math.max(480,980-Data.speed[sp]*5);}
 public void update(int dt){time+=dt;smooth(dt);if(fxT>0)fxT-=dt;if(heroDmgT>0)heroDmgT-=dt;if(enemyDmgT>0)enemyDmgT-=dt;if(state==OPPORTUNITY||state==RESULT)return;if(state==THROW){throwT-=dt;if(throwT<=0)resolveThrow();return;}attackT-=dt;enemyT-=dt;if(!adjacent()){moveT-=dt;if(moveT<=0){moveT+=170;step(true);if(!adjacent())step(false);}return;}if(attackT<=0){attackT+=interval(hero);heroHits++;boolean skill=heroHits%4==0;int d=damage(hero,enemy,skill);ehp-=d;heroTotal+=d;enemyDmg=d;enemyDmgT=650;fxT=skill?520:300;fxSp=hero;if(ehp<=0){ehp=0;world.recordDefeat(enemy);if(Data.category[enemy]!=6){long before=Save.exploreLegendUntil;ExploreRules.recordDefeat(enemy,System.currentTimeMillis()/1000L);if(Save.exploreLegendUntil!=before)world.legendaryUnlocked();Save.save();finish(Lang.t(Data.name[enemy]+" đã hẹo! Tiến trình nhiệm vụ +1.",Data.name[enemy]+" fainted! Quest progress +1."),true,1300);}else{Save.save();finish(Lang.t(Data.name[enemy]+" đã hẹo! Thần thú biến mất.",Data.name[enemy]+" fainted! The Legendary vanished."),true,1300);}return;}if(!opportunityShown&&ehp*100<=maxEhp*20){opportunityShown=true;opportunityChoice=0;resetTouchChoice();state=OPPORTUNITY;return;}}if(enemyT<=0){enemyT+=interval(enemy);enemyHits++;boolean skill=enemyHits%4==0;int d=damage(enemy,hero,skill);hp-=d;enemyTotal+=d;heroDmg=d;heroDmgT=650;fxT=skill?520:300;fxSp=enemy;if(hp<=0){hp=0;finish(Lang.t(Data.name[hero]+" đã hẹo. Bạn rút lui!",Data.name[hero]+" fainted. You retreated!"),false,1400);}}}
 private void smooth(int dt){int s=Math.max(1,dt*256/170);hvx=toward(hvx,hc*256,s);hvy=toward(hvy,hr*256,s);evx=toward(evx,ec*256,s);evy=toward(evy,er*256,s);}
 private int toward(int v,int t,int s){return v<t?Math.min(t,v+s):(v>t?Math.max(t,v-s):v);}
 private boolean adjacent(){return Math.abs(hc-ec)<=1&&Math.abs(hr-er)<=1;}
 private void step(boolean h){int x=h?hc:ec,y=h?hr:er,tx=h?ec:hc,ty=h?er:hr,dx=tx>x?1:(tx<x?-1:0),dy=ty>y?1:(ty<y?-1:0);int nx=x+dx,ny=y+dy;if(h){if(nx!=ec||ny!=er){hc=nx;hr=ny;}}else if(nx!=hc||ny!=hr){ec=nx;er=ny;}}
 private void finish(String s,boolean rm,int delay){state=RESULT;msg=s;remove=rm;retry=false;resultT=delay;}
 private int chance(){return ExploreBattleRules.catchChance(enemy,ehp,maxEhp);}
 public boolean pointer(int x,int y){if(state==RESULT){key(Game.K_FIRE);return true;}if(state==OPPORTUNITY){int fh=Art.fh,w=Math.min(game.W-18,210),h=fh*7+14,left=(game.W-w)/2,top=(game.H-h)/2,bw=(w-18)/2,by=top+h-fh*2-8;for(int i=0;i<2;i++){int bx=left+6+i*(bw+6);if(x>=bx&&x<bx+bw&&y>=by&&y<by+fh+6){opportunityChoice=i;if(confirmTouch(900+i))key(Game.K_FIRE);}}return true;}if(y>=game.H-Art.fh-5){key(x<game.W*2/3?Game.K_FIRE:Game.K_0);return true;}return true;}
 public void key(int k){if(k!=Game.K_FIRE&&k!=Game.K_SOFT1)resetTouchChoice();if(state==RESULT){if(k==Game.K_FIRE||k==Game.K_SOFT1)continueResult();return;}if(state==OPPORTUNITY){if(k==Game.K_LEFT||k==Game.K_UP)opportunityChoice=0;else if(k==Game.K_RIGHT||k==Game.K_DOWN)opportunityChoice=1;else if(k==Game.K_0||k==Game.K_SOFT2){opportunityChoice=1;state=FIGHT;}else if(k==Game.K_FIRE||k==Game.K_SOFT1){if(opportunityChoice==0)startThrow();else state=FIGHT;}return;}if(state!=FIGHT)return;if(k==Game.K_0||k==Game.K_SOFT2){finish(Lang.t("Đã rút lui an toàn.","You retreated safely."),false,450);return;}if(k==Game.K_FIRE||k==Game.K_SOFT1)startThrow();}
 private void continueResult(){if(retry){retry=false;state=FIGHT;msg="";}else{world.encounterDone(wx,wy,remove,msg);game.setScreen(world);}}
 private void startThrow(){if(Save.balls<=0){finish(Lang.t("Đã hết \uE000!","Out of \uE000!"),false,900);return;}Save.balls--;Save.save();throwCount++;resetTouchChoice();throwT=760;state=THROW;msg="";}
 private void resolveThrow(){boolean legend=Data.category[enemy]==6;if(rng.pct(chance())){boolean fresh=Save.unlockFamily(enemy);Save.caught++;world.recordCatch(enemy);if(!legend){long before=Save.exploreLegendUntil;ExploreRules.recordCatch(enemy,System.currentTimeMillis()/1000L);if(Save.exploreLegendUntil!=before)world.legendaryUnlocked();}Save.save();caughtVisual=true;msg=Lang.t("Đã bắt ","Caught ")+Data.name[enemy]+(fresh?Lang.t("! MỚI!","! NEW!"):"!");finish(msg,true,1700);}else{world.recordMiss();if(legend){Save.save();finish(Lang.t("Bắt hụt! Thần thú đã biến mất.","Capture failed! The Legendary vanished."),true,1400);}else if(throwCount>=3){Save.save();finish(Data.name[enemy]+Lang.t(" đã chạy mất sau 3 lần!"," fled after 3 throws!"),true,1400);}else{msg=Lang.t("Không bắt được! Tiếp tục chiến đấu.","Broke free! Battle continues.");resultT=700;state=RESULT;remove=false;retry=true;}}}
 public void paint(Graphics g){int W=game.W,H=game.H,fh=Art.fh,header=fh+6,msgH=fh*2+8,infoH=fh*5+18;boolean wide=UiLayout.landscape(W,H);int arenaW=wide?W*3/5:W,arenaH=wide?H-header:H-header-msgH-infoH;if(arenaH<72)arenaH=72;g.setColor(0x090D14);g.fillRect(0,0,W,H);int cols=6,rows=6,cw=(arenaW+cols-1)/cols,ch=(arenaH+rows-1)/rows;for(int r=0;r<rows;r++)for(int c0=0;c0<cols;c0++){boolean foe=r<3;int a=foe?0x573536:0x304667,b=foe?0x4B2E31:0x293D5B;g.setColor(((r+c0)&1)==0?a:b);g.fillRect(c0*cw,header+r*ch,cw+1,ch+1);}g.setColor(0x6D7D92);g.drawRect(0,header,arenaW-1,arenaH-1);g.drawLine(0,header+3*ch,arenaW,header+3*ch);String title="VS "+Data.name[enemy];Art.textR(g,title,W-3,2,0xFFFFFF);int c=chance(),box=35,bx=3;g.setColor(c>=60?0x205B35:(c>=30?0x594915:0x572020));g.fillRect(bx,1,box,header-3);g.setColor(c>=60?0x60F080:(c>=30?0xFFE060:0xFF7060));g.drawRect(bx,1,box-1,header-4);Art.textSmallC(g,c+"%",bx+box/2,4,0xFFFFFF);
 int size=Math.min(52,Math.min(cw*2,ch*2+8)),hx=hvx*cw/256+cw/2-size/2,hy=header+hvy*ch/256+ch-size,ex=evx*cw/256+cw/2-size/2,ey=header+evy*ch/256+ch-size;if(fxT>0&&fxSp==hero){hx+=(ec-hc)*cw*fxT/900;hy+=(er-hr)*ch*fxT/900;}if(fxT>0&&fxSp==enemy){ex+=(hc-ec)*cw*fxT/900;ey+=(hr-er)*ch*fxT/900;}if(!caughtVisual)drawFacing(g,enemy,ex,ey,size,hc-ec,hr-er,time/90+3);drawFacing(g,hero,hx,hy,size,ec-hc,er-hr,time/90);Art.battleBar(g,hx+size/2,hy+size-1,hp,maxHp,0,(heroHits%4)*25,100,true);if(!caughtVisual)Art.battleBar(g,ex+size/2,ey+size-1,ehp,maxEhp,0,(enemyHits%4)*25,100,false);if(fxT>300){int tx=fxSp==hero?ex:hx,ty=fxSp==hero?ey:hy;Art.speciesSkillSprite(g,fxSp,tx+size/2-16,ty+size/2-16,(520-fxT)/55);}if(enemyDmgT>0)paintDamage(g,enemyDmg,ex+size/2,ey-4,enemyDmgT);if(heroDmgT>0)paintDamage(g,heroDmg,hx+size/2,hy-4,heroDmgT);if(state==THROW)paintCatchWave(g,ex+size/2,ey+size/2,760-throwT,false);if(caughtVisual)paintCatchWave(g,ex+size/2,ey+size/2,760,true);
 if(wide){paintLandscapeInfo(g,arenaW+1,header,W-arenaW-1,H-header);if(state==OPPORTUNITY)paintOpportunity(g);else if(state==RESULT&&(caughtVisual||retry||hp<=0||ehp<=0||throwCount>=3||Data.category[enemy]==6))paintOutcomePopup(g);return;}
 int my=header+arenaH;g.setColor(0x0B1220);g.fillRect(0,my,W,msgH);g.setColor(0x52637A);g.drawRect(2,my+2,W-5,msgH-5);String notice=Lang.t("Hai Pokémon đang giao chiến...","The Pokémon are battling...");int noticeCol=0xB8C8D8;if(state==THROW){notice=Lang.t("Sóng bắt đang lan tỏa...","Capture wave expanding...");noticeCol=0x80D8FF;}else if(state==RESULT){notice=msg;noticeCol=caughtVisual?0xFFF080:(retry?0xFF9090:0xFFFFFF);}Art.textSmallC(g,notice,W/2,my+5,noticeCol);if(state==RESULT&&retry)Art.textSmallC(g,Lang.t("Trận đấu sẽ tiếp tục","The battle will continue"),W/2,my+fh+4,0xA8B8D0);else Art.textSmallC(g,chance()+"%  •  "+throwCount+"/3",W/2,my+fh+4,0x90E8A0);
 int iy=my+msgH;paintAutoChessStats(g,iy,H-iy);if(state==OPPORTUNITY)paintOpportunity(g);else if(state==RESULT&&(caughtVisual||retry||hp<=0||ehp<=0||throwCount>=3||Data.category[enemy]==6))paintOutcomePopup(g);}
 private void drawFacing(Graphics g,int sp,int x,int y,int size,int dx,int dy,int clock){int dir=direction(dx,dy);if(!RawAtlas.drawFormation(g,sp,x,y,size,size,game.W,dir,clock))Art.battleSprite(g,sp,x,y,clock,RawAtlas.IDLE,dir);}
 private void paintLandscapeInfo(Graphics g,int x,int y,int w,int h){int fh=Art.fh,msgH=fh*3+10,footer=fh+5,cardH=Math.max(48,(h-msgH-footer)/2);g.setColor(0x111A29);g.fillRect(x,y,w,h);g.setColor(0x40506A);g.drawRect(x,y,w-1,h-1);String notice=Lang.t("Hai Pokémon đang giao chiến...","The Pokémon are battling...");int col=0xB8C8D8;if(state==THROW){notice=Lang.t("Sóng bắt đang lan tỏa...","Capture wave expanding...");col=0x80D8FF;}else if(state==RESULT){notice=msg;col=caughtVisual?0xFFF080:(retry?0xFF9090:0xFFFFFF);}String[] lines=Art.wrap(notice,w-12,2);for(int i=0;i<lines.length;i++)Art.textSmallC(g,lines[i],x+w/2,y+5+i*fh,col);Art.textSmallC(g,chance()+"%  •  "+throwCount+"/3",x+w/2,y+fh*2+4,0x90E8A0);int cy=y+msgH;paintPetCard(g,hero,hp,maxHp,(heroHits%4)*25,heroTotal,x+1,cy,w-2,cardH,false);paintPetCard(g,enemy,ehp,maxEhp,(enemyHits%4)*25,enemyTotal,x+1,cy+cardH,w-2,cardH,true);Art.textSmallC(g,"5: "+Lang.t("bắt","catch")+"   0: "+Lang.t("rút","leave"),x+w/2,y+h-fh-2,0xA8B5C8);}
 private int direction(int dx,int dy){if(dy>0){if(dx>0)return 1;if(dx<0)return 7;return 0;}if(dy<0){if(dx>0)return 3;if(dx<0)return 5;return 4;}return dx>0?2:6;}
 private void paintAutoChessStats(Graphics g,int y,int h){int W=game.W,fh=Art.fh,half=W/2;g.setColor(0x111A29);g.fillRect(0,y,W,h);g.setColor(0x40506A);g.drawLine(0,y,W,y);int gh=Math.max(42,h-fh-2);paintPetCard(g,hero,hp,maxHp,(heroHits%4)*25,heroTotal,0,y+1,half-1,gh,false);paintPetCard(g,enemy,ehp,maxEhp,(enemyHits%4)*25,enemyTotal,half,y+1,W-half,gh,true);Art.textSmall(g,Lang.t("Tổng: ","Total: ")+(heroTotal+enemyTotal),3,y+h-fh,0xFF8060);Art.textSmallR(g,"5: "+Lang.t("bắt","catch")+"  0: "+Lang.t("rút","leave"),W-3,y+h-fh,0xA8B5C8);}
 private void paintPetCard(Graphics g,int sp,int value,int max,int mana,int dealt,int x,int y,int w,int h,boolean foe){g.setColor(foe?0x1B2638:0x202C3F);g.fillRect(x,y,w-1,h);int av=20,ax=foe?x+w-av-3:x+3,tx=foe?x+3:x+av+7,tw=w-av-11;Art.avatarMini(g,sp,ax,y+3);String name=Data.name[sp],nums=value+"/"+max;if(foe){Art.textSmallR(g,name,x+w-av-7,y+1,0xFFFFFF);Art.textSmall(g,nums,tx,y+1,0xD8E8F0);}else{Art.textSmall(g,name,tx,y+1,0xFFFFFF);Art.textSmallR(g,nums,x+w-4,y+1,0xD8E8F0);}int by=y+13;g.setColor(0x171B24);g.fillRect(tx,by,tw,7);int fill=Math.max(0,value)*tw/Math.max(1,max);g.setColor(foe?0xE76E55:0x76C442);g.fillRect(tx,by,fill,7);if(foe){int mark=tx+tw/5;g.setColor(0xFFD030);g.fillRect(mark,by-2,2,11);}g.setColor(0x0D1624);g.fillRect(tx,by+9,tw,3);g.setColor(0x209CEE);g.fillRect(tx,by+9,tw*mana/100,3);int sy=y+25;String a=Lang.t("Công ","ATK ")+Data.atk[sp]+Lang.t(" Thủ "," DEF ")+Data.def[sp];String b=Lang.t("Kháng ","SDEF ")+Data.speDef[sp]+Lang.t(" Tốc "," SPD ")+Data.speed[sp];if(foe){Art.textSmallR(g,a,x+w-3,sy,0xC8D3E3);Art.textSmallR(g,b,x+w-3,sy+10,0x9EADC2);}else{Art.textSmall(g,a,x+3,sy,0xC8D3E3);Art.textSmall(g,b,x+3,sy+10,0x9EADC2);}Art.textSmall(g,Lang.t("DMG ","DMG ")+dealt,foe?x+w-38:x+3,y+h-11,foe?0xFF9078:0x90E880);}
 private void paintDamage(Graphics g,int d,int x,int y,int life){int lift=(650-life)/35;Art.textSmallC(g,"-"+d,x,y-lift,0xFFF060);}
 private void paintCatchWave(Graphics g,int x,int y,int age,boolean sparkle){int p=Math.min(256,age*256/760);for(int i=0;i<3;i++){int q=p-i*55;if(q<0)continue;int r=5+q/3;g.setColor(i==0?0xFFFFFF:(i==1?0x70D8FF:0xA060FF));g.drawArc(x-r,y-r/2,r*2,r,0,360);}if(sparkle)for(int i=0;i<10;i++){int dx=((i*13+time/55)%35)-17,dy=((i*19+time/45)%31)-15;g.setColor((i&1)==0?0xFFF080:0xFFFFFF);g.fillRect(x+dx,y+dy,2,2);}}
 private void paintOutcomePopup(Graphics g){int W=game.W,H=game.H,fh=Art.fh,w=Math.min(W-34,190),h=fh*5+14,x=(W-w)/2,y=(H-h)/2,col,titleCol;String title;if(caughtVisual){col=0x60D878;titleCol=0xFFF080;title=Lang.t("BẮT THÀNH CÔNG!","CAPTURED!");}else if(retry||throwCount>=3||(Data.category[enemy]==6&&hp>0&&ehp>0)){col=0xFFB040;titleCol=0xFFB060;title=Lang.t("BẮT HỤT!","CAPTURE FAILED!");}else{col=0xE75C58;titleCol=0xFF8078;title=Lang.t("POKÉMON ĐÃ HẸO!","POKÉMON FAINTED!");}Art.box(g,x,y,w,h,0x101827,col);Art.textBC(g,title,W/2,y+5,titleCol);String[] lines=Art.wrap(msg,w-14,2);for(int i=0;i<lines.length;i++)Art.textSmallC(g,lines[i],W/2,y+fh+9+i*fh,0xFFFFFF);Art.textSmallC(g,Lang.t("Nhấn 5 để tiếp tục","Press 5 to continue"),W/2,y+h-fh-5,0xFFE080);}
 private void paintOpportunity(Graphics g){int W=game.W,H=game.H,fh=Art.fh,w=Math.min(W-18,210),h=fh*7+14,x=(W-w)/2,y=(H-h)/2;Art.box(g,x,y,w,h,0x111A2C,0xFFE060);Art.textBC(g,Lang.t("ĐÂY LÀ THỜI CƠ THÍCH HỢP","THIS IS A GOOD CHANCE"),W/2,y+5,0xFFE060);Art.textSmallC(g,chance()+"%",W/2,y+fh+8,0x90FF98);String[] a={Lang.t("BẮT NGAY","CATCH NOW"),Lang.t("TIẾP TỤC ĐÁNH","KEEP FIGHTING")};int bw=(w-18)/2,by=y+h-fh*2-8;for(int i=0;i<2;i++){int bx=x+6+i*(bw+6);g.setColor(i==opportunityChoice?0x405B80:0x263348);g.fillRect(bx,by,bw,fh+6);g.setColor(i==opportunityChoice?0xFFE060:0x64758B);g.drawRect(bx,by,bw-1,fh+5);Art.textSmallC(g,a[i],bx+bw/2,by+3,0xFFFFFF);}}
 private void paintSide(Graphics g,int sp,int value,int max,int x,int y,int w,boolean enemySide){Art.avatarMini(g,sp,x,y);Art.textSmall(g,Data.name[sp],x+20,y,0xFFFFFF);int barY=y+17,bw=w-4;g.setColor(0x202430);g.fillRect(x,barY,bw,7);int fill=value*bw/Math.max(1,max);g.setColor(value*100/max<=20?0xE84040:0x55D868);g.fillRect(x,barY,fill,7);if(enemySide){int mark=x+bw/5;g.setColor(0xFF3030);g.fillRect(mark,barY-2,2,11);}Art.textSmall(g,"HP "+value+"/"+max,x,y+28,0xC8D8E8);Art.textSmall(g,Lang.t("Công ","ATK ")+Data.atk[sp]+Lang.t(" Thủ "," DEF ")+Data.def[sp],x,y+39,0xA8B8D0);Art.typeIcon(g,Data.t1[sp],x,y+51);if(Data.t2[sp]>=0)Art.typeIcon(g,Data.t2[sp],x+17,y+51);}
}
