package pac;
import javax.microedition.lcdui.Graphics;
/** Responsive per-map caught species grid, count and species detail. */
public final class ExploreDexScreen extends Screen{
 private final int gen;private int cursor,top;private boolean detail;
 public ExploreDexScreen(Game g,int generation){super(g);gen=generation;}
 private int columns(){int c=game.W/48;if(c<4)c=4;if(c>10)c=10;return c;}
 private int speciesAt(int rank){for(int sp=0;sp<Data.N;sp++)if(Data.isBase(sp)&&ExploreRules.gen(sp)==gen&&rank--==0)return sp;return-1;}
 public void update(int dt){}
 public void key(int k){if(detail){if(k==Game.K_FIRE||k==Game.K_0||k==Game.K_SOFT1||k==Game.K_SOFT2)detail=false;return;}int cols=columns(),n=ExploreRules.mapSpeciesCount(gen);if(k==Game.K_LEFT)cursor--;else if(k==Game.K_RIGHT)cursor++;else if(k==Game.K_UP)cursor-=cols;else if(k==Game.K_DOWN)cursor+=cols;else if(k==Game.K_FIRE||k==Game.K_SOFT1){detail=true;return;}else if(k==Game.K_0||k==Game.K_SOFT2){game.setScreen(new ExploreMapScreen(game));return;}if(cursor<0)cursor=0;if(cursor>=n)cursor=n-1;int rows=Math.max(2,(game.H-Art.fh*7)/(Art.fh*2+20)),row=cursor/cols;if(row<top)top=row;if(row>=top+rows)top=row-rows+1;}
 public void paint(Graphics g){int W=game.W,H=game.H,fh=Art.fh,n=ExploreRules.mapSpeciesCount(gen),u=ExploreRules.uniqueCaught(gen),cols=columns(),rows=Math.max(2,(H-fh*7)/(fh*2+20));g.setColor(0x101827);g.fillRect(0,0,W,H);Art.textBC(g,Lang.t("BỘ SƯU TẬP MAP GEN ","MAP COLLECTION GEN ")+gen,W/2,3,0xFFD030);Art.textSmallC(g,u+"/"+n+Lang.t(" loài đã bắt"," species caught"),W/2,fh+5,0x90E8A0);int cell=W/cols,rowH=fh*2+20,gy=fh*3;for(int r=0;r<rows;r++)for(int c=0;c<cols;c++){int rank=(top+r)*cols+c;if(rank>=n)continue;int sp=speciesAt(rank),x=c*cell,y=gy+r*rowH,caught=Save.exploreSpeciesCaught[sp];if(rank==cursor){g.setColor(0xFFD030);g.drawRect(x+2,y-2,cell-5,rowH-2);}if(caught>0){Art.avatarMini(g,sp,x+(cell-24)/2,y);Art.textSmallC(g,"x"+caught,x+cell/2,y+24,0xFFFFFF);}else Art.textBC(g,"?",x+cell/2,y+7,0x526078);}int yy=H-fh*4-5;Art.textSmallC(g,Lang.t("25% +1 Bạc • 50% +2 Bạc • 100% +","25% +1 Silver • 50% +2 Silver • 100% +")+ExploreRules.mapCompletionGold(gen)+Lang.t(" Vàng"," Gold"),W/2,yy,0xFFE080);int sp=speciesAt(cursor);if(sp>=0)Art.textSmallC(g,Save.exploreSpeciesCaught[sp]>0?Data.name[sp]+"  x"+Save.exploreSpeciesCaught[sp]:Lang.t("Chưa bắt","Not caught"),W/2,yy+fh,0xD8E4F2);Art.textSmallC(g,Lang.t("FIRE: chi tiết   Phím hướng: xem   0: về","FIRE: details   D-pad: browse   0: back"),W/2,H-fh-3,0x8090B0);if(detail)paintDetail(g,speciesAt(cursor));}
 private void paintDetail(Graphics g,int sp){if(sp<0)return;int W=game.W,H=game.H,fh=Art.fh,w=Math.min(W-18,210),h=Math.min(H-18,fh*11+26),x=(W-w)/2,y=(H-h)/2;Art.box(g,x,y,w,h,0x101827,0xFFD030);boolean caught=Save.exploreSpeciesCaught[sp]>0;Art.avatar(g,sp,x+8,y+8);Art.textB(g,caught?Data.name[sp]:"???",x+48,y+8,caught?0xFFFFFF:0x708098);if(caught){Art.typeIcon(g,Data.t1[sp],x+48,y+fh+10);if(Data.t2[sp]>=0)Art.typeIcon(g,Data.t2[sp],x+66,y+fh+10);int yy=y+52;line(g,Lang.t("Số lần bắt","Times caught"),Save.exploreSpeciesCaught[sp],x,w,yy);yy+=fh+3;line(g,"HP",Data.hp[sp],x,w,yy);yy+=fh+3;line(g,Lang.t("Công","ATK"),Data.atk[sp],x,w,yy);yy+=fh+3;line(g,Lang.t("Thủ","DEF"),Data.def[sp],x,w,yy);yy+=fh+3;line(g,Lang.t("Kháng","SDEF"),Data.speDef[sp],x,w,yy);yy+=fh+3;line(g,Lang.t("Tốc","SPD"),Data.speed[sp],x,w,yy);yy+=fh+3;Art.textSmall(g,Lang.t("Độ hiếm: ","Rarity: ")+Data.RARITY[Data.cost[sp]],x+9,yy,0xFFE080);}else Art.textSmallC(g,Lang.t("Hãy bắt loài này để mở thông tin.","Catch this species to reveal its data."),W/2,y+h/2,0xA8B8C8);Art.textSmallC(g,Lang.t("FIRE/0: đóng","FIRE/0: close"),W/2,y+h-fh-4,0x8090B0);}
 private void line(Graphics g,String s,int v,int x,int w,int y){Art.textSmall(g,s,x+9,y,0xB8C8D8);Art.textSmallR(g,""+v,x+w-9,y,0xFFFFFF);}
}
