package pac;
import javax.microedition.lcdui.Graphics;
/** Entry point for all offline Explore activities. */
public final class ExploreHubScreen extends Screen{
 private int sel;private static final int N=4;public ExploreHubScreen(Game g){super(g);}public void update(int dt){}
 public boolean pointer(int x,int y){int fh=Art.fh,gap=fh+10,top=Math.max(fh*3,game.H/2-(N*gap)/2),pick=(y-top+3)/gap;if(x>=game.W/8&&x<game.W*7/8&&y>=top-3&&pick<N&&(y-top+3)%gap<fh+6){sel=pick;if(confirmTouch(sel))key(Game.K_FIRE);}else if(y>=game.H-fh-8)key(Game.K_0);return true;}
 public void key(int k){if(k==Game.K_UP||k==Game.K_LEFT)sel=(sel+N-1)%N;else if(k==Game.K_DOWN||k==Game.K_RIGHT)sel=(sel+1)%N;else if(k==Game.K_0||k==Game.K_SOFT2)game.setScreen(new MenuScreen(game));else if(k==Game.K_FIRE||k==Game.K_SOFT1){if(sel==0)game.setScreen(new ExploreMapScreen(game));else if(sel==1)game.setScreen(new GachaScreen(game));else if(sel==2)game.setScreen(new SurvivalPickScreen(game));else game.setScreen(new ExploreBallScreen(game,true));}}
 public void paint(Graphics g){int W=game.W,H=game.H,fh=Art.fh;String[] n={Lang.t("THU THẬP POKÉMON","COLLECT POKÉMON"),Lang.t("GACHA POKÉMON","POKÉMON GACHA"),Lang.t("POKEMON NỔI LOẠN","POKEMON UPRISING"),Lang.t("ĐỔI \uE000","BALL EXCHANGE")};String[] d={Lang.t("Chọn khu Gen 1-3, chiến đấu rồi thu thập Pokémon hoang dã.","Choose a Gen 1-3 area, battle and collect wild Pokémon."),Lang.t("Quay Gen 1-3 theo Gen, Hệ hoặc Độ hiếm.","Draw Gen 1-3 by Gen, Type or Rarity."),Lang.t("Chọn pet đã sở hữu, thủ các đợt địch; chọn buff, tiến hóa và nhận \uE000.","Choose an owned Pokemon, survive waves, choose upgrades and earn \uE000."),Lang.t("Nâng cấp \uE000 để dùng trong Gacha.","Upgrade \uE000 for Gacha.")};g.setColor(0x101827);g.fillRect(0,0,W,H);Art.textBC(g,Lang.t("CHẾ ĐỘ KHÁM PHÁ","EXPLORE MODES"),W/2,12,0xFFD030);int gap=fh+10,y=Math.max(fh*3,H/2-(N*gap)/2);for(int i=0;i<N;i++){if(i==sel){g.setColor(0x305090);g.fillRect(W/8,y+i*gap-3,W*3/4,fh+6);g.setColor(0xFFD030);g.drawRect(W/8,y+i*gap-3,W*3/4-1,fh+5);}Art.textC(g,n[i],W/2,y+i*gap,i==sel?0xFFFFFF:0xAFC0D8);}Art.para(g,d[sel],8,H-fh*5,W-16,0x70D8FF,3);Art.textSmallC(g,"FIRE: "+Lang.t("chọn","select")+"   0: "+Lang.t("về","back"),W/2,H-fh-2,0x8090B0);}
}
