package pac;
import javax.microedition.lcdui.Graphics;
/** Independent animated Farm run: five KOs convert to one Ball at summary. */
public final class FarmScreen extends Screen{
 private static final int SELECT=0,SPAWN=1,FIGHT=2,SUMMARY=3;
 private final Rng rng=new Rng((int)System.currentTimeMillis());
 private int state=SELECT,hero=-1,enemy=-1,hp,mp,ehp,emp,kills,spawnT,heroAtk,enemyAtk,heroFlash,enemyFlash,heroSwing,enemySwing,time,button,summaryChoice;
 private int hx,hy,ex,ey,moveBank;private boolean actorsPlaced,moving;
 private boolean popup,paid;private int pick,pickTop,reward;
 public FarmScreen(Game g){super(g);if(Save.hero>=0&&Save.usable(Save.hero)&&Data.isBase(Save.hero))hero=Save.hero;else if(OwnedPokemon.count(-1)>0)hero=OwnedPokemon.at(0,-1);resetHero();}
 private int sceneY(){return Art.fh+4;}private int sceneH(){return Math.max(64,game.H-sceneY()-(Art.fh*7+24));}
 private void resetHero(){if(hero>=0){hp=Data.hp[hero];mp=0;}enemy=-1;ehp=emp=0;heroAtk=enemyAtk=heroFlash=enemyFlash=heroSwing=enemySwing=0;actorsPlaced=false;}
 private void placeHero(){int sy=sceneY(),sh=sceneH();hx=8;hy=sy+Math.max(5,sh/2-20);actorsPlaced=true;}
 private void start(){if(hero<0)return;kills=0;paid=false;reward=0;resetHero();placeHero();state=SPAWN;spawnT=3000;}
 public void update(int dt){time+=dt;if(heroFlash>0)heroFlash-=dt;if(enemyFlash>0)enemyFlash-=dt;if(heroSwing>0)heroSwing-=dt;if(enemySwing>0)enemySwing-=dt;if(state==SPAWN){spawnT-=dt;if(spawnT<=0)spawnEnemy();}else if(state==FIGHT)fight(dt);}
 private void spawnEnemy(){enemy=ExploreRules.farmLegendaryRound(kills+1)?pickLegendary():ExploreRules.pickAnyBase(rng);if(enemy<0)enemy=0;ehp=Data.hp[enemy];emp=0;heroAtk=enemyAtk=0;int sy=sceneY(),sh=sceneH();ex=Math.max(8,game.W-64);ey=sy+Math.max(5,sh/2-20+rng.nextInt(25)-12);state=FIGHT;moving=true;}
 private int pickLegendary(){int n=0;for(int i=0;i<Data.N;i++)if(Data.category[i]==6)n++;if(n==0)return Data.MEWTWO;int q=rng.nextInt(n);for(int i=0;i<Data.N;i++)if(Data.category[i]==6&&q--==0)return i;return Data.MEWTWO;}
 private void fight(int dt){int range=Math.min(92,38+Math.max(Data.range[hero],Data.range[enemy])*7),dx=ex-hx,dy=ey-hy;moving=Math.abs(dx)>range||Math.abs(dy)>10;if(moving){moveBank+=dt;int steps=moveBank/55;moveBank%=55;while(steps-->0){if(Math.abs(ex-hx)>range){if(hx<ex)hx++;else hx--;if(ex>hx)ex--;else ex++;}if(Math.abs(ey-hy)>8){if(hy<ey)hy++;else hy--;if(ey>hy)ey--;else ey++;}}return;}heroAtk+=dt;enemyAtk+=dt;int hc=Math.max(360,1150-Data.speed[hero]*7),ec=Math.max(420,1250-Data.speed[enemy]*7);if(heroAtk>=hc){heroAtk=0;heroSwing=220;enemyFlash=180;ehp-=Math.max(1,Data.atk[hero]);mp=Math.min(100,mp+10);check();}if(state==FIGHT&&enemyAtk>=ec){enemyAtk=0;enemySwing=220;heroFlash=180;hp-=Math.max(1,Data.atk[enemy]/2);emp=Math.min(100,emp+10);if(emp>=100){hp-=Math.max(2,Data.atk[enemy]);emp=0;}check();}}
 private void check(){if(ehp<=0){ehp=0;kills++;enemy=-1;state=SPAWN;spawnT=3000;}else if(hp<=0){hp=0;finish();}}
 private void skill(){if(state==FIGHT&&mp>=100){mp=0;heroSwing=420;enemyFlash=300;ehp-=Math.max(3,Data.atk[hero]*3);check();}}
 private void finish(){if(state==SUMMARY)return;state=SUMMARY;reward=ExploreRules.farmReward(kills);if(!paid){Save.balls+=reward;Save.save();paid=true;}summaryChoice=0;}
 public void key(int k){if(popup){keyPopup(k);return;}if(state==SUMMARY){if(k==Game.K_LEFT||k==Game.K_UP)summaryChoice=0;else if(k==Game.K_RIGHT||k==Game.K_DOWN)summaryChoice=1;else if(k==Game.K_FIRE||k==Game.K_SOFT1){if(summaryChoice==0)start();else game.setScreen(new ExploreHubScreen(game));}return;}if(k==Game.K_LEFT)button=(button+2)%3;else if(k==Game.K_RIGHT)button=(button+1)%3;else if(k==Game.K_FIRE||k==Game.K_SOFT1){if(button==0&&state==SELECT){popup=true;pick=0;pickTop=0;}else if(button==1){if(state==SELECT)start();else skill();}else if(button==2)finish();}else if(k==Game.K_0||k==Game.K_SOFT2){if(state==SELECT)game.setScreen(new ExploreHubScreen(game));else finish();}}
 private void keyPopup(int k){int count=OwnedPokemon.count(-1),cols=Math.max(3,game.W/38);if(k==Game.K_LEFT&&pick>0)pick--;else if(k==Game.K_RIGHT&&pick<count-1)pick++;else if(k==Game.K_UP&&pick>=cols)pick-=cols;else if(k==Game.K_DOWN&&pick+cols<count)pick+=cols;else if((k==Game.K_FIRE||k==Game.K_SOFT1)&&count>0){hero=OwnedPokemon.at(pick,-1);Save.hero=hero;Save.save();resetHero();popup=false;}else if(k==Game.K_0||k==Game.K_SOFT2)popup=false;}
 public void paint(Graphics g){int W=game.W,H=game.H,fh=Art.fh,sceneY=fh+4,infoH=fh*7+24,sceneH=H-sceneY-infoH;if(sceneH<64)sceneH=64;CampMap.draw(g,0,sceneY,W,sceneH);g.setColor(0x0D1720);g.fillRect(0,0,W,sceneY);Art.textBC(g,Lang.t("FARM PET","PET FARM")+"   KO "+kills,W/2,2,0xFFD030);
  if(hero>=0){if(!actorsPlaced)placeHero();int ha=heroFlash>0?RawAtlas.HURT:(heroSwing>0?RawAtlas.ATTACK:(moving||state==SPAWN?RawAtlas.WALK:RawAtlas.IDLE));drawModel(g,hero,hx+(heroSwing>0?3:0),hy,ha,2,time/90);}if(enemy>=0){int ea=enemyFlash>0?RawAtlas.HURT:(enemySwing>0?RawAtlas.ATTACK:(moving?RawAtlas.WALK:RawAtlas.IDLE));drawModel(g,enemy,ex-(enemySwing>0?3:0),ey,ea,6,time/90+2);}if(state==SPAWN){int px=Math.max(28,W-36),py=sceneY+sceneH/2;int shrink=3-Math.max(0,spawnT)*4/3001;GachaFx.farmPortal(g,px,py,time,shrink);Art.textSmallC(g,Lang.t("Địch mới sau ","Next foe in ")+(spawnT+999)/1000+"s",px,sceneY+3,0xFFFFFF);}
  int iy=sceneY+sceneH;g.setColor(0x111B28);g.fillRect(0,iy,W,H-iy);g.setColor(0x40506A);g.drawLine(W/2,iy,W/2,iy+fh*4+8);paintInfo(g,true,0,iy,W/2);paintInfo(g,false,W/2,iy,W-W/2);paintButtons(g,iy+fh*4+10);if(popup)paintPopup(g);if(state==SUMMARY)paintSummary(g);
 }
 private void drawModel(Graphics g,int sp,int x,int y,int action,int dir,int clock){if(!RawAtlas.draw(g,sp,x,y,56,44,action,dir,clock))Art.sprite(g,sp,x+12,y+6,32);}
 private void paintInfo(Graphics g,boolean mine,int x,int y,int w){int fh=Art.fh,sp=mine?hero:enemy;if(sp<0){Art.textSmallC(g,mine?Lang.t("Chưa chọn pet","No partner"):Lang.t("Đang chờ...","Waiting..."),x+w/2,y+5,0x90A0B0);return;}int avx=mine?x+3:x+w-35,tx=mine?x+38:x+3,tw=w-41;Art.avatar(g,sp,avx,y+3);int chp=mine?hp:ehp,cm=mine?mp:emp;Art.textSmall(g,Data.name[sp],tx,y+2,0xFFFFFF);Art.bar(g,tx,y+fh+2,tw,5,chp,Data.hp[sp],mine?0x48D878:0xE85858);Art.bar(g,tx,y+fh+9,tw,4,cm,100,0x50A8FF);Art.textSmall(g,"AT "+Data.atk[sp]+" DF "+Data.def[sp]+" SP "+Data.speed[sp],tx,y+fh*2+5,0xC8D8E8);}
 private void paintButtons(Graphics g,int y){int W=game.W,fh=Art.fh,bw=W/3;String[] a={Lang.t("THAY PET","CHANGE"),state==SELECT?Lang.t("XÁC NHẬN","CONFIRM"):Lang.t("KỸ NĂNG","SKILL"),Lang.t("TỔNG KẾT","SUMMARY")};for(int i=0;i<3;i++){boolean disabled=i==0&&state!=SELECT;g.setColor(i==button&&!disabled?0x405A80:0x263448);g.fillRect(i*bw+1,y,bw-2,fh+7);if(i==button&&!disabled){g.setColor(0xFFE060);g.drawRect(i*bw+1,y,bw-3,fh+6);}Art.textSmallC(g,a[i],i*bw+bw/2,y+3,disabled?0x596575:0xFFFFFF);}Art.textSmallC(g,Lang.t("5 KO = 1 Bóng, phần dư bị bỏ","5 KOs = 1 Ball; remainder discarded"),W/2,y+fh+9,0xFFE080);}
 private void paintPopup(Graphics g){int W=game.W,H=game.H,fh=Art.fh,bx=6,by=fh*2,bw=W-12,bh=H-fh*4,count=OwnedPokemon.count(-1),cols=Math.max(3,bw/38),cell=bw/cols,row=38,rows=(bh-fh*3)/row;if(rows<1)rows=1;int pr=pick/cols;if(pr<pickTop)pickTop=pr;if(pr>=pickTop+rows)pickTop=pr-rows+1;Art.box(g,bx,by,bw,bh,0x111A27,0x80D8FF);Art.textBC(g,Lang.t("CHỌN PET FARM","CHOOSE FARM PARTNER"),W/2,by+4,0xFFD060);int y0=by+fh+8;for(int r=0;r<rows;r++)for(int c=0;c<cols;c++){int i=(pickTop+r)*cols+c;if(i>=count)continue;int sp=OwnedPokemon.at(i,-1),xx=bx+c*cell+(cell-32)/2,yy=y0+r*row;if(i==pick){g.setColor(0xFFE060);g.drawRect(xx-2,yy-2,35,35);}Art.avatar(g,sp,xx,yy);}if(count>0){int sp=OwnedPokemon.at(pick,-1);Art.textSmallC(g,Data.name[sp]+"  HP "+Data.hp[sp]+" AT "+Data.atk[sp]+" DF "+Data.def[sp],W/2,by+bh-fh*2,0xA0E8FF);}Art.textSmallC(g,Lang.t("Pet đang treo không xuất hiện ở đây","Camped Pokémon are unavailable"),W/2,by+bh-fh,0x8090B0);}
 private void paintSummary(Graphics g){int W=game.W,H=game.H,fh=Art.fh,w=Math.min(W-16,190),h=fh*8,x=(W-w)/2,y=(H-h)/2;Art.box(g,x,y,w,h,0x111624,0xFFD060);Art.textBC(g,hp<=0?Lang.t("PET ĐÃ GỤC","PARTNER FAINTED"):Lang.t("TỔNG KẾT FARM","FARM SUMMARY"),W/2,y+5,hp<=0?0xFF7070:0xFFD030);Art.textC(g,Lang.t("Đã hạ: ","Defeated: ")+kills,W/2,y+fh*2,0xFFFFFF);Art.textC(g,Lang.t("Nhận: ","Reward: ")+reward+Lang.t(" Bóng"," Balls"),W/2,y+fh*3,0x80FF90);Art.textSmallC(g,Lang.t("Dư ","Discarded ")+(kills%5)+Lang.t(" KO bị bỏ"," KOs"),W/2,y+fh*4,0xA0A8B8);String[] a={Lang.t("ĐI TIẾP","CONTINUE"),Lang.t("THOÁT","EXIT")};for(int i=0;i<2;i++){int bx=x+8+i*(w/2-4),bw=w/2-12,by=y+fh*5+5;g.setColor(i==summaryChoice?0x405A80:0x283448);g.fillRect(bx,by,bw,fh+7);if(i==summaryChoice){g.setColor(0xFFE060);g.drawRect(bx,by,bw-1,fh+6);}Art.textSmallC(g,a[i],bx+bw/2,by+3,0xFFFFFF);}}
}
