package pac;
import javax.microedition.lcdui.Graphics;
/** One-Ball collection draw filtered by generation, type or rarity. */
public final class GachaScreen extends Screen{
 private int kind,value,last=-1;private boolean lastNew;private final Rng rng=new Rng((int)System.currentTimeMillis());public GachaScreen(Game g){super(g);}public void update(int dt){}
 private int max(){return kind==0?3:(kind==1?Data.NT:Data.CATEGORY_NAME.length);}private String filter(){return kind==0?Lang.t("Thế hệ ","Generation ")+(value+1):(kind==1?Lang.typeName(value):Data.CATEGORY_NAME[value]);}
 public void key(int k){if(k==Game.K_UP){kind=(kind+2)%3;value=0;}else if(k==Game.K_DOWN){kind=(kind+1)%3;value=0;}else if(k==Game.K_LEFT)value=(value+max()-1)%max();else if(k==Game.K_RIGHT)value=(value+1)%max();else if(k==Game.K_0||k==Game.K_SOFT2)game.setScreen(new ExploreHubScreen(game));else if(k==Game.K_FIRE||k==Game.K_SOFT1){if(Save.balls<=0)return;int sp=ExploreRules.pick(rng,kind,kind==0?value+1:value);if(sp>=0){Save.balls--;last=sp;lastNew=Save.unlockFamily(sp);Save.caught++;if(!lastNew)Save.balls++;Save.save();}}}
 public void paint(Graphics g){int W=game.W,H=game.H,fh=Art.fh;g.setColor(0x12182A);g.fillRect(0,0,W,H);Art.textBC(g,Lang.t("GACHA POKÉMON","POKÉMON GACHA"),W/2,5,0xFFD030);Art.textC(g,(kind==0?"GEN":(kind==1?Lang.t("HỆ","TYPE"):Lang.t("ĐỘ HIẾM","RARITY")))+": < "+filter()+" >",W/2,fh*3,0x80D8FF);if(last>=0){Art.formationSprite(g,last,W/2-40,fh*5,80,70,W,0);Art.textBC(g,Data.name[last],W/2,fh*5+74,0xFFFFFF);Art.textC(g,lastNew?Lang.t("MỚI - đã mở cả family","NEW - family unlocked"):Lang.t("Trùng - hoàn lại Bóng","Duplicate - Ball refunded"),W/2,fh*5+fh+75,lastNew?0x80FF90:0xFFD070);}else Art.textC(g,Lang.t("Tốn 1 Bóng mỗi lượt","Costs 1 Ball per draw"),W/2,H/2,0xB8C8E0);Art.textC(g,Lang.t("Bóng: ","Balls: ")+Save.balls,W/2,H-fh*4,0xFF9090);Art.textSmallC(g,Lang.t("2/8 loại  4/6 lọc  FIRE quay  0 về","2/8 kind  4/6 filter  FIRE draw  0 back"),W/2,H-fh-2,0x8090B0);}
}
