package pac;

/** Full item catalogue generated from app.zip Item enum, stats and recipes. */
public final class ItemData {
    private ItemData() {}
    public static final String[] ID={
        "FOSSIL_STONE","TWISTED_SPOON","MYSTIC_WATER","MAGNET","BLACK_GLASSES",
        "MIRACLE_SEED","NEVER_MELT_ICE","CHARCOAL","HEART_SCALE","OLD_AMBER",
        "DAWN_STONE","WATER_STONE","THUNDER_STONE","FIRE_STONE","MOON_STONE",
        "DUSK_STONE","LEAF_STONE","ICE_STONE","CHOICE_SPECS","SOUL_DEW",
        "UPGRADE","REAPER_CLOTH","POKEMONOMICON","ABILITY_SHIELD","POWER_LENS",
        "SHELL_BELL","HEAVY_DUTY_BOOTS","AQUA_EGG","BLUE_ORB","SCOPE_LENS",
        "STAR_DUST","GREEN_ORB","DEEP_SEA_TOOTH","SMOKE_BALL","XRAY_VISION",
        "RAZOR_FANG","PROTECTIVE_PADS","LOADED_DICE","PUNCHING_GLOVE","MUSCLE_BAND",
        "WONDER_BOX","STICKY_BARB","WIDE_LENS","RAZOR_CLAW","SAFETY_GOGGLES",
        "KINGS_ROCK","SHINY_CHARM","GRACIDEA_FLOWER","FLAME_ORB","ASSAULT_VEST",
        "AMULET_COIN","POKE_DOLL","RED_ORB","MAX_REVIVE","ROCKY_HELMET",
        "AGUAV_BERRY","APICOT_BERRY","ASPEAR_BERRY","BABIRI_BERRY","CHERI_BERRY",
        "CHESTO_BERRY","GANLON_BERRY","JABOCA_BERRY","LANSAT_BERRY","LEPPA_BERRY",
        "LIECHI_BERRY","LUM_BERRY","ORAN_BERRY","PECHA_BERRY","PERSIM_BERRY",
        "PETAYA_BERRY","RAWST_BERRY","ROWAP_BERRY","SALAC_BERRY","SITRUS_BERRY",
        "GOLDEN_RAZZ_BERRY","GOLDEN_NANAB_BERRY","GOLDEN_PINAP_BERRY","COMFEY","ELECTIRIZER",
        "MAGMARIZER","MACHO_BRACE","LIGHT_BALL","DRAGON_SCALE","METRONOME",
        "EXPLORER_KIT","METAL_COAT","AIR_BALLOON","PROTECTOR","INCENSE",
        "EXP_SHARE","TERRAIN_EXTENDER","POKERUS_VIAL","SPELL_TAG","SHED_SHELL",
        "BERSERK_GENE","SURFBOARD","COOKING_POT","RUNNING_SHOES","MAX_ELIXIR",
        "METEORITE","ROTOM_CATALOG","TRASH","DYNAMAX_BAND","SHINY_STONE",
        "OLD_ROD","GOOD_ROD","SUPER_ROD","RARE_CANDY","EVIOLITE",
        "RED_SCALE","GOLD_MASK","GOLD_BOTTLE_CAP","ABSORB_BULB","SACRED_ASH",
        "STAR_PIECE","REPEAT_BALL","GOLD_BOW","DAMP_ROCK","ICY_ROCK",
        "HEAT_ROCK","SMOOTH_ROCK","BLACK_AUGURITE","FLOAT_STONE","MIST_STONE",
        "ELECTRIC_QUARTZ","BLOOD_STONE","SMELLY_CLAY","ODD_KEYSTONE","SUN_STONE",
        "NORMAL_GEM","GRASS_GEM","FIRE_GEM","WATER_GEM","ELECTRIC_GEM",
        "FIGHTING_GEM","PSYCHIC_GEM","DARK_GEM","STEEL_GEM","GROUND_GEM",
        "POISON_GEM","DRAGON_GEM","FIELD_GEM","MONSTER_GEM","HUMAN_GEM",
        "AQUATIC_GEM","BUG_GEM","FLYING_GEM","FLORA_GEM","ROCK_GEM",
        "GHOST_GEM","FAIRY_GEM","ICE_GEM","FOSSIL_GEM","SOUND_GEM",
        "ARTIFICIAL_GEM","LIGHT_GEM","WILD_GEM","AMORPHOUS_GEM","GOURMET_GEM",
        "FIRE_SHARD","TEAL_MASK","WELLSPRING_MASK","CORNERSTONE_MASK","HEARTHFLAME_MASK",
        "ZYGARDE_CUBE","TM_RAGE","TM_RETURN","TM_COUNTER","TM_DISABLE",
        "TM_BULK_UP","TM_CHARGE","TM_REFLECT","TM_PAYDAY","TM_FOCUS_PUNCH",
        "TM_HYPER_BEAM","TM_SUBSTITUTE","TM_SKILL_SWAP","CHEF_HAT","PICNIC_SET",
        "SANDWICH","HEARTY_STEW","RAGE_CANDY_BAR","TEA","CURRY",
        "CASTELIACONE","WHIPPED_DREAM","BERRY_JUICE","NANAB_BERRY","OLIVE_OIL",
        "LUCKY_EGG","TART_APPLE","SWEET_APPLE","SIRUPY_APPLE","HERBA_MYSTICA",
        "HERBA_MYSTICA_SWEET","HERBA_MYSTICA_SPICY","HERBA_MYSTICA_SOUR","HERBA_MYSTICA_BITTER","HERBA_MYSTICA_SALTY",
        "MOOMOO_MILK","HONEY","MUSHROOMS","TINY_MUSHROOM","BIG_MUSHROOM",
        "BALM_MUSHROOM","RICE","BERRIES","POFFIN","ROCK_SALT",
        "NUTRITIOUS_EGG","LEFTOVERS","BLACK_SLUDGE","FRUIT_JUICE","LEEK",
        "LARGE_LEEK","SMOKED_FILET","SPINDA_COCKTAIL","BINDING_MOCHI","STRAWBERRY_SWEET",
        "LOVE_SWEET","BERRY_SWEET","CLOVER_SWEET","FLOWER_SWEET","STAR_SWEET",
        "RIBBON_SWEET","SWEETS","VANILLA_FLAVOR","RUBY_FLAVOR","MATCHA_FLAVOR",
        "MINT_FLAVOR","LEMON_FLAVOR","SALTED_FLAVOR","RUBY_SWIRL_FLAVOR","CARAMEL_SWIRL_FLAVOR",
        "RAINBOW_SWIRL_FLAVOR","EGG_FOR_SELL","COIN","NUGGET","BIG_NUGGET",
        "GIMMIGHOUL_COIN","EXCHANGE_TICKET","RECYCLE_TICKET","TREASURE_BOX","AUSPICIOUS_ARMOR",
        "MALICIOUS_ARMOR","RUSTED_SWORD","SCROLL_OF_WATERS","SCROLL_OF_DARKNESS","MYSTERY_BOX",
        "RICH_MULCH","AMAZE_MULCH","BRONZE_DOJO_TICKET","SILVER_DOJO_TICKET","GOLD_DOJO_TICKET",
        "WANTED_NOTICE","MEMORY_DISCS","FIRE_MEMORY","FOSSIL_MEMORY","PSYCHIC_MEMORY",
        "WATER_MEMORY","ELECTRIC_MEMORY","FAIRY_MEMORY","DARK_MEMORY","GRASS_MEMORY",
        "ICE_MEMORY","FIGHTING_MEMORY","POISON_MEMORY","SOUND_MEMORY","STEEL_MEMORY",
        "FLYING_MEMORY","ROCK_MEMORY","GROUND_MEMORY","FIELD_MEMORY","GHOST_MEMORY",
        "LIGHT_MEMORY","NORMAL_MEMORY","BUG_MEMORY","GOURMET_MEMORY","MONSTER_MEMORY",
        "AQUATIC_MEMORY","DRAGON_MEMORY","FLORA_MEMORY","MISSION_ORDER_PINK","MISSION_ORDER_RED",
        "MISSION_ORDER_BLUE","MISSION_ORDER_GREEN","MISSION_ORDER_GOLD","LEADERS_CREST","LAPRAS_PASSPORT",
        "CELL_BATTERY","SILK_SCARF","FRIEND_BOW","BLACK_BELT","MACH_RIBBON",
        "EXPLOSIVE_BAND","TWIST_BAND","BIG_EATER_BELT","LUCKY_RIBBON","COVER_BAND",
        "EFFICIENT_BANDANNA","NULLIFY_BANDANNA","TATSUGIRI_CURLY","TATSUGIRI_DROOPY","TATSUGIRI_STRETCHY",
        "CONFUSE_WAND","PETRIFY_WAND","SLOW_WAND","SLUMBER_WAND","BLAST_WAND",
        "HP_SWAP_WAND","SPIRIT_WAND","LONG_WAND","GUIDING_WAND","SURROUND_WAND",
        "POUNCE_WAND","TWO_EDGED_WAND","WARP_WAND","SWITCHER_WAND","WHIRLWIND_WAND",
        "TUNNEL_WAND","AQUA_MONICA","FIERY_DRUM","GRASS_CORNET","ICY_FLUTE",
        "ROCK_HORN","SKY_MELODICA","TERRA_CYMBAL","SOOTHE_BELL","BALL",
        "BERRIES_GIFT","SWEETS_GIFT","DITTO_GIFT","TICKET_BUNDLE","HATCH_BUNDLE",
        "REGIONAL_TOUR","BANQUET","GEMS_BUNDLE","POTION","FORAGE_BAG",
        "COLLECTION_BOX","PRETTY_BOX","DELUXE_BOX","TOOLBOX","SMALL_EXP_GIFT",
        "LARGE_EXP_GIFT","STAR_GIFT","COMMON_GIFT","UNCOMMON_GIFT","RARE_GIFT",
        "EPIC_GIFT","ULTRA_GIFT","UNIQUE_GIFT","LEGENDARY_GIFT","PURPLE_NECTAR",
        "RED_NECTAR","PINK_NECTAR","YELLOW_NECTAR"
    };
    public static final String[] EN={
        "Fossil Stone","Twisted Spoon","Mystic Water","Magnet","Black Glasses",
        "Miracle Seed","Never Melt Ice","Charcoal","Heart Scale","Old Amber",
        "Dawn Stone","Water Stone","Thunder Stone","Fire Stone","Moon Stone",
        "Dusk Stone","Leaf Stone","Ice Stone","Choice Specs","Soul Dew",
        "Upgrade","Reaper Cloth","Pokemonomicon","Ability Shield","Power Lens",
        "Shell Bell","Heavy Duty Boots","Aqua Egg","Blue Orb","Scope Lens",
        "Star Dust","Green Orb","Deep Sea Tooth","Smoke Ball","Xray Vision",
        "Razor Fang","Protective Pads","Loaded Dice","Punching Glove","Muscle Band",
        "Wonder Box","Sticky Barb","Wide Lens","Razor Claw","Safety Goggles",
        "Kings Rock","Shiny Charm","Gracidea Flower","Flame Orb","Assault Vest",
        "Amulet Coin","Poke Doll","Red Orb","Max Revive","Rocky Helmet",
        "Aguav Berry","Apicot Berry","Aspear Berry","Babiri Berry","Cheri Berry",
        "Chesto Berry","Ganlon Berry","Jaboca Berry","Lansat Berry","Leppa Berry",
        "Liechi Berry","Lum Berry","Oran Berry","Pecha Berry","Persim Berry",
        "Petaya Berry","Rawst Berry","Rowap Berry","Salac Berry","Sitrus Berry",
        "Golden Razz Berry","Golden Nanab Berry","Golden Pinap Berry","Comfey","Electirizer",
        "Magmarizer","Macho Brace","Light Ball","Dragon Scale","Metronome",
        "Explorer Kit","Metal Coat","Air Balloon","Protector","Incense",
        "Exp Share","Terrain Extender","Pokerus Vial","Spell Tag","Shed Shell",
        "Berserk Gene","Surfboard","Cooking Pot","Running Shoes","Max Elixir",
        "Meteorite","Rotom Catalog","Trash","Dynamax Band","Shiny Stone",
        "Old Rod","Good Rod","Super Rod","Rare Candy","Eviolite",
        "Red Scale","Gold Mask","Gold Bottle Cap","Absorb Bulb","Sacred Ash",
        "Star Piece","Repeat Ball","Gold Bow","Damp Rock","Icy Rock",
        "Heat Rock","Smooth Rock","Black Augurite","Float Stone","Mist Stone",
        "Electric Quartz","Blood Stone","Smelly Clay","Odd Keystone","Sun Stone",
        "Normal Gem","Grass Gem","Fire Gem","Water Gem","Electric Gem",
        "Fighting Gem","Psychic Gem","Dark Gem","Steel Gem","Ground Gem",
        "Poison Gem","Dragon Gem","Field Gem","Monster Gem","Human Gem",
        "Aquatic Gem","Bug Gem","Flying Gem","Flora Gem","Rock Gem",
        "Ghost Gem","Fairy Gem","Ice Gem","Fossil Gem","Sound Gem",
        "Artificial Gem","Light Gem","Wild Gem","Amorphous Gem","Gourmet Gem",
        "Fire Shard","Teal Mask","Wellspring Mask","Cornerstone Mask","Hearthflame Mask",
        "Zygarde Cube","TM Rage","TM Return","TM Counter","TM Disable",
        "TM Bulk Up","TM Charge","TM Reflect","TM Payday","TM Focus Punch",
        "TM Hyper Beam","TM Substitute","TM Skill Swap","Chef Hat","Picnic Set",
        "Sandwich","Hearty Stew","Rage Candy Bar","Tea","Curry",
        "Casteliacone","Whipped Dream","Berry Juice","Nanab Berry","Olive Oil",
        "Lucky Egg","Tart Apple","Sweet Apple","Sirupy Apple","Herba Mystica",
        "Herba Mystica Sweet","Herba Mystica Spicy","Herba Mystica Sour","Herba Mystica Bitter","Herba Mystica Salty",
        "Moomoo Milk","Honey","Mushrooms","Tiny Mushroom","Big Mushroom",
        "Balm Mushroom","Rice","Berries","Poffin","Rock Salt",
        "Nutritious Egg","Leftovers","Black Sludge","Fruit Juice","Leek",
        "Large Leek","Smoked Filet","Spinda Cocktail","Binding Mochi","Strawberry Sweet",
        "Love Sweet","Berry Sweet","Clover Sweet","Flower Sweet","Star Sweet",
        "Ribbon Sweet","Sweets","Vanilla Flavor","Ruby Flavor","Matcha Flavor",
        "Mint Flavor","Lemon Flavor","Salted Flavor","Ruby Swirl Flavor","Caramel Swirl Flavor",
        "Rainbow Swirl Flavor","Egg For Sell","Coin","Nugget","Big Nugget",
        "Gimmighoul Coin","Exchange Ticket","Recycle Ticket","Treasure Box","Auspicious Armor",
        "Malicious Armor","Rusted Sword","Scroll Of Waters","Scroll Of Darkness","Mystery Box",
        "Rich Mulch","Amaze Mulch","Bronze Dojo Ticket","Silver Dojo Ticket","Gold Dojo Ticket",
        "Wanted Notice","Memory Discs","Fire Memory","Fossil Memory","Psychic Memory",
        "Water Memory","Electric Memory","Fairy Memory","Dark Memory","Grass Memory",
        "Ice Memory","Fighting Memory","Poison Memory","Sound Memory","Steel Memory",
        "Flying Memory","Rock Memory","Ground Memory","Field Memory","Ghost Memory",
        "Light Memory","Normal Memory","Bug Memory","Gourmet Memory","Monster Memory",
        "Aquatic Memory","Dragon Memory","Flora Memory","Mission Order Pink","Mission Order Red",
        "Mission Order Blue","Mission Order Green","Mission Order Gold","Leaders Crest","Lapras Passport",
        "Cell Battery","Silk Scarf","Friend Bow","Black Belt","Mach Ribbon",
        "Explosive Band","Twist Band","Big Eater Belt","Lucky Ribbon","Cover Band",
        "Efficient Bandanna","Nullify Bandanna","Tatsugiri Curly","Tatsugiri Droopy","Tatsugiri Stretchy",
        "Confuse Wand","Petrify Wand","Slow Wand","Slumber Wand","Blast Wand",
        "HP Swap Wand","Spirit Wand","Long Wand","Guiding Wand","Surround Wand",
        "Pounce Wand","Two Edged Wand","Warp Wand","Switcher Wand","Whirlwind Wand",
        "Tunnel Wand","Aqua Monica","Fiery Drum","Grass Cornet","Icy Flute",
        "Rock Horn","Sky Melodica","Terra Cymbal","Soothe Bell","Ball",
        "Berries Gift","Sweets Gift","Ditto Gift","Ticket Bundle","Hatch Bundle",
        "Regional Tour","Banquet","Gems Bundle","Potion","Forage Bag",
        "Collection Box","Pretty Box","Deluxe Box","Toolbox","Small Exp Gift",
        "Large Exp Gift","Star Gift","Common Gift","Uncommon Gift","Rare Gift",
        "Epic Gift","Ultra Gift","Unique Gift","Legendary Gift","Purple Nectar",
        "Red Nectar","Pink Nectar","Yellow Nectar"
    };
    public static final String[] VI={
        "Đá Hóa Thạch","Thìa Xoắn","Nước Huyền Bí","Nam Châm","Kính Đen",
        "Hạt Kỳ Diệu","Băng Vĩnh Cửu","Than Củi","Vảy Tim","Cũ Amber",
        "Dawn Đá","Nước Đá","Thunder Đá","Lửa Đá","Moon Đá",
        "Dusk Đá","Leaf Đá","Băng Đá","Kính Lựa Chọn","Soul Dew",
        "Upgrade","Vải Tử Thần","Pokemonomicon","Ability Shield","Power Lens",
        "Chuông Vỏ Sò","Heavy Duty Boots","Aqua Egg","Xanh Lam Cầu","Scope Lens",
        "Star Dust","Xanh Lá Cầu","Deep Sea Tooth","Smoke Ball","Xray Vision",
        "Razor Fang","Protective Pads","Loaded Dice","Punching Glove","Đai Cơ Bắp",
        "Wonder Hộp","Sticky Barb","Wide Lens","Razor Claw","Safety Goggles",
        "Đá Vương Giả","Shiny Charm","Gracidea Flower","Flame Cầu","Áo Khoác Xung Kích",
        "Đồng Xu Hộ Mệnh","Búp Bê Pokémon","Đỏ Cầu","Max Revive","Mũ Đá",
        "Aguav Quả","Apicot Quả","Aspear Quả","Babiri Quả","Cheri Quả",
        "Chesto Quả","Ganlon Quả","Jaboca Quả","Lansat Quả","Leppa Quả",
        "Liechi Quả","Lum Quả","Oran Quả","Pecha Quả","Persim Quả",
        "Petaya Quả","Rawst Quả","Rowap Quả","Salac Quả","Sitrus Quả",
        "Vàng Razz Quả","Vàng Nanab Quả","Vàng Pinap Quả","Comfey","Electirizer",
        "Magmarizer","Macho Brace","Cầu Ánh Sáng","Rồng Scale","Metronome",
        "Explorer Kit","Áo Kim Loại","Air Balloon","Protector","Incense",
        "Chia Sẻ Kinh Nghiệm","Terrain Extender","Pokerus Vial","Spell Tag","Shed Shell",
        "Berserk Gene","Surfboard","Cooking Pot","Running Shoes","Max Elixir",
        "Meteorite","Rotom Catalog","Trash","Dynamax Đai","Shiny Đá",
        "Cũ Rod","Good Rod","Super Rod","Kẹo Hiếm","Eviolite",
        "Đỏ Scale","Vàng Mặt Nạ","Vàng Bottle Cap","Absorb Bulb","Sacred Ash",
        "Star Piece","Repeat Ball","Vàng Bow","Damp Đá","Icy Đá",
        "Heat Đá","Smooth Đá","Đen Augurite","Float Đá","Mist Đá",
        "Điện Quartz","Blood Đá","Smelly Clay","Odd Keystone","Sun Đá",
        "Thường Ngọc","Cỏ Ngọc","Lửa Ngọc","Nước Ngọc","Điện Ngọc",
        "Chiến Đấu Ngọc","Tâm Linh Ngọc","Bóng Tối Ngọc","Thép Ngọc","Đất Ngọc",
        "Độc Ngọc","Rồng Ngọc","Field Ngọc","Monster Ngọc","Human Ngọc",
        "Aquatic Ngọc","Bọ Ngọc","Bay Ngọc","Flora Ngọc","Đá Ngọc",
        "Ma Ngọc","Tiên Ngọc","Băng Ngọc","Hóa Thạch Ngọc","Sound Ngọc",
        "Artificial Ngọc","Ánh Sáng Ngọc","Wild Ngọc","Amorphous Ngọc","Gourmet Ngọc",
        "Lửa Shard","Teal Mặt Nạ","Wellspring Mặt Nạ","Cornerstone Mặt Nạ","Hearthflame Mặt Nạ",
        "Zygarde Cube","Tm Rage","Tm Return","Tm Counter","Tm Disable",
        "Tm Bulk Up","Tm Charge","Tm Reflect","Tm Payday","Tm Focus Punch",
        "Tm Hyper Beam","Tm Substitute","Tm Skill Swap","Chef Hat","Picnic Set",
        "Sandwich","Hearty Stew","Rage Candy Bar","Tea","Curry",
        "Casteliacone","Whipped Dream","Quả Juice","Nanab Quả","Olive Oil",
        "Trứng May Mắn","Tart Apple","Kẹo Apple","Sirupy Apple","Herba Mystica",
        "Herba Mystica Kẹo","Herba Mystica Spicy","Herba Mystica Sour","Herba Mystica Bitter","Herba Mystica Salty",
        "Moomoo Milk","Honey","Mushrooms","Tiny Mushroom","Lớn Mushroom",
        "Balm Mushroom","Rice","Berries","Poffin","Đá Salt",
        "Nutritious Egg","Thức Ăn Thừa","Đen Sludge","Fruit Juice","Leek",
        "Large Leek","Smoked Filet","Spinda Cocktail","Binding Mochi","Strawberry Kẹo",
        "Love Kẹo","Quả Kẹo","Clover Kẹo","Flower Kẹo","Star Kẹo",
        "Ruy Băng Kẹo","Sweets","Vanilla Vị","Ruby Vị","Matcha Vị",
        "Mint Vị","Lemon Vị","Salted Vị","Ruby Swirl Vị","Caramel Swirl Vị",
        "Rainbow Swirl Vị","Egg For Sell","Coin","Nugget","Lớn Nugget",
        "Gimmighoul Coin","Exchange Vé","Recycle Vé","Treasure Hộp","Auspicious Armor",
        "Malicious Armor","Rusted Sword","Scroll Of Waters","Scroll Of Darkness","Mystery Hộp",
        "Rich Mulch","Amaze Mulch","Bronze Dojo Vé","Silver Dojo Vé","Vàng Dojo Vé",
        "Wanted Notice","Bộ Nhớ Discs","Lửa Bộ Nhớ","Hóa Thạch Bộ Nhớ","Tâm Linh Bộ Nhớ",
        "Nước Bộ Nhớ","Điện Bộ Nhớ","Tiên Bộ Nhớ","Bóng Tối Bộ Nhớ","Cỏ Bộ Nhớ",
        "Băng Bộ Nhớ","Chiến Đấu Bộ Nhớ","Độc Bộ Nhớ","Sound Bộ Nhớ","Thép Bộ Nhớ",
        "Bay Bộ Nhớ","Đá Bộ Nhớ","Đất Bộ Nhớ","Field Bộ Nhớ","Ma Bộ Nhớ",
        "Ánh Sáng Bộ Nhớ","Thường Bộ Nhớ","Bọ Bộ Nhớ","Gourmet Bộ Nhớ","Monster Bộ Nhớ",
        "Aquatic Bộ Nhớ","Rồng Bộ Nhớ","Flora Bộ Nhớ","Mission Order Hồng","Mission Order Đỏ",
        "Mission Order Xanh Lam","Mission Order Xanh Lá","Mission Order Vàng","Leaders Crest","Lapras Passport",
        "Cell Battery","Khăn Lụa","Friend Bow","Đen Belt","Mach Ruy Băng",
        "Explosive Đai","Twist Đai","Lớn Eater Belt","Lucky Ruy Băng","Cover Đai",
        "Efficient Bandanna","Nullify Bandanna","Tatsugiri Curly","Tatsugiri Droopy","Tatsugiri Stretchy",
        "Confuse Đũa","Petrify Đũa","Slow Đũa","Slumber Đũa","Blast Đũa",
        "Hp Swap Đũa","Spirit Đũa","Long Đũa","Guiding Đũa","Surround Đũa",
        "Pounce Đũa","Two Edged Đũa","Warp Đũa","Switcher Đũa","Whirlwind Đũa",
        "Tunnel Đũa","Aqua Monica","Fiery Drum","Cỏ Cornet","Icy Flute",
        "Đá Horn","Sky Melodica","Terra Cymbal","Soothe Bell","Ball",
        "Berries Quà","Sweets Quà","Ditto Quà","Vé Bundle","Hatch Bundle",
        "Regional Tour","Banquet","Gems Bundle","Potion","Forage Bag",
        "Collection Hộp","Pretty Hộp","Deluxe Hộp","Toolbox","Nhỏ Exp Quà",
        "Large Exp Quà","Star Quà","Thường Quà","Không Phổ Biến Quà","Hiếm Quà",
        "Sử Thi Quà","Siêu Cấp Quà","Độc Nhất Quà","Huyền Thoại Quà","Tím Nectar",
        "Đỏ Nectar","Hồng Nectar","Vàng Nectar"
    };
    public static final String[] DESC_EN={
        "Stone used for evolution, weather or crafting.","Stats: AP +10.","Stats: MP +15.","Stats: SPD +10.","Stats: CRIT +10.",
        "Stats: HP +15.","Stats: SP.DEF +3.","Stats: ATK +3.","Stats: DEF +3.","Recipe: Fossil Stone + Fossil Stone.",
        "Stats: AP +20. Recipe: Fossil Stone + Twisted Spoon. Stone used for evolution, weather or crafting.","Stats: MP +30. Recipe: Fossil Stone + Mystic Water. Stone used for evolution, weather or crafting.","Stats: SPD +20. Recipe: Fossil Stone + Magnet. Stone used for evolution, weather or crafting.","Stats: ATK +6. Recipe: Fossil Stone + Charcoal. Stone used for evolution, weather or crafting.","Stats: DEF +6. Recipe: Fossil Stone + Heart Scale. Stone used for evolution, weather or crafting.",
        "Stats: CRIT +20. Recipe: Fossil Stone + Black Glasses. Stone used for evolution, weather or crafting.","Stats: HP +30. Recipe: Fossil Stone + Miracle Seed. Stone used for evolution, weather or crafting.","Stats: SP.DEF +6. Recipe: Fossil Stone + Never Melt Ice. Stone used for evolution, weather or crafting.","Stats: AP +100. Recipe: Twisted Spoon + Twisted Spoon.","Recipe: Twisted Spoon + Mystic Water.",
        "Stats: AP +10, SPD +10. Recipe: Twisted Spoon + Magnet.","Stats: AP +10, CRIT +20. Recipe: Twisted Spoon + Black Glasses.","Stats: AP +30, ATK +3. Recipe: Twisted Spoon + Charcoal.","Stats: AP +10. Recipe: Twisted Spoon + Miracle Seed.","Stats: SP.DEF +10, AP +10. Recipe: Twisted Spoon + Never Melt Ice.",
        "Stats: ATK +5, SP.DEF +5. Recipe: Never Melt Ice + Charcoal.","Stats: AP +50, DEF +12. Recipe: Twisted Spoon + Heart Scale.","Stats: MP +30. Recipe: Mystic Water + Mystic Water.","Stats: MP +15, SPD +10. Recipe: Mystic Water + Magnet.","Stats: MP +15, CRIT +25. Recipe: Mystic Water + Black Glasses.",
        "Stats: SP.DEF +10, MP +15. Recipe: Mystic Water + Never Melt Ice.","Stats: HP +15. Recipe: Mystic Water + Miracle Seed.","Stats: ATK +7, MP +15. Recipe: Mystic Water + Charcoal.","Stats: CRIT +10. Recipe: Black Glasses + Miracle Seed.","Stats: SPD +50. Recipe: Magnet + Magnet.",
        "Stats: SPD +10, CRIT +10, CRIT DMG +50. Recipe: Magnet + Black Glasses.","Stats: SHIELD +60, ATK +6. Recipe: Miracle Seed + Charcoal.","Stats: SPD +10, SP.DEF +3, LUCK +20. Recipe: Magnet + Never Melt Ice.","Stats: SPD +10, ATK +3. Recipe: Magnet + Charcoal.","Stats: SPD +10, DEF +3. Recipe: Magnet + Heart Scale. Held equipment for a Pokémon in battle.",
        "Recipe: Black Glasses + Black Glasses. Reward container that grants items when opened.","Stats: DEF +6, HP +15. Recipe: Miracle Seed + Heart Scale.","Stats: RANGE +2, CRIT +15, SP.DEF +3. Recipe: Black Glasses + Never Melt Ice.","Stats: CRIT +50, ATK +3. Recipe: Black Glasses + Charcoal.","Stats: CRIT +10, DEF +3. Recipe: Black Glasses + Heart Scale.",
        "Stats: HP +100. Recipe: Miracle Seed + Miracle Seed. Stone used for evolution, weather or crafting.","Stats: DEF +3. Recipe: Mystic Water + Heart Scale.","Recipe: Magnet + Miracle Seed.","Stats: ATK +5, DEF +3. Recipe: Charcoal + Heart Scale.","Stats: SP.DEF +40. Recipe: Never Melt Ice + Never Melt Ice.",
        "This app.zip does not include the localized description for this item.","Stats: DEF +3, SP.DEF +3. Recipe: Never Melt Ice + Heart Scale.","Stats: ATK +10. Recipe: Charcoal + Charcoal.","Recipe: Miracle Seed + Never Melt Ice.","Stats: DEF +25. Recipe: Heart Scale + Heart Scale.",
        "Berry with a support or recovery effect.","Berry with a support or recovery effect.","Berry with a support or recovery effect.","Berry with a support or recovery effect.","Berry with a support or recovery effect.",
        "Berry with a support or recovery effect.","Berry with a support or recovery effect.","Berry with a support or recovery effect.","Berry with a support or recovery effect.","Berry with a support or recovery effect.",
        "Berry with a support or recovery effect.","Berry with a support or recovery effect.","Berry with a support or recovery effect.","Berry with a support or recovery effect.","Berry with a support or recovery effect.",
        "Berry with a support or recovery effect.","Berry with a support or recovery effect.","Berry with a support or recovery effect.","Berry with a support or recovery effect.","Berry with a support or recovery effect.",
        "Berry with a support or recovery effect.","Berry with a support or recovery effect.","Berry with a support or recovery effect.","This app.zip does not include the localized description for this item.","Stats: SPD +10.",
        "Stats: ATK +5.","Stats: ATK +15, SPD -15.","Stats: AP +50.","Stats: DEF +5, SP.DEF +5.","Stats: MP +5.",
        "Stats: DEF +5, SP.DEF +5, ATK +3.","Stats: DEF +10, SP.DEF +10.","Stats: SPD +30.","Stats: SHIELD +75.","Stats: SP.DEF +10, LUCK +30.",
        "This app.zip does not include the localized description for this item.","Stats: SHIELD +50, MP +20.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.",
        "Stats: ATK +10.","This app.zip does not include the localized description for this item.","Stats: DEF +10.","Stats: SPD +15.","This app.zip does not include the localized description for this item.",
        "This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","Held equipment for a Pokémon in battle.","Stats: AP +50. Stone used for evolution, weather or crafting.",
        "This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","Stats: HP +100, ATK +10, AP +50, DEF +10, SP.DEF +10.",
        "This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","Stats: LUCK +50, CRIT +30.","Stats: DEF +20, SP.DEF +20.","This app.zip does not include the localized description for this item.",
        "This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","Stats: SHIELD +50.","Stone used for evolution, weather or crafting.","Stone used for evolution, weather or crafting.",
        "Stone used for evolution, weather or crafting.","Stone used for evolution, weather or crafting.","This app.zip does not include the localized description for this item.","Stone used for evolution, weather or crafting.","Stone used for evolution, weather or crafting.",
        "This app.zip does not include the localized description for this item.","Stone used for evolution, weather or crafting.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","Stone used for evolution, weather or crafting.",
        "Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.",
        "Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.",
        "Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.",
        "Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.",
        "Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.",
        "Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.","Synergy gem representing a Pokémon type.",
        "This app.zip does not include the localized description for this item.","Stats: SHIELD +100, SPD +30.","Stats: SHIELD +100, SP.DEF +10.","Stats: SHIELD +100, DEF +10.","Stats: SHIELD +100, ATK +10.",
        "This app.zip does not include the localized description for this item.","Technical machine that teaches a move.","Technical machine that teaches a move.","Technical machine that teaches a move.","Technical machine that teaches a move.",
        "Technical machine that teaches a move.","Technical machine that teaches a move.","Technical machine that teaches a move.","Technical machine that teaches a move.","Technical machine that teaches a move.",
        "Technical machine that teaches a move.","Technical machine that teaches a move.","Technical machine that teaches a move.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.",
        "Food or ingredient used during exploration.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","Food or ingredient used during exploration.","Food or ingredient used during exploration.",
        "This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","Food or ingredient used during exploration.","Berry with a support or recovery effect.","This app.zip does not include the localized description for this item.",
        "This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.",
        "Food or ingredient used during exploration.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.",
        "Food or ingredient used during exploration.","Food or ingredient used during exploration.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.",
        "This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","Food or ingredient used during exploration.","This app.zip does not include the localized description for this item.",
        "This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","Food or ingredient used during exploration.","This app.zip does not include the localized description for this item.",
        "This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","Food or ingredient used during exploration.",
        "Food or ingredient used during exploration.","Food or ingredient used during exploration.","Food or ingredient used during exploration.","Food or ingredient used during exploration.","Food or ingredient used during exploration.",
        "Food or ingredient used during exploration.","This app.zip does not include the localized description for this item.","Food or ingredient used during exploration.","Food or ingredient used during exploration.","Food or ingredient used during exploration.",
        "Food or ingredient used during exploration.","Food or ingredient used during exploration.","Food or ingredient used during exploration.","Food or ingredient used during exploration.","Food or ingredient used during exploration.",
        "Food or ingredient used during exploration.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.",
        "This app.zip does not include the localized description for this item.","Quest item or ticket used in town.","Quest item or ticket used in town.","Reward container that grants items when opened.","This app.zip does not include the localized description for this item.",
        "This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","Reward container that grants items when opened.",
        "This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","Quest item or ticket used in town.","Quest item or ticket used in town.","Quest item or ticket used in town.",
        "This app.zip does not include the localized description for this item.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.",
        "Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.",
        "Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.",
        "Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.",
        "Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.",
        "Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Memory disc used by type-changing mechanics.","Quest item or ticket used in town.","Quest item or ticket used in town.",
        "Quest item or ticket used in town.","Quest item or ticket used in town.","Quest item or ticket used in town.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.",
        "This app.zip does not include the localized description for this item.","Stats: SHIELD +15. Held equipment for a Pokémon in battle.","Stats: SHIELD +30. Recipe: Silk Scarf + Fossil Stone.","Stats: SHIELD +15, CRIT +30. Recipe: Silk Scarf + Black Glasses. Held equipment for a Pokémon in battle.","Stats: SHIELD +15, SPD +10. Recipe: Silk Scarf + Magnet. Held equipment for a Pokémon in battle.",
        "Stats: SHIELD +50, ATK +3. Recipe: Silk Scarf + Charcoal. Held equipment for a Pokémon in battle.","Stats: SP.DEF +20, SHIELD +50. Recipe: Silk Scarf + Never Melt Ice. Held equipment for a Pokémon in battle.","Stats: HP +50, SHIELD +15. Recipe: Silk Scarf + Miracle Seed. Held equipment for a Pokémon in battle.","Stats: SHIELD +15, AP +50, LUCK +20. Recipe: Silk Scarf + Twisted Spoon. Held equipment for a Pokémon in battle.","Stats: DEF +12, SHIELD +50. Recipe: Silk Scarf + Heart Scale. Held equipment for a Pokémon in battle.",
        "Stats: SHIELD +15, MP +15. Recipe: Silk Scarf + Mystic Water. Held equipment for a Pokémon in battle.","Stats: SHIELD +30. Recipe: Silk Scarf + Silk Scarf. Held equipment for a Pokémon in battle.","Stats: HP +50, ATK +8.","Stats: HP +50, DEF +8.","Stats: HP +50, SPD +25.",
        "Wand with a special exploration effect.","Wand with a special exploration effect.","Wand with a special exploration effect.","Wand with a special exploration effect.","Wand with a special exploration effect.",
        "Wand with a special exploration effect.","Wand with a special exploration effect.","Wand with a special exploration effect.","Wand with a special exploration effect.","Wand with a special exploration effect.",
        "Wand with a special exploration effect.","Wand with a special exploration effect.","Wand with a special exploration effect.","Wand with a special exploration effect.","Wand with a special exploration effect.",
        "Wand with a special exploration effect.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.",
        "This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.",
        "Reward container that grants items when opened.","Reward container that grants items when opened.","Reward container that grants items when opened.","Reward container that grants items when opened.","Reward container that grants items when opened.",
        "This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.","Reward container that grants items when opened.","This app.zip does not include the localized description for this item.","This app.zip does not include the localized description for this item.",
        "Reward container that grants items when opened.","Reward container that grants items when opened.","Reward container that grants items when opened.","This app.zip does not include the localized description for this item.","Reward container that grants items when opened.",
        "Reward container that grants items when opened.","Reward container that grants items when opened.","Reward container that grants items when opened.","Reward container that grants items when opened.","Reward container that grants items when opened.",
        "Reward container that grants items when opened.","Reward container that grants items when opened.","Reward container that grants items when opened.","Reward container that grants items when opened.","Nectar used by the matching form-change mechanic.",
        "Nectar used by the matching form-change mechanic.","Nectar used by the matching form-change mechanic.","Nectar used by the matching form-change mechanic."
    };
    public static final String[] DESC_VI={
        "Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.","Chỉ số: AP +10.","Chỉ số: MP +15.","Chỉ số: SPD +10.","Chỉ số: CRIT +10.",
        "Chỉ số: HP +15.","Chỉ số: SP.DEF +3.","Chỉ số: ATK +3.","Chỉ số: DEF +3.","Ghép: Đá Hóa Thạch + Đá Hóa Thạch.",
        "Chỉ số: AP +20. Ghép: Đá Hóa Thạch + Thìa Xoắn. Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.","Chỉ số: MP +30. Ghép: Đá Hóa Thạch + Nước Huyền Bí. Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.","Chỉ số: SPD +20. Ghép: Đá Hóa Thạch + Nam Châm. Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.","Chỉ số: ATK +6. Ghép: Đá Hóa Thạch + Than Củi. Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.","Chỉ số: DEF +6. Ghép: Đá Hóa Thạch + Vảy Tim. Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.",
        "Chỉ số: CRIT +20. Ghép: Đá Hóa Thạch + Kính Đen. Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.","Chỉ số: HP +30. Ghép: Đá Hóa Thạch + Hạt Kỳ Diệu. Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.","Chỉ số: SP.DEF +6. Ghép: Đá Hóa Thạch + Băng Vĩnh Cửu. Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.","Chỉ số: AP +100. Ghép: Thìa Xoắn + Thìa Xoắn.","Ghép: Thìa Xoắn + Nước Huyền Bí.",
        "Chỉ số: AP +10, SPD +10. Ghép: Thìa Xoắn + Nam Châm.","Chỉ số: AP +10, CRIT +20. Ghép: Thìa Xoắn + Kính Đen.","Chỉ số: AP +30, ATK +3. Ghép: Thìa Xoắn + Than Củi.","Chỉ số: AP +10. Ghép: Thìa Xoắn + Hạt Kỳ Diệu.","Chỉ số: SP.DEF +10, AP +10. Ghép: Thìa Xoắn + Băng Vĩnh Cửu.",
        "Chỉ số: ATK +5, SP.DEF +5. Ghép: Băng Vĩnh Cửu + Than Củi.","Chỉ số: AP +50, DEF +12. Ghép: Thìa Xoắn + Vảy Tim.","Chỉ số: MP +30. Ghép: Nước Huyền Bí + Nước Huyền Bí.","Chỉ số: MP +15, SPD +10. Ghép: Nước Huyền Bí + Nam Châm.","Chỉ số: MP +15, CRIT +25. Ghép: Nước Huyền Bí + Kính Đen.",
        "Chỉ số: SP.DEF +10, MP +15. Ghép: Nước Huyền Bí + Băng Vĩnh Cửu.","Chỉ số: HP +15. Ghép: Nước Huyền Bí + Hạt Kỳ Diệu.","Chỉ số: ATK +7, MP +15. Ghép: Nước Huyền Bí + Than Củi.","Chỉ số: CRIT +10. Ghép: Kính Đen + Hạt Kỳ Diệu.","Chỉ số: SPD +50. Ghép: Nam Châm + Nam Châm.",
        "Chỉ số: SPD +10, CRIT +10, CRIT DMG +50. Ghép: Nam Châm + Kính Đen.","Chỉ số: SHIELD +60, ATK +6. Ghép: Hạt Kỳ Diệu + Than Củi.","Chỉ số: SPD +10, SP.DEF +3, LUCK +20. Ghép: Nam Châm + Băng Vĩnh Cửu.","Chỉ số: SPD +10, ATK +3. Ghép: Nam Châm + Than Củi.","Chỉ số: SPD +10, DEF +3. Ghép: Nam Châm + Vảy Tim. Trang bị đeo cho Pokémon trong trận.",
        "Ghép: Kính Đen + Kính Đen. Gói phần thưởng; mở để nhận vật phẩm.","Chỉ số: DEF +6, HP +15. Ghép: Hạt Kỳ Diệu + Vảy Tim.","Chỉ số: RANGE +2, CRIT +15, SP.DEF +3. Ghép: Kính Đen + Băng Vĩnh Cửu.","Chỉ số: CRIT +50, ATK +3. Ghép: Kính Đen + Than Củi.","Chỉ số: CRIT +10, DEF +3. Ghép: Kính Đen + Vảy Tim.",
        "Chỉ số: HP +100. Ghép: Hạt Kỳ Diệu + Hạt Kỳ Diệu. Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.","Chỉ số: DEF +3. Ghép: Nước Huyền Bí + Vảy Tim.","Ghép: Nam Châm + Hạt Kỳ Diệu.","Chỉ số: ATK +5, DEF +3. Ghép: Than Củi + Vảy Tim.","Chỉ số: SP.DEF +40. Ghép: Băng Vĩnh Cửu + Băng Vĩnh Cửu.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Chỉ số: DEF +3, SP.DEF +3. Ghép: Băng Vĩnh Cửu + Vảy Tim.","Chỉ số: ATK +10. Ghép: Than Củi + Than Củi.","Ghép: Hạt Kỳ Diệu + Băng Vĩnh Cửu.","Chỉ số: DEF +25. Ghép: Vảy Tim + Vảy Tim.",
        "Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.",
        "Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.",
        "Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.",
        "Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.",
        "Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Chỉ số: SPD +10.",
        "Chỉ số: ATK +5.","Chỉ số: ATK +15, SPD -15.","Chỉ số: AP +50.","Chỉ số: DEF +5, SP.DEF +5.","Chỉ số: MP +5.",
        "Chỉ số: DEF +5, SP.DEF +5, ATK +3.","Chỉ số: DEF +10, SP.DEF +10.","Chỉ số: SPD +30.","Chỉ số: SHIELD +75.","Chỉ số: SP.DEF +10, LUCK +30.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Chỉ số: SHIELD +50, MP +20.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Chỉ số: ATK +10.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Chỉ số: DEF +10.","Chỉ số: SPD +15.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Trang bị đeo cho Pokémon trong trận.","Chỉ số: AP +50. Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Chỉ số: HP +100, ATK +10, AP +50, DEF +10, SP.DEF +10.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Chỉ số: LUCK +50, CRIT +30.","Chỉ số: DEF +20, SP.DEF +20.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Chỉ số: SHIELD +50.","Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.","Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.",
        "Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.","Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.","Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Đá dùng cho tiến hóa, thời tiết hoặc chế tạo.",
        "Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.",
        "Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.",
        "Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.",
        "Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.",
        "Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.",
        "Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.","Ngọc cộng hưởng, đại diện cho một hệ Pokémon.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Chỉ số: SHIELD +100, SPD +30.","Chỉ số: SHIELD +100, SP.DEF +10.","Chỉ số: SHIELD +100, DEF +10.","Chỉ số: SHIELD +100, ATK +10.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Máy dạy kỹ năng.","Máy dạy kỹ năng.","Máy dạy kỹ năng.","Máy dạy kỹ năng.",
        "Máy dạy kỹ năng.","Máy dạy kỹ năng.","Máy dạy kỹ năng.","Máy dạy kỹ năng.","Máy dạy kỹ năng.",
        "Máy dạy kỹ năng.","Máy dạy kỹ năng.","Máy dạy kỹ năng.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Quả mọng có hiệu ứng hỗ trợ hoặc hồi phục.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.",
        "Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.",
        "Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.",
        "Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.",
        "Nguyên liệu hoặc món ăn dùng trong chế độ thám hiểm.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Vật phẩm nhiệm vụ hoặc vé sử dụng tại thị trấn.","Vật phẩm nhiệm vụ hoặc vé sử dụng tại thị trấn.","Gói phần thưởng; mở để nhận vật phẩm.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói phần thưởng; mở để nhận vật phẩm.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Vật phẩm nhiệm vụ hoặc vé sử dụng tại thị trấn.","Vật phẩm nhiệm vụ hoặc vé sử dụng tại thị trấn.","Vật phẩm nhiệm vụ hoặc vé sử dụng tại thị trấn.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.",
        "Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.",
        "Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.",
        "Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.",
        "Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.",
        "Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Đĩa bộ nhớ dùng cho cơ chế đổi hệ.","Vật phẩm nhiệm vụ hoặc vé sử dụng tại thị trấn.","Vật phẩm nhiệm vụ hoặc vé sử dụng tại thị trấn.",
        "Vật phẩm nhiệm vụ hoặc vé sử dụng tại thị trấn.","Vật phẩm nhiệm vụ hoặc vé sử dụng tại thị trấn.","Vật phẩm nhiệm vụ hoặc vé sử dụng tại thị trấn.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Chỉ số: SHIELD +15. Trang bị đeo cho Pokémon trong trận.","Chỉ số: SHIELD +30. Ghép: Khăn Lụa + Đá Hóa Thạch.","Chỉ số: SHIELD +15, CRIT +30. Ghép: Khăn Lụa + Kính Đen. Trang bị đeo cho Pokémon trong trận.","Chỉ số: SHIELD +15, SPD +10. Ghép: Khăn Lụa + Nam Châm. Trang bị đeo cho Pokémon trong trận.",
        "Chỉ số: SHIELD +50, ATK +3. Ghép: Khăn Lụa + Than Củi. Trang bị đeo cho Pokémon trong trận.","Chỉ số: SP.DEF +20, SHIELD +50. Ghép: Khăn Lụa + Băng Vĩnh Cửu. Trang bị đeo cho Pokémon trong trận.","Chỉ số: HP +50, SHIELD +15. Ghép: Khăn Lụa + Hạt Kỳ Diệu. Trang bị đeo cho Pokémon trong trận.","Chỉ số: SHIELD +15, AP +50, LUCK +20. Ghép: Khăn Lụa + Thìa Xoắn. Trang bị đeo cho Pokémon trong trận.","Chỉ số: DEF +12, SHIELD +50. Ghép: Khăn Lụa + Vảy Tim. Trang bị đeo cho Pokémon trong trận.",
        "Chỉ số: SHIELD +15, MP +15. Ghép: Khăn Lụa + Nước Huyền Bí. Trang bị đeo cho Pokémon trong trận.","Chỉ số: SHIELD +30. Ghép: Khăn Lụa + Khăn Lụa. Trang bị đeo cho Pokémon trong trận.","Chỉ số: HP +50, ATK +8.","Chỉ số: HP +50, DEF +8.","Chỉ số: HP +50, SPD +25.",
        "Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.","Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.","Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.","Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.","Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.",
        "Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.","Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.","Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.","Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.","Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.",
        "Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.","Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.","Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.","Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.","Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.",
        "Đũa phép tạo hiệu ứng đặc biệt trong thám hiểm.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Gói phần thưởng; mở để nhận vật phẩm.","Gói phần thưởng; mở để nhận vật phẩm.","Gói phần thưởng; mở để nhận vật phẩm.","Gói phần thưởng; mở để nhận vật phẩm.","Gói phần thưởng; mở để nhận vật phẩm.",
        "Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói phần thưởng; mở để nhận vật phẩm.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.",
        "Gói phần thưởng; mở để nhận vật phẩm.","Gói phần thưởng; mở để nhận vật phẩm.","Gói phần thưởng; mở để nhận vật phẩm.","Gói app.zip không kèm bản mô tả ngôn ngữ cho vật phẩm này.","Gói phần thưởng; mở để nhận vật phẩm.",
        "Gói phần thưởng; mở để nhận vật phẩm.","Gói phần thưởng; mở để nhận vật phẩm.","Gói phần thưởng; mở để nhận vật phẩm.","Gói phần thưởng; mở để nhận vật phẩm.","Gói phần thưởng; mở để nhận vật phẩm.",
        "Gói phần thưởng; mở để nhận vật phẩm.","Gói phần thưởng; mở để nhận vật phẩm.","Gói phần thưởng; mở để nhận vật phẩm.","Gói phần thưởng; mở để nhận vật phẩm.","Mật hoa dùng để đổi dạng Pokémon tương ứng.",
        "Mật hoa dùng để đổi dạng Pokémon tương ứng.","Mật hoa dùng để đổi dạng Pokémon tương ứng.","Mật hoa dùng để đổi dạng Pokémon tương ứng."
    };
    public static final int[] HP={0,0,0,0,0,15,0,0,0,0,0,0,0,0,0,0,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,0,0,0,0,0,0,0,0,0,15,0,0,0,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50,0,0,0,0,50,50,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    public static final int[] ATK={0,0,0,0,0,0,0,3,0,0,0,0,0,6,0,0,0,0,0,0,0,0,3,0,0,5,0,0,0,0,0,0,7,0,0,0,6,0,3,0,0,0,0,3,0,0,0,0,5,0,0,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,15,0,0,0,3,0,0,0,0,0,0,0,0,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    public static final int[] DEF={0,0,0,0,0,0,0,0,3,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,12,0,0,0,0,0,0,0,0,0,0,0,0,3,0,6,0,0,3,0,3,0,3,0,0,3,0,0,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,5,10,0,0,0,0,0,0,0,0,0,0,10,0,0,0,0,0,0,0,0,0,0,0,10,0,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,0,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    public static final int[] SPE_DEF={0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,10,5,0,0,0,0,10,0,0,0,0,0,0,3,0,0,0,0,3,0,0,0,0,0,0,40,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,5,10,0,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,0,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    public static final int[] SPEED={0,0,0,10,0,0,0,0,0,0,0,0,20,0,0,0,0,0,0,0,10,0,0,0,0,0,0,0,10,0,0,0,0,0,50,10,0,10,10,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,0,-15,0,0,0,0,0,30,0,0,0,0,0,0,0,0,0,0,15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,0,0,0,0,0,0,0,0,0,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    public static final int[] MP={0,0,15,0,0,0,0,0,0,0,0,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,30,15,15,15,0,15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    public static final int[] AP={0,10,0,0,0,0,0,0,0,0,20,0,0,0,0,0,0,0,100,0,10,10,30,10,10,0,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50,0,0,0,0,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    public static final int[] CRIT={0,0,0,0,10,0,0,0,0,0,0,0,0,0,0,20,0,0,0,0,0,20,0,0,0,0,0,0,0,25,0,0,0,10,0,10,0,0,0,0,0,0,15,50,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    public static final int[] SHIELD={0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,60,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,75,0,0,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,30,15,15,50,50,15,15,50,15,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    public static final int[] RECIPE_A={-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,6,1,2,2,2,2,2,2,4,3,3,5,3,3,3,4,5,4,4,4,5,2,3,7,6,-1,6,7,5,8,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,291,291,291,291,291,291,291,291,291,291,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1};
    public static final int[] RECIPE_B={-1,-1,-1,-1,-1,-1,-1,-1,-1,0,1,2,3,7,8,4,5,6,1,2,3,4,7,5,6,7,8,2,3,4,6,5,7,5,3,4,7,6,7,8,4,8,6,7,8,5,8,5,8,6,-1,8,7,6,8,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,4,3,7,6,5,1,8,2,291,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1};
    public static int count(){return ID.length;}
    public static String name(int i){return Save.language==Lang.EN?EN[i]:VI[i];}
    public static String desc(int i){String base=Save.language==Lang.EN?DESC_EN[i]:DESC_VI[i];String passive=ItemEffects.passiveDesc(i);return passive.length()==0?base:base+" "+Lang.t("Nội tại: ","Passive: ")+passive;}
    public static int indexOf(String id){for(int i=0;i<ID.length;i++)if(ID[i].equals(id))return i;return -1;}
    public static boolean isComponent(int i){String s=ID[i];return s.equals("MIRACLE_SEED")||s.equals("MYSTIC_WATER")||s.equals("HEART_SCALE")||s.equals("NEVER_MELT_ICE")||s.equals("CHARCOAL")||s.equals("MAGNET")||s.equals("BLACK_GLASSES")||s.equals("TWISTED_SPOON")||s.equals("FOSSIL_STONE")||s.equals("SILK_SCARF");}
    public static int crafted(int a,int b){for(int i=0;i<ID.length;i++)if((RECIPE_A[i]==a&&RECIPE_B[i]==b)||(RECIPE_A[i]==b&&RECIPE_B[i]==a))return i;return -1;}
    public static int recipeCount(){int n=0;for(int i=0;i<ID.length;i++)if(RECIPE_A[i]>=0&&RECIPE_B[i]>=0)n++;return n;}
    public static int recipeOutputAt(int rank){for(int i=0,n=0;i<ID.length;i++)if(RECIPE_A[i]>=0&&RECIPE_B[i]>=0){if(n==rank)return i;n++;}return -1;}
    public static int outputCount(int ingredient){int n=0;for(int i=0;i<ID.length;i++)if(RECIPE_A[i]==ingredient||RECIPE_B[i]==ingredient)n++;return n;}
    public static int outputAt(int ingredient,int rank){for(int i=0,n=0;i<ID.length;i++)if(RECIPE_A[i]==ingredient||RECIPE_B[i]==ingredient){if(n==rank)return i;n++;}return -1;}
    public static String kind(int i){
        String s=ID[i];
        if(s.indexOf("_BERRY")>=0)return Lang.t("QUẢ MỌNG","BERRY");
        if(s.indexOf("_MEMORY")>=0||s.equals("MEMORY_DISCS"))return Lang.t("ĐĨA BỘ NHỚ","MEMORY");
        if(s.indexOf("_GEM")>=0)return Lang.t("NGỌC HỆ","SYNERGY GEM");
        if(s.indexOf("TM_")==0)return Lang.t("MÁY KỸ NĂNG","TECHNICAL MACHINE");
        if(s.indexOf("_WAND")>=0)return Lang.t("ĐŨA PHÉP","WAND");
        if(s.indexOf("_STONE")>=0||s.indexOf("_ROCK")>=0)return Lang.t("ĐÁ / TIẾN HÓA","STONE / EVOLUTION");
        if(s.indexOf("_GIFT")>=0||s.indexOf("_BOX")>=0||s.indexOf("_BUNDLE")>=0)return Lang.t("GÓI PHẦN THƯỞNG","REWARD");
        if(s.indexOf("_TICKET")>=0||s.indexOf("MISSION_ORDER")>=0)return Lang.t("NHIỆM VỤ / VÉ","QUEST / TICKET");
        return Lang.t("VẬT PHẨM","ITEM");
    }
}
