package pac;
/** 143 source DungeonPMDO identifiers, kept as lightweight Collection metadata. */
public final class MapData{
 private MapData(){}
 public static final String[] ID={"AmpPlains","AppleWoods","BarrenValley","BeachCave","BrineCave","BuriedRelic1","BuriedRelic2","BuriedRelic3","ConcealedRuins","CraggyCoast","CrystalCave1","CrystalCave2","CrystalCrossing","DarkCrater","DarkHill1","DarkHill2","DarkIceMountain","DarkIceMountainPeak","DarknightRelic","DarkWasteland","DeepBoulderQuarry","DeepDarkCrater","DeepDuskForest1","DeepDuskForest2","DeepLimestoneCavern","DeepSealedRuin","DesertRegion","DrenchedBluff","DuskForest1","DuskForest2","ElectricMaze","FarAmpPlains","FinalMaze2","FoggyForest","ForestPath","FrostyForest","FutureTemporalSpire","FutureTemporalTower","GoldenChamber","GrassMaze","GreatCanyon","HiddenHighland","HiddenLand","HowlingForest1","HowlingForest2","IceAegisCave","IceMaze","IcicleForest","JoyousTower","LapisCave","LightningField","LimestoneCavern","LowerBrineCave","LushPrairie","MagmaCavern2","MagmaCavern3","MeteorCave","MiracleSea","MoonlitCourtyard","MtBlaze","MtBristle","MtFaraway2","MtFaraway4","MtFreeze","MtHorn","MtSteel1","MtSteel2","MtThunder","MtThunderPeak","MtTravail","MurkyCave","MurkyForest","MysteryJungle1","MysteryJungle2","MystifyingForest","NorthernDesert1","NorthernDesert2","NorthernRange1","NorthernRange2","NorthwindField","PitfallValley1","PoisonMaze","PurityForest2","PurityForest4","PurityForest6","PurityForest7","QuicksandCave","QuicksandPit","QuicksandUnused","RescueTeamMaze","RockAegisCave","RockMaze","RockPathRB","RockPathTDS","SealedRuin","SidePath","SilentChasm","SkyPeak4thPass","SkyPeak7thPass","SkyPeakSummitPass","SkyTower","SnowPath","SolarCave1","SouthernCavern1","SouthernCavern2","SouthernJungle","SpacialCliffs","SpacialRift1","SpacialRift2","SteamCave","SteelAegisCave","StormySea1","StormySea2","SurroundedSea","TemporalSpire","TemporalTower","TemporalUnused","TestDungeon","TheNightmare","ThunderwaveCave","TinyMeadow","TinyWoods","TreeshroudForest1","TreeshroudForest2","UnusedBrineCave","UnusedSteamCave","UnusedWaterfallPond","UproarForest","VastIceMountain","VastIceMountainPeak","WaterfallCave","WaterfallPond","WaterMaze","WesternCave1","WesternCave2","WishCave1","WishCave2","WorldAbyss2","WyvernHill","ZeroIsleEast3","ZeroIsleEast4","ZeroIsleSouth1","ZeroIsleSouth2"};
 public static final int COUNT=ID.length;
 public static String name(int i){String s=ID[i],o="";for(int p=0;p<s.length();p++){char c=s.charAt(p);if(p>0&&((c>='A'&&c<='Z')||(c>='0'&&c<='9'&&s.charAt(p-1)<'0')))o+=" ";o+=c;}return o;}
 public static String theme(int i){String s=ID[i].toUpperCase();if(has(s,"ICE")||has(s,"FROST")||has(s,"SNOW")||has(s,"FREEZE"))return Lang.t("Băng tuyết","Ice/Snow");if(has(s,"SEA")||has(s,"WATER")||has(s,"BRINE")||has(s,"BEACH"))return Lang.t("Biển/Nước","Sea/Water");if(has(s,"FOREST")||has(s,"WOODS")||has(s,"JUNGLE"))return Lang.t("Rừng","Forest");if(has(s,"MAGMA")||has(s,"BLAZE")||has(s,"CRATER"))return Lang.t("Núi lửa","Volcanic");if(has(s,"DESERT")||has(s,"QUICKSAND"))return Lang.t("Sa mạc","Desert");if(has(s,"CAVE")||has(s,"CAVERN")||has(s,"RUIN")||has(s,"RELIC"))return Lang.t("Hang động/Di tích","Cave/Ruins");if(has(s,"SKY")||has(s,"SPIRE")||has(s,"TOWER"))return Lang.t("Trời cao","Sky/Tower");if(has(s,"THUNDER")||has(s,"AMP")||has(s,"ELECTRIC")||has(s,"LIGHTNING"))return Lang.t("Điện","Electric");return Lang.t("Đồng hoang/Đặc biệt","Field/Special");}
 public static String desc(int i){return Lang.t("Map gốc: ","Original map: ")+ID[i]+". "+Lang.t("Chủ đề ","Theme ")+theme(i)+Lang.t(". Được nhập vào thư viện để dùng dần cho Explore offline.",". Catalogued for progressive use by offline Explore.");}
 private static boolean has(String s,String q){return s.indexOf(q)>=0;}
}
