package pac;

import java.io.DataInputStream;
import java.io.InputStream;
import javax.microedition.lcdui.Graphics;
import javax.microedition.lcdui.Image;

/** Small LRU loader for the eight source-backed Mega animation atlases. */
public final class MegaAtlas{
    private static final int TRANS_NONE=0,TRANS_ROT270=6,MAX=4;
    private static final MegaAtlas[] CACHE=new MegaAtlas[Data.N];private static final boolean[] FAILED=new boolean[Data.N];private static final int[] AGE=new int[Data.N];private static int clock;
    private Image sheet;private short[][][] frames=new short[6][8][],shinyFrames=new short[6][8][];private byte[][][] rotated=new byte[6][8][],shinyRotated=new byte[6][8][];
    private Image[] outlineFrames;private int outlineDirection=-1,outlineCount=-1,outlineColor=-1;private boolean outlineShiny;
    private MegaAtlas(int sp)throws Exception{int dex=Data.nationalDex(sp);sheet=Image.createImage("/megaraw/"+dex+".png");load("/megaraw/"+dex+".dat",frames,rotated,true);load("/megaraw/"+dex+"-shiny.dat",shinyFrames,shinyRotated,false);}
    private void load(String path,short[][][] target,byte[][][] turns,boolean required)throws Exception{InputStream input=getClass().getResourceAsStream(path);if(input==null){if(required)throw new Exception("missing Mega atlas");return;}DataInputStream in=new DataInputStream(input);if(in.readInt()!=0x50414352)throw new Exception("bad Mega atlas");int actions=in.readUnsignedByte();for(int a=0;a<actions;a++)for(int d=0;d<8;d++){int count=in.readUnsignedShort();short[] v=new short[count*8];byte[] r=new byte[count];for(int i=0;i<count;i++){int p=i*8;for(int n=0;n<8;n++)v[p+n]=(short)in.readUnsignedShort();r[i]=in.readByte();}target[a][d]=v;turns[a][d]=r;}in.close();}
    private static MegaAtlas get(int sp){if(sp<0||sp>=CACHE.length||!MegaData.available(sp))return null;if(CACHE[sp]!=null){AGE[sp]=++clock;return CACHE[sp];}if(FAILED[sp])return null;int count=0,old=-1,age=Integer.MAX_VALUE;for(int i=0;i<CACHE.length;i++)if(CACHE[i]!=null){count++;if(AGE[i]<age){age=AGE[i];old=i;}}if(count>=MAX&&old>=0){CACHE[old]=null;AGE[old]=0;}try{CACHE[sp]=new MegaAtlas(sp);AGE[sp]=++clock;}catch(Exception e){FAILED[sp]=true;}return CACHE[sp];}
    private static short[] frames(MegaAtlas a,int action,int direction,boolean shiny){short[] c=shiny?a.shinyFrames[action][direction]:null;return c!=null&&c.length>0?c:a.frames[action][direction];}
    private static byte[] turns(MegaAtlas a,int action,int direction,boolean shiny){short[] c=shiny?a.shinyFrames[action][direction]:null;return c!=null&&c.length>0?a.shinyRotated[action][direction]:a.rotated[action][direction];}
    public static boolean draw(Graphics g,int sp,int x,int y,int w,int h,int action,int direction,int clock,boolean shiny){MegaAtlas a=get(sp);if(a==null)return false;if(action<0||action>=6)action=0;direction&=7;short[] c=frames(a,action,direction,shiny);if(c==null||c.length==0)return false;byte[] r=turns(a,action,direction,shiny);int frame=(clock/2)%(c.length/8),p=frame*8,sx=c[p]&65535,sy=c[p+1]&65535,sw=c[p+2]&65535,sh=c[p+3]&65535,ox=c[p+4]&65535,oy=c[p+5]&65535,sourceW=c[p+6]&65535,sourceH=c[p+7]&65535;g.drawRegion(a.sheet,sx,sy,sw,sh,r[frame]!=0?TRANS_ROT270:TRANS_NONE,x+(w-sourceW)/2+ox,y+h-sourceH+oy,Graphics.TOP|Graphics.LEFT);return true;}
    public static boolean bounds(int sp,int x,int y,int w,int h,int action,int direction,int clock,int[] out,boolean shiny){MegaAtlas a=get(sp);if(a==null)return false;if(action<0||action>=6)action=0;direction&=7;short[] c=frames(a,action,direction,shiny);if(c==null||c.length==0)return false;byte[] r=turns(a,action,direction,shiny);int frame=(clock/2)%(c.length/8),p=frame*8,sw=c[p+2]&65535,sh=c[p+3]&65535,ox=c[p+4]&65535,oy=c[p+5]&65535,sourceW=c[p+6]&65535,sourceH=c[p+7]&65535;boolean turn=r[frame]!=0;out[0]=x+(w-sourceW)/2+ox;out[1]=y+h-sourceH+oy;out[2]=turn?sh:sw;out[3]=turn?sw:sh;return true;}
    public static boolean drawFormation(Graphics g,int sp,int x,int y,int w,int h,int screenW,int direction,int clock,boolean shiny){MegaAtlas a=get(sp);if(a==null)return false;direction&=7;short[] c=frames(a,0,direction,shiny);if(c==null||c.length==0)return false;byte[] r=turns(a,0,direction,shiny);int frame=(clock/2)%(c.length/8),p=frame*8,sx=c[p]&65535,sy=c[p+1]&65535,sw=c[p+2]&65535,sh=c[p+3]&65535;boolean turn=r[frame]!=0;int vw=turn?sh:sw,vh=turn?sw:sh,dx=x+(w-vw)/2;if(dx<0)dx=0;if(dx+vw>screenW)dx=screenW-vw;g.drawRegion(a.sheet,sx,sy,sw,sh,turn?TRANS_ROT270:TRANS_NONE,dx,y+h-vh-2,Graphics.TOP|Graphics.LEFT);return true;}
    public static boolean drawFormationOutline(Graphics g,int sp,int x,int y,int w,int h,int screenW,int direction,int clock,int color,boolean shiny){MegaAtlas a=get(sp);if(a==null)return false;direction&=7;short[] c=frames(a,0,direction,shiny);if(c==null||c.length==0)return false;byte[] r=turns(a,0,direction,shiny);int count=c.length/8,frame=(clock/2)%count,p=frame*8,sx=c[p]&65535,sy=c[p+1]&65535,sw=c[p+2]&65535,sh=c[p+3]&65535;boolean turn=r[frame]!=0;int vw=turn?sh:sw,vh=turn?sw:sh,dx=x+(w-vw)/2;if(dx<0)dx=0;if(dx+vw>screenW)dx=screenW-vw;int dy=y+h-vh-2;if(a.outlineFrames==null||a.outlineDirection!=direction||a.outlineCount!=count||a.outlineColor!=color||a.outlineShiny!=shiny){a.outlineFrames=new Image[count];a.outlineDirection=direction;a.outlineCount=count;a.outlineColor=color;a.outlineShiny=shiny;}if(a.outlineFrames[frame]==null)try{Image part=Image.createImage(a.sheet,sx,sy,sw,sh,turn?TRANS_ROT270:TRANS_NONE);int ow=vw+4,oh=vh+4,argb=0xFF000000|(color&0xFFFFFF);int[] src=new int[vw*vh],out=new int[ow*oh];part.getRGB(src,0,vw,0,0,vw,vh);for(int yy=0;yy<vh;yy++)for(int xx=0;xx<vw;xx++)if((src[yy*vw+xx]>>>24)!=0){int cx=xx+2,cy=yy+2;for(int yd=-1;yd<=1;yd++)for(int xd=-1;xd<=1;xd++)out[(cy+yd)*ow+cx+xd]=argb;}for(int yy=0;yy<vh;yy++)for(int xx=0;xx<vw;xx++)if((src[yy*vw+xx]>>>24)!=0)out[(yy+2)*ow+xx+2]=0;a.outlineFrames[frame]=Image.createRGBImage(out,ow,oh,true);}catch(Exception e){return false;}g.drawImage(a.outlineFrames[frame],dx-2,dy-2,Graphics.TOP|Graphics.LEFT);return true;}
}
