package pac;
/** Lightweight source-backed passive hooks shared by every generation. */
public final class PokemonPassive {
 private PokemonPassive(){}private static boolean named(Unit u,String n){return Data.name[u.sp].equals(n);}
 public static void onStart(Unit u){if(named(u,"Wobbuffet")||named(u,"Sudowoodo"))u.passiveTree=true;if(named(u,"Mimikyu")){int sh=Math.max(1,u.maxHp/4);u.shield+=sh;u.shieldDone+=sh;}if(named(u,"Toxapex"))u.regen+=2;if(named(u,"Zacian"))u.atk+=10;if(named(u,"Zamazenta")){u.def+=5;u.speDef+=5;}if(named(u,"Regigigas")){u.atk=Math.max(1,u.atk*3/4);u.speed=Math.max(1,u.speed*3/4);u.passiveTimer=50;}}
 public static boolean blocksMove(Unit u){return u.passiveTree;}
 public static boolean immune(Unit u,int status){return named(u,"Vigoroth")&&status==CombatStatus.SLEEP;}
 public static void onTick(Battle b,Unit u){int wanted=0;if(named(u,"Heracross")&&(u.status.burn>0||u.status.poison>0))wanted=5;if(named(u,"Zangoose")&&u.status.poison>0)wanted=10;if(wanted!=u.passiveAttackBonus){u.atk+=wanted-u.passiveAttackBonus;u.passiveAttackBonus=wanted;}if(named(u,"Sudowoodo")&&u.passiveTree&&b.tick%10==0)u.atk+=2;if(named(u,"Regigigas")&&u.passiveTimer>0&&--u.passiveTimer==0){u.atk=Math.max(1,u.atk*4/3);u.speed=Math.max(1,u.speed*4/3);}}
 public static void onDamaged(Battle b,Unit u){if((named(u,"Psyduck")||named(u,"Golduck"))&&b.itemChance(10))u.status.apply(CombatStatus.CONFUSION,30);if(named(u,"Mudsdale"))u.def++;}
 public static void onKill(Battle b,Unit killer,Unit victim){if(killer==null||!killer.alive)return;String n=Data.name[killer.sp];if(n.equals("Calyrex")||n.equals("Guzzlord")||n.equals("Nihilego")||n.equals("Buzzwole")||n.equals("Pheromosa")||n.equals("Xurkitree")||n.equals("Celesteela")||n.equals("Kartana")||n.equals("Blacephalon")){killer.atk+=5;killer.skillBonus+=10;}}
 public static String description(int sp){String n=Data.name[sp];if(n.equals("Heracross"))return Lang.t("Nội tại Guts: +5 Công khi Bỏng hoặc Nhiễm độc.","Guts: +5 Attack while Burned or Poisoned.");if(n.equals("Zangoose"))return Lang.t("Nội tại Toxic Boost: +10 Công khi Nhiễm độc.","Toxic Boost: +10 Attack while Poisoned.");if(n.equals("Vigoroth"))return Lang.t("Nội tại Vigoroth: miễn nhiễm Ngủ.","Vigoroth: immune to Sleep.");if(n.equals("Psyduck")||n.equals("Golduck"))return Lang.t("Nội tại Psyduck: 10% tự Hoang mang khi trúng đòn.","Psyduck: 10% chance to self-Confuse when hit.");if(n.equals("Sudowoodo"))return Lang.t("Dạng Cây: đứng yên và nhận +2 Công mỗi giây.","Tree form: immobile and gains +2 Attack each second.");if(n.equals("Wobbuffet"))return Lang.t("Dạng Cây: không tự di chuyển khỏi vị trí.","Tree form: does not move from its position.");if(n.equals("Mimikyu"))return Lang.t("Hóa trang: bắt đầu với Khiên bằng 25% HP.","Disguise: starts with a shield equal to 25% HP.");if(n.equals("Toxapex"))return Lang.t("Tái sinh: hồi thêm 2% HP mỗi giây.","Regenerator: restores an extra 2% HP each second.");if(n.equals("Mudsdale"))return Lang.t("Bền bỉ: +1 Thủ mỗi lần chịu đòn.","Stamina: gains 1 Defense whenever hit.");if(n.equals("Zacian"))return Lang.t("Kiếm bất khuất: +10 Công đầu trận.","Intrepid Sword: +10 Attack at battle start.");if(n.equals("Zamazenta"))return Lang.t("Khiên bất khuất: +5 Thủ và Kháng đầu trận.","Dauntless Shield: +5 Defense and Sp. Defense at battle start.");if(n.equals("Regigigas"))return Lang.t("Khởi động chậm: giảm Công/Tốc trong 5 giây đầu.","Slow Start: reduced Attack/Speed for the first 5 seconds.");if(n.equals("Calyrex")||n.equals("Guzzlord")||n.equals("Nihilego")||n.equals("Buzzwole")||n.equals("Pheromosa")||n.equals("Xurkitree")||n.equals("Celesteela")||n.equals("Kartana")||n.equals("Blacephalon"))return Lang.t("Hạ gục: +5 Công và +10 uy lực kỹ năng.","On knockout: +5 Attack and +10 ability power.");return "";}
}
