package pac;
// Form cache follows the stable expanded form ID range.
import java.io.DataInputStream;import java.io.InputStream;import javax.microedition.lcdui.Graphics;import javax.microedition.lcdui.Image;
/** LRU renderer for Primal, Origin, Ancient Paradox and Zygarde forms. */
public final class SpecialFormAtlas{
    private static final int TRANS_NONE=0,TRANS_ROT270=6,MAX=7,FORM_COUNT=SpecialFormData.MAX_FORM+1;private static final SpecialFormAtlas[] CACHE=new SpecialFormAtlas[FORM_COUNT];private static final boolean[] FAILED=new boolean[FORM_COUNT];private static final int[] AGE=new int[FORM_COUNT];private static final int[] CLIP=new int[4];private static final Image[] AVATAR=new Image[FORM_COUNT*2],AVATAR_MINI=new Image[FORM_COUNT*2];private static int clock;
    private Image sheet;private short[][][] frames=new short[6][8][],shinyFrames=new short[6][8][];private byte[][][] rotated=new byte[6][8][],shinyRotated=new byte[6][8][];private Image[] outline;private int outDir=-1,outCount=-1,outColor=-1;private boolean outShiny;
    private SpecialFormAtlas(int form)throws Exception{String key=SpecialFormData.key(form);sheet=Image.createImage("/formraw/"+key+".png");load("/formraw/"+key+".dat",frames,rotated,true);load("/formraw/"+key+"-shiny.dat",shinyFrames,shinyRotated,false);}
    private void load(String path,short[][][] target,byte[][][] turns,boolean required)throws Exception{InputStream input=getClass().getResourceAsStream(path);if(input==null){if(required)throw new Exception("missing form");return;}DataInputStream in=new DataInputStream(input);if(in.readInt()!=0x50414352)throw new Exception("bad form");int actions=in.readUnsignedByte();for(int a=0;a<actions;a++)for(int d=0;d<8;d++){int n=in.readUnsignedShort();short[] v=new short[n*8];byte[] r=new byte[n];for(int i=0;i<n;i++){int p=i*8;for(int q=0;q<8;q++)v[p+q]=(short)in.readUnsignedShort();r[i]=in.readByte();}target[a][d]=v;turns[a][d]=r;}in.close();}
    private static SpecialFormAtlas get(int f){if(f<=0||f>=CACHE.length)return null;if(CACHE[f]!=null){AGE[f]=++clock;return CACHE[f];}if(FAILED[f])return null;int n=0,old=-1,age=Integer.MAX_VALUE;for(int i=1;i<CACHE.length;i++)if(CACHE[i]!=null){n++;if(AGE[i]<age){age=AGE[i];old=i;}}if(n>=MAX&&old>0){CACHE[old]=null;AGE[old]=0;}try{CACHE[f]=new SpecialFormAtlas(f);AGE[f]=++clock;}catch(Exception e){FAILED[f]=true;}return CACHE[f];}
    private static int[] clip(SpecialFormAtlas a,int action,int direction,int tick,boolean shiny){if(action<0||action>=6)action=0;direction&=7;short[][][] fs=shiny&&a.shinyFrames[action][direction]!=null?a.shinyFrames:a.frames;short[] c=fs[action][direction];if(c==null||c.length==0)return null;int fr=(tick/2)%(c.length/8);CLIP[0]=action;CLIP[1]=direction;CLIP[2]=fr;CLIP[3]=fr*8;return CLIP;}
    private static int[] clip(SpecialFormAtlas a,int action,int direction,int tick){return clip(a,action,direction,tick,false);}
    public static boolean draw(Graphics g,int form,int x,int y,int w,int h,int action,int direction,int tick,boolean shiny){SpecialFormAtlas a=get(form);if(a==null)return false;int[] z=clip(a,action,direction,tick,shiny);if(z==null)return false;boolean useShiny=shiny&&a.shinyFrames[z[0]][z[1]]!=null;short[][][] fs=useShiny?a.shinyFrames:a.frames;byte[][][] rs=useShiny?a.shinyRotated:a.rotated;short[] c=fs[z[0]][z[1]];int p=z[3],sx=c[p]&65535,sy=c[p+1]&65535,sw=c[p+2]&65535,sh=c[p+3]&65535,ox=c[p+4]&65535,oy=c[p+5]&65535,sow=c[p+6]&65535,soh=c[p+7]&65535;g.drawRegion(a.sheet,sx,sy,sw,sh,rs[z[0]][z[1]][z[2]]!=0?TRANS_ROT270:TRANS_NONE,x+(w-sow)/2+ox,y+h-soh+oy,Graphics.TOP|Graphics.LEFT);return true;}
    public static boolean drawFormation(Graphics g,int form,int x,int y,int w,int h,int screenW,int direction,int tick,boolean shiny){SpecialFormAtlas a=get(form);if(a==null)return false;int[] z=clip(a,0,direction,tick,shiny);if(z==null)return false;boolean useShiny=shiny&&a.shinyFrames[0][z[1]]!=null;short[][][] fs=useShiny?a.shinyFrames:a.frames;byte[][][] rs=useShiny?a.shinyRotated:a.rotated;short[] c=fs[0][z[1]];int p=z[3],sx=c[p]&65535,sy=c[p+1]&65535,sw=c[p+2]&65535,sh=c[p+3]&65535;boolean turn=rs[0][z[1]][z[2]]!=0;int vw=turn?sh:sw,vh=turn?sw:sh,dx=x+(w-vw)/2;if(dx<0)dx=0;if(dx+vw>screenW)dx=screenW-vw;g.drawRegion(a.sheet,sx,sy,sw,sh,turn?TRANS_ROT270:TRANS_NONE,dx,y+h-vh-2,Graphics.TOP|Graphics.LEFT);return true;}
    public static boolean drawFormationOutline(Graphics g,int form,int x,int y,int w,int h,int screenW,int direction,int tick,int color,boolean shiny){SpecialFormAtlas a=get(form);if(a==null)return false;int[] z=clip(a,0,direction,tick,shiny);if(z==null)return false;boolean useShiny=shiny&&a.shinyFrames[0][z[1]]!=null;short[][][] fs=useShiny?a.shinyFrames:a.frames;byte[][][] rs=useShiny?a.shinyRotated:a.rotated;short[] c=fs[0][z[1]];int p=z[3],sx=c[p]&65535,sy=c[p+1]&65535,sw=c[p+2]&65535,sh=c[p+3]&65535;boolean turn=rs[0][z[1]][z[2]]!=0;int vw=turn?sh:sw,vh=turn?sw:sh,dx=x+(w-vw)/2;if(dx<0)dx=0;if(dx+vw>screenW)dx=screenW-vw;try{if(a.outline==null||a.outDir!=z[1]||a.outCount!=c.length/8||a.outColor!=color||a.outShiny!=useShiny){a.outline=new Image[c.length/8];a.outDir=z[1];a.outCount=c.length/8;a.outColor=color;a.outShiny=useShiny;}int fi=z[2];if(a.outline[fi]==null){Image part=Image.createImage(a.sheet,sx,sy,sw,sh,turn?TRANS_ROT270:TRANS_NONE);int ow=vw+4,oh=vh+4,argb=0xFF000000|(color&0xFFFFFF);int[] src=new int[vw*vh],out=new int[ow*oh];part.getRGB(src,0,vw,0,0,vw,vh);for(int yy=0;yy<vh;yy++)for(int xx=0;xx<vw;xx++)if((src[yy*vw+xx]>>>24)!=0){int cx=xx+2,cy=yy+2;for(int yd=-1;yd<=1;yd++)for(int xd=-1;xd<=1;xd++)out[(cy+yd)*ow+cx+xd]=argb;}for(int yy=0;yy<vh;yy++)for(int xx=0;xx<vw;xx++)if((src[yy*vw+xx]>>>24)!=0)out[(yy+2)*ow+xx+2]=0;a.outline[fi]=Image.createRGBImage(out,ow,oh,true);}g.drawImage(a.outline[fi],dx-2,y+h-vh-4,Graphics.TOP|Graphics.LEFT);}catch(Exception e){return false;}return true;}
    public static boolean bounds(int form,int x,int y,int w,int h,int action,int direction,int tick,int[] out,boolean shiny){SpecialFormAtlas a=get(form);if(a==null)return false;int[] z=clip(a,action,direction,tick,shiny);if(z==null)return false;boolean useShiny=shiny&&a.shinyFrames[z[0]][z[1]]!=null;short[][][] fs=useShiny?a.shinyFrames:a.frames;byte[][][] rs=useShiny?a.shinyRotated:a.rotated;short[] c=fs[z[0]][z[1]];int p=z[3],sw=c[p+2]&65535,sh=c[p+3]&65535,ox=c[p+4]&65535,oy=c[p+5]&65535,sow=c[p+6]&65535,soh=c[p+7]&65535;boolean turn=rs[z[0]][z[1]][z[2]]!=0;out[0]=x+(w-sow)/2+ox;out[1]=y+h-soh+oy;out[2]=turn?sh:sw;out[3]=turn?sw:sh;return true;}
    public static void avatar(Graphics g,int form,int x,int y,boolean mini,boolean shiny){if(form<=0||form>=FORM_COUNT)return;int ai=form+(shiny?FORM_COUNT:0);if(AVATAR[ai]==null)try{AVATAR[ai]=Image.createImage("/formav/"+SpecialFormData.key(form)+(shiny?"-shiny":"")+".png");}catch(Exception e){if(shiny){avatar(g,form,x,y,mini,false);return;}return;}if(mini&&AVATAR_MINI[ai]==null)try{int s=20,sw=AVATAR[ai].getWidth(),sh=AVATAR[ai].getHeight();int[] src=new int[sw*sh],dst=new int[s*s];AVATAR[ai].getRGB(src,0,sw,0,0,sw,sh);for(int yy=0;yy<s;yy++)for(int xx=0;xx<s;xx++)dst[yy*s+xx]=src[(yy*sh/s)*sw+xx*sw/s];AVATAR_MINI[ai]=Image.createRGBImage(dst,s,s,true);}catch(Exception e){}g.drawImage(mini&&AVATAR_MINI[ai]!=null?AVATAR_MINI[ai]:AVATAR[ai],x,y,Graphics.TOP|Graphics.LEFT);}
}
