package pac;

/** Item-only forms; none of these entries are ever inserted into the shop pool. */
public final class SpecialFormData{
    private SpecialFormData(){}
    public static final int ALOLA_RATICATE=13,ALOLA_RAICHU=14,ALOLA_SANDSLASH=15,ALOLA_NINETALES=16,ALOLA_DUGTRIO=17,ALOLA_PERSIAN=18,HISUI_ARCANINE=19,ALOLA_GOLEM=20,GALAR_RAPIDASH=21,GALAR_SLOWBRO=22,ALOLA_MUK=23,HISUI_ELECTRODE=24,ALOLA_EXEGGUTOR=25,ALOLA_MAROWAK=26,GALAR_WEEZING=27,GALAR_MR_MIME=28,GALAR_ARTICUNO=38,GALAR_ZAPDOS=39,GALAR_MOLTRES=40,PALDEA_WOOPER=41,HISUI_QWILFISH=42,HISUI_SNEASEL=43,GALAR_CORSOLA=44,MAX_FORM=LaterFormData.MAX_FORM;
    public static boolean evolutionVariant(int form){return form>=13&&form<=44||GenThreeFormData.regional(form)||LaterFormData.regional(form);}
    public static final int NONE=0,PRIMAL_KYOGRE=1,PRIMAL_GROUDON=2,ORIGIN_GIRATINA=3,WALKING_WAKE=4,ZYGARDE_10=5,ZYGARDE_100=6,ZYGARDE_50=7,DEOXYS_ATTACK=8,DEOXYS_DEFENSE=9,DEOXYS_SPEED=10,HOOPA_UNBOUND=11,ULTRA_NECROZMA=12;
    public static final int MEMORY_PRICE=25,CUBE_PRICE=10,UNLOCK_ROUND=15;
    public static boolean memoryAvailable(int sp){int d=Data.nationalDex(sp);return d==382||d==383||d==487||d==245||d==386||d==720||d==800||d==144||d==145||d==146||d==194||d==211||d==215||d==222||GenTwoFormData.first(sp)!=0||GenThreeFormData.first(sp)!=0||d==263||d==264||LaterFormData.first(sp)!=0;}
    public static boolean zygarde(int sp){return Data.nationalDex(sp)==718;}
    /** Regional and cosmetic forms are not special-upgrade evolution markers. */
    public static boolean markerAvailable(int sp){int form=memoryForm(sp);return LaterFormData.marker(sp)||zygarde(sp)||(form>=PRIMAL_KYOGRE&&form<=ULTRA_NECROZMA);}
    public static int memoryForm(int sp){switch(Data.nationalDex(sp)){case 382:return PRIMAL_KYOGRE;case 383:return PRIMAL_GROUDON;case 487:return ORIGIN_GIRATINA;case 245:return WALKING_WAKE;case 386:return DEOXYS_ATTACK;case 720:return HOOPA_UNBOUND;case 800:return ULTRA_NECROZMA;case 144:return 38;case 145:return 39;case 146:return 40;case 194:return 41;case 211:return 42;case 215:return 43;case 222:return 44;case 263:return 74;case 264:return 75;default:if(LaterFormData.first(sp)!=0)return LaterFormData.first(sp);return GenThreeFormData.first(sp)!=0?GenThreeFormData.first(sp):GenTwoFormData.first(sp);}}
    public static int nextMemoryForm(int sp,int current){if(LaterFormData.first(sp)!=0)return LaterFormData.next(sp,current);if(GenThreeFormData.first(sp)!=0)return GenThreeFormData.next(sp,current);if(GenTwoFormData.first(sp)!=0)return GenTwoFormData.next(sp,current);if(Data.nationalDex(sp)!=386)return current==NONE?memoryForm(sp):NONE;if(current==NONE)return DEOXYS_ATTACK;if(current==DEOXYS_ATTACK)return DEOXYS_DEFENSE;if(current==DEOXYS_DEFENSE)return DEOXYS_SPEED;return DEOXYS_ATTACK;}
    public static String key(int form){if(LaterFormData.contains(form))return LaterFormData.key(form);if(GenThreeFormData.contains(form))return GenThreeFormData.key(form);if(GenTwoFormData.cosmetic(form))return GenTwoFormData.key(form);if(evolutionVariant(form))return EvolutionVariantData.key(form);switch(form){case PRIMAL_KYOGRE:return"0382-0001";case PRIMAL_GROUDON:return"0383-0001";case ORIGIN_GIRATINA:return"0487-0001";case WALKING_WAKE:return"1009";case ZYGARDE_10:return"0718-0001";case ZYGARDE_100:return"0718-0002";case DEOXYS_ATTACK:return"0386-0001";case DEOXYS_DEFENSE:return"0386-0002";case DEOXYS_SPEED:return"0386-0003";case HOOPA_UNBOUND:return"0720-0001";case ULTRA_NECROZMA:return"0800-0003";default:return"0718";}}
    public static String name(int form){if(LaterFormData.contains(form))return LaterFormData.name(form);if(GenThreeFormData.contains(form))return GenThreeFormData.name(form);if(GenTwoFormData.cosmetic(form))return GenTwoFormData.name(form);if(evolutionVariant(form))return EvolutionVariantData.name(form);switch(form){case PRIMAL_KYOGRE:return"Primal Kyogre";case PRIMAL_GROUDON:return"Primal Groudon";case ORIGIN_GIRATINA:return"Origin Giratina";case WALKING_WAKE:return"Walking Wake";case ZYGARDE_10:return"Zygarde 10%";case ZYGARDE_50:return"Zygarde 50%";case ZYGARDE_100:return"Zygarde 100%";case DEOXYS_ATTACK:return"Deoxys Công";case DEOXYS_DEFENSE:return"Deoxys Thủ";case DEOXYS_SPEED:return"Deoxys Tốc";case HOOPA_UNBOUND:return"Hoopa Unbound";case ULTRA_NECROZMA:return"Ultra Necrozma";default:return"";}}
    public static String memoryDesc(){return Lang.t("Đổi Pokémon tương thích sang dạng vùng miền, Unown, Pichu Spiky, Shadow Lugia, Castform, Kecleon tím, Primal, Origin, Ancient, Deoxys, Hoopa hoặc Ultra đến hết run. Dùng tiếp trên Deoxys để đổi Công - Thủ - Tốc. Tỏa sáng được giữ nguyên.","Changes compatible Pokemon to regional, Unown, Spiky Pichu, Shadow Lugia, Castform, Purple Kecleon, Primal, Origin, Ancient, Deoxys, Hoopa or Ultra form for the run. Reuse on Deoxys to cycle Attack, Defense and Speed. Shiny is preserved.");}
    public static String cubeDesc(){return Lang.t("Shop bán Zygarde 10% giá $5. Mỗi Cube giá $10: dùng lần đầu nâng 10% lên 50%, lần hai nâng 50% lên 100%. Không bắt buộc Tỏa sáng và giữ nguyên trạng thái Tỏa sáng.","The shop sells 10% Zygarde for $5. Each $10 Cube upgrades 10% to 50%, then 50% to 100%. Shiny is optional and preserved.");}
    public static void apply(Unit u,int form){if(form==NONE)return;u.specialForm=form;if(LaterFormData.contains(form)){u.type1=LaterFormData.type1(u.sp,form);u.type2=LaterFormData.type2(u.sp,form);if(LaterFormData.upgrade(form)){u.maxHp+=Math.max(10,Data.hp[u.sp]/5);u.hp=u.prevHp=u.maxHp;u.atk+=Math.max(2,Data.atk[u.sp]/5);u.def+=2;u.speDef+=2;u.speed+=5;}return;}if(GenThreeFormData.contains(form)){u.type1=GenThreeFormData.type1(u.sp,form);u.type2=GenThreeFormData.type2(u.sp,form);return;}if(GenTwoFormData.cosmetic(form))return;if(evolutionVariant(form)){u.type1=EvolutionVariantData.type1(u.sp,form);u.type2=EvolutionVariantData.type2(u.sp,form);return;}int hp=0,atk=0,def=0,sd=0,spd=0,range=0,mana=0;switch(form){case PRIMAL_KYOGRE:hp=380;atk=24;spd=60;def=10;sd=14;range=3;mana=90;break;case PRIMAL_GROUDON:u.type1=Data.T_GROUND;u.type2=Data.T_FIRE;hp=380;atk=26;spd=55;def=18;sd=10;range=1;mana=100;break;case ORIGIN_GIRATINA:hp=350;atk=28;spd=55;def=14;sd=14;range=2;mana=80;break;case WALKING_WAKE:hp=300;atk=25;spd=70;def=10;sd=8;range=2;mana=90;break;case ZYGARDE_10:hp=220;atk=20;spd=70;def=7;sd=7;range=1;mana=100;break;case ZYGARDE_50:hp=270;atk=24;spd=60;def=10;sd=10;range=1;mana=100;break;case ZYGARDE_100:hp=340;atk=28;spd=50;def=14;sd=14;range=2;mana=100;break;case DEOXYS_ATTACK:hp=230;atk=30;spd=75;def=4;sd=4;range=3;mana=100;break;case DEOXYS_DEFENSE:hp=300;atk=18;spd=45;def=18;sd=18;range=1;mana=100;break;case DEOXYS_SPEED:hp=250;atk=20;spd=95;def=7;sd=7;range=2;mana=70;break;case HOOPA_UNBOUND:hp=300;atk=28;spd=55;def=8;sd=14;range=2;mana=100;break;case ULTRA_NECROZMA:hp=340;atk=32;spd=70;def=12;sd=12;range=2;mana=90;break;}u.specialForm=form;u.maxHp+=hp-Data.hp[u.sp];u.hp=u.prevHp=u.maxHp;u.atk+=atk-Data.atk[u.sp];u.def+=def-Data.def[u.sp];u.speDef+=sd-Data.speDef[u.sp];u.speed+=spd-Data.speed[u.sp];u.range+=range-Data.range[u.sp];u.maxMana+=mana-Data.mana[u.sp];if(u.mana>u.maxMana)u.mana=u.maxMana;}
}
