package pac;

/** Run-local economy. These passives are arena rules, not Auto Chess effects. */
public final class SurvivalShop {
 public static final int MAX_RANK=10,SLOTS=6,GEARS=18,PARTS=6;
 // Utility/damage gear costs less than lethal guards and resurrection.
 private static final int[] UPGRADE_FEE={60,75,90,105,75,120,120,135,105,150,120,210,105,135,240,165,300,180};
 public final int[] ranks=new int[5],parts=new int[PARTS],bag=new int[GEARS],slots=new int[SLOTS];
 public int plannedGear=-1;
 public String activePassives(){String s="";for(int i=0;i<SLOTS;i++){int gear=slots[i];if(gear>=0&&gear<GEARS)s+=(s.length()==0?"":" | ")+gearName(gear)+": "+passiveDesc(gear);}return s.length()==0?Lang.t("Nội tại trang bị: Không có.","Equipment passives: None."):s;}
 public int quickTarget(SurvivalRun r){if(r.over||r.pendingLevels>0||r.variantPending>0||r.elementPending||plannedGear<0||plannedGear>=GEARS||bag[plannedGear]>0||has(plannedGear))return -1;if(r.gold>=remainingPrice(plannedGear))return plannedGear;if(r.gold<15)return -1;for(int node=0;node<2;node++)if(!ingredientOwned(plannedGear,node)){int part=node==0?A[plannedGear]:B[plannedGear];if(parts[part]<99)return GEARS+part;}return -1;}
 public boolean quickBuyAvailable(SurvivalRun r){return quickTarget(r)>=0;}
 public int quickPrice(int target){return target>=GEARS?15:remainingPrice(target);}
 public String quickName(int target){return target>=GEARS?ItemData.name(ICON[target-GEARS]):gearName(target);}
 public boolean quickPurchase(SurvivalRun r){int target=quickTarget(r);return buyAndEquip(r,target);}
 public boolean buyAndEquip(SurvivalRun r,int target){if(target<0||target>=GEARS+PARTS)return false;boolean ok=target>=GEARS?buy(r,target-GEARS):purchaseUpgrade(r,target);if(ok){if(target>=GEARS)equipPart(r,target-GEARS);else equip(r,target);fillSlots(r);}return ok;}
 public boolean equipPart(SurvivalRun r,int part){if(part<0||part>=PARTS)return false;int worn=0;for(int i=0;i<SLOTS;i++)if(slots[i]==GEARS+part)worn++;if(parts[part]<=worn)return false;for(int i=0;i<SLOTS;i++)if(slots[i]<0){slots[i]=GEARS+part;r.shopRebuild();return true;}return false;}
 private void fillSlots(SurvivalRun r){for(int gear=0;gear<GEARS;gear++)if(bag[gear]>0&&!has(gear))equip(r,gear);for(int part=0;part<PARTS;part++)while(equipPart(r,part)){} }
 private void consumePart(int part){parts[part]--;for(int i=0;i<SLOTS;i++)if(slots[i]==GEARS+part){slots[i]=-1;break;}}
 public int sellPrice(int target){return target>=GEARS&&target<GEARS+PARTS?7:target>=0&&target<GEARS?gearPrice(target)/2:0;}
 public boolean sell(SurvivalRun r,int target,int slot){if(r.over||target<0||target>=GEARS+PARTS)return false;if(slot>=0){if(slot>=SLOTS||slots[slot]!=target)return false;slots[slot]=-1;if(target>=GEARS)parts[target-GEARS]--;}else if(target>=GEARS){if(parts[target-GEARS]<=0)return false;consumePart(target-GEARS);}else{if(bag[target]>0)bag[target]--;else{int found=-1;for(int i=0;i<SLOTS;i++)if(slots[i]==target){found=i;break;}if(found<0)return false;slots[found]=-1;}}r.gold+=sellPrice(target);fillSlots(r);r.shopRebuild();return true;}
 public boolean plan(int gear){if(gear<0||gear>=GEARS)return false;plannedGear=plannedGear==gear?-1:gear;return true;}
 public boolean ingredientOwned(int gear,int node){if(gear<0||gear>=GEARS||node<0||node>1)return false;int part=node==0?A[gear]:B[gear];return parts[part]>=(node==1&&A[gear]==B[gear]?2:1);}
 public int remainingPrice(int gear){if(gear<0||gear>=GEARS)return-1;int credit=ingredientOwned(gear,0)?15:0;if(ingredientOwned(gear,1))credit+=15;return gearPrice(gear)-credit;}
 public boolean purchaseUpgrade(SurvivalRun r,int gear){int cost=remainingPrice(gear);if(r.over||cost<0||r.gold<cost||bag[gear]>=99||has(gear))return false;boolean a=ingredientOwned(gear,0),b=ingredientOwned(gear,1);r.gold-=cost;if(a)consumePart(A[gear]);if(b)consumePart(B[gear]);r.shopRebuild();bag[gear]++;if(plannedGear==gear)plannedGear=-1;return true;}
 public static final int[] ICON={7,8,1,3,5,6};
 public static final String[] GEAR_ID={"MUSCLE_BAND","ROCKY_HELMET","SHELL_BELL","SOUL_DEW","HEAVY_DUTY_BOOTS","CHOICE_SPECS","FLAME_ORB","POKEMONOMICON","PUNCHING_GLOVE","PROTECTIVE_PADS","STICKY_BARB","POKE_DOLL","POWER_LENS","XRAY_VISION","GRACIDEA_FLOWER","KINGS_ROCK","MAX_REVIVE","ASSAULT_VEST"};
 public static final int[] A={0,1,2,2,3,2,0,0,0,0,1,1,2,3,3,4,4,5},B={0,1,4,3,5,2,1,2,3,4,4,5,5,3,4,4,5,5};
 public SurvivalShop(){for(int i=0;i<SLOTS;i++)slots[i]=-1;}
 public static String statName(int i){return i==0?Lang.t("Máu","HP"):i==1?Lang.t("Công","ATK"):i==2?Lang.t("Giáp","Armor"):i==3?Lang.t("Kháng","Resistance"):Lang.t("Tốc","Speed");}
 public int price(int stat){return stat<0||stat>=5||ranks[stat]>=MAX_RANK?-1:20+ranks[stat]*15;}
 public boolean upgrade(SurvivalRun r,int stat){int cost=price(stat);if(r.over||cost<0||r.gold<cost||stat==4&&r.speed>=CombatRules.MAX_SPEED)return false;r.gold-=cost;ranks[stat]++;r.shopRebuild();return true;}
 public boolean buy(SurvivalRun r,int part){if(r.over||part<0||part>=PARTS||parts[part]>=99||r.gold<15)return false;r.gold-=15;parts[part]++;return true;}
 public static int upgradeFee(int gear){return gear<0||gear>=GEARS?-1:UPGRADE_FEE[gear];}
 public static int gearPrice(int gear){return gear<0||gear>=GEARS?-1:15+15+upgradeFee(gear);}
 public boolean buyGear(SurvivalRun r,int gear){return purchaseUpgrade(r,gear);}
 public static int gearIcon(int gear){return ItemData.indexOf(GEAR_ID[gear]);}
 public static String gearName(int gear){return ItemData.name(gearIcon(gear));}
 public static String gearDesc(int gear){return Lang.t("Chỉ số: ","Stats: ")+gearStats(gear)+"\n"+Lang.t("Nội tại: ","Passive: ")+passiveDesc(gear);}
 public static String gearStats(int gear){switch(gear){case 0:return Lang.t("Công +6","ATK +6");case 1:return Lang.t("Giáp +8","Armor +8");case 2:return Lang.t("Máu +40","HP +40");case 3:return Lang.t("MP +30, Kháng +5","MP +30, Resistance +5");case 4:return Lang.t("Tốc +12","Speed +12");case 5:return Lang.t("Công +5","ATK +5");default:return extraStats(gear);}}
 public static String componentDesc(){return Lang.t("Chỉ số: Không cộng khi nằm trong túi.\nNội tại: Không có.","Stats: No bonus while in the bag.\nPassive: None.");}
 public static String componentStats(int part){int i=ICON[part];String s="";s=statLine(s,ItemData.ATK[i],Lang.t("Công","ATK"));s=statLine(s,ItemData.DEF[i],Lang.t("Giáp","Armor"));s=statLine(s,ItemData.HP[i],Lang.t("Máu","HP"));s=statLine(s,ItemData.SPE_DEF[i],Lang.t("Kháng","Resistance"));s=statLine(s,ItemData.MP[i],"MP");s=statLine(s,ItemData.SPEED[i],Lang.t("Tốc","Speed"));s=statLine(s,ItemData.CRIT[i],Lang.t("Chí mạng","Crit"));if(ItemData.AP[i]>0)s+=(s.length()==0?"":", ")+Lang.t("Tuyệt kỹ +","Ultimate +")+ItemData.AP[i]+"%";return s.length()==0?Lang.t("Không.","None."):s;}
 private static String statLine(String s,int value,String name){return value==0?s:s+(s.length()==0?"":", ")+name+" +"+value;}
 private static String extraStats(int gear){int i=gearIcon(gear);String s="";s=statLine(s,ItemData.ATK[i],Lang.t("Công","ATK"));s=statLine(s,ItemData.DEF[i],Lang.t("Giáp","Armor"));s=statLine(s,ItemData.HP[i],Lang.t("Máu","HP"));s=statLine(s,ItemData.SPE_DEF[i],Lang.t("Kháng","Resistance"));s=statLine(s,ItemData.MP[i],"MP");s=statLine(s,ItemData.SPEED[i],Lang.t("Tốc","Speed"));if(ItemData.AP[i]>0)s+=(s.length()==0?"":", ")+Lang.t("Tuyệt kỹ +","Ultimate +")+ItemData.AP[i]+"%";return s.length()==0?Lang.t("Không.","None."):s;}
 public static String passiveDesc(int gear){switch(gear){case 0:return Lang.t("Hút máu 8% sát thương thực tế gây ra.","Heal for 8% actual damage dealt.");case 1:return Lang.t("Giảm thêm 10% sát thương nhận.","Take 10% less damage.");case 2:return Lang.t("Hồi 2% máu tối đa mỗi giây.","Regenerate 2% max HP per second.");case 3:return Lang.t("Hồi chiêu tuyệt kỹ giảm 20%: 30 còn 24 giây.","Ultimate cooldown -20%: 30 to 24s.");case 4:return Lang.t("Lướt tốn 15 MP thay vì 20.","Dash costs 15 MP instead of 20.");case 5:return Lang.t("Tuyệt kỹ tăng 25% sát thương.","Ultimate damage +25%.");case 6:return Lang.t("Đòn trúng đốt 3 giây: mỗi 0,5 giây gây 20% sát thương đòn trúng.","Hits burn for 3s: 20% hit damage every 0.5s.");case 7:return Lang.t("Đánh địch còn không quá 50% máu gây thêm 20% sát thương.","Deal 20% more damage to enemies at 50% HP or less.");case 8:return Lang.t("Mỗi 5 đòn trúng, đòn thứ 5 gây thêm 50% sát thương.","Every fifth hit deals 50% extra damage.");case 9:return Lang.t("Mỗi 15 giây tạo khiên bằng 20% máu tối đa (ít nhất 60), tồn tại 5 giây.","Every 15s: shield for 20% max HP (minimum 60), lasting 5s.");case 10:return Lang.t("Phản 25% sát thương mất máu vào địch gần nhất trong 100 px.","Reflect 25% HP damage to nearest enemy within 100px.");case 11:return Lang.t("Chặn đòn chí tử, giữ 1 máu và bất tử 2 giây. Hồi 60 giây.","Survive lethal damage at 1 HP, immune for 2s. Cooldown 60s.");case 12:return Lang.t("Dùng tuyệt kỹ thành công hoàn lại 20% MP tối đa.","Successful ultimate refunds 20% max MP.");case 13:return Lang.t("Mỗi 8 giây, lượt bắn kế tiếp chắc chắn chí mạng.","Every 8s, the next volley is a guaranteed critical.");case 14:return Lang.t("Khi đòn đánh sẽ đưa máu xuống 10%: chặn đòn, hồi 15% máu, khiên 40% máu trong 5 giây, bất tử 1 giây. Hồi 45 giây.","A hit reaching 10% HP is blocked; heal 15%, gain 40% HP shield for 5s and immunity for 1s. Cooldown 45s.");case 15:return Lang.t("Mỗi 6 đòn trúng làm địch choáng 1 giây.","Every sixth hit stuns the enemy for 1s.");case 16:return Lang.t("Hồi sinh tại chỗ với 50% máu/MP và bất tử 3 giây. Chỉ 1 lần mỗi lượt.","Revive with 50% HP/MP and 3s immunity. Once per run.");case 17:return Lang.t("Giảm thêm 25% sát thương kỹ năng nhận vào.","Take 25% less skill damage.");default:return "";}}
 public boolean has(int gear){for(int i=0;i<SLOTS;i++)if(slots[i]==gear)return true;return false;}
 public boolean canCraft(int gear){return gear>=0&&gear<GEARS&&bag[gear]<99&&parts[A[gear]]>=(A[gear]==B[gear]?2:1)&&parts[B[gear]]>=(A[gear]==B[gear]?2:1);}
 public boolean craft(SurvivalRun r,int gear){if(r.over||!canCraft(gear))return false;return purchaseUpgrade(r,gear);}
 public boolean craftParts(SurvivalRun r,int a,int b){int gear=SurvivalShopLayout.recipe(a,b);if(r.over||gear<0||bag[gear]>=99||has(gear)||r.gold<gearPrice(gear)-30||parts[a]<(a==b?2:1)||parts[b]<(a==b?2:1))return false;r.gold-=gearPrice(gear)-30;consumePart(a);consumePart(b);r.shopRebuild();bag[gear]++;if(plannedGear==gear)plannedGear=-1;return true;}
 public int extra(int[] values){int n=0;for(int i=0;i<SLOTS;i++)if(slots[i]>=GEARS)n+=values[ICON[slots[i]-GEARS]];else if(slots[i]>=6)n+=values[gearIcon(slots[i])];return n;}
 public boolean equip(SurvivalRun r,int gear){if(r.over||gear<0||gear>=GEARS||bag[gear]<=0||has(gear))return false;for(int i=0;i<SLOTS;i++)if(slots[i]<0){slots[i]=gear;bag[gear]--;r.shopRebuild();return true;}return false;}
 public boolean unequip(SurvivalRun r,int slot){if(r.over||slot<0||slot>=SLOTS||slots[slot]<0||slots[slot]<GEARS&&bag[slots[slot]]>=99)return false;if(slots[slot]<GEARS)bag[slots[slot]]++;slots[slot]=-1;r.shopRebuild();return true;}
 public int dashCost(){return has(4)?15:20;}
 public int ultiCooldown(){return has(3)?SurvivalRun.ULTIMATE_COOLDOWN*80/100:SurvivalRun.ULTIMATE_COOLDOWN;}
}
