package pac;

/** Fixed-step, allocation-free arena simulation. Progress is local to one attempt. */
public final class SurvivalRun {
    public static final int WIDTH=1280,HEIGHT=960,MAX_ENEMIES=28;
    public final SurvivalShop shop=new SurvivalShop();
    public static final int MAX_DROPS=12;public final int[] dropLife=new int[MAX_DROPS],dropX=new int[MAX_DROPS],dropY=new int[MAX_DROPS],dropPart=new int[MAX_DROPS];
    /** Gear/stat changes preserve missing HP/MP, never provide a free full heal. */
    public void shopRebuild(){rebuild();hp=Math.min(maxHp,hp);if(!shop.has(9)&&!shop.has(14)){shield=Math.max(0,shield-temporaryShield);temporaryShield=temporaryShieldLife=0;}}
    public void dropBossParts(int px,int py){int amount=2+rng.nextInt(3);for(int n=0;n<amount;n++){int part=rng.nextInt(SurvivalShop.PARTS),slot=-1;for(int i=0;i<MAX_DROPS;i++)if(dropLife[i]==0){slot=i;break;}if(slot<0){shop.parts[part]=Math.min(99,shop.parts[part]+1);continue;}dropPart[slot]=part;dropX[slot]=Math.max(12*256,Math.min((WIDTH-12)*256,px+(n-1)*12*256));dropY[slot]=Math.max(12*256,Math.min((HEIGHT-12)*256,py));dropLife[slot]=30000;}}
    private void updateDrops(){for(int i=0;i<MAX_DROPS;i++)if(dropLife[i]>0){dropLife[i]=Math.max(0,dropLife[i]-20);int dx=(dropX[i]-x)/256,dy=(dropY[i]-y)/256;if(dx*dx+dy*dy<=28*28){shop.parts[dropPart[i]]=Math.min(99,shop.parts[dropPart[i]]+1);dropLife[i]=0;notice=Lang.t("Nhặt mảnh: ","Component: ")+ItemData.name(SurvivalShop.ICON[dropPart[i]]);noticeT=1200;}}}
    public static final int MAX_RAYS=72,PLAYER_RAYS=56; public final int[] rayLife=new int[MAX_RAYS],rayX=new int[MAX_RAYS],rayY=new int[MAX_RAYS],rayVX=new int[MAX_RAYS],rayVY=new int[MAX_RAYS],rayDamage=new int[MAX_RAYS],rayType=new int[MAX_RAYS];public final boolean[] rayEnemy=new boolean[MAX_RAYS];
    public static final int MAX_FRUIT=8,MEMORY=11;public int target=-1,variantPending,noticeT;public String notice="";public final int[] fruitLife=new int[MAX_FRUIT],fruitX=new int[MAX_FRUIT],fruitY=new int[MAX_FRUIT],fruitKind=new int[MAX_FRUIT],buffTime=new int[4];public final int[] rayTier=new int[MAX_RAYS],rayPierce=new int[MAX_RAYS],rayBounce=new int[MAX_RAYS];private final int[] raySeen=new int[MAX_RAYS],burnTime=new int[MAX_ENEMIES],burnDamage=new int[MAX_ENEMIES],slowTime=new int[MAX_ENEMIES];
    public static final int VITALITY=0,POWER=1,ARMOR=2,HASTE=3,REACH=4,HEAL=5,ENERGY=6,EVOLVE=7,MEGA=8,SHINY=9,VARIANT=10;
    public static final int MULTISHOT=14,BURST=15,MAX_SHOTS=5,MAX_BURST=3,MAX_RANGE=6;
    public int shotCount=1,burstCount=1;private int burstLeft,burstClock,burstAimX,burstAimY,attackDir;
    public final Rng rng;
    public final int originalSpecies;
    public int sp,form,level=1,x=WIDTH*128,y=HEIGHT*128,dir=0,hp,maxHp,atk,def,speed,range,mana,maxMana;
    public int gold,lastGold,bossKills,goldFx,goldX,goldY;public int kills,wave=1,completedWaves,elapsed,xp,pendingLevels,normalCd,skillCd,swing,hurt,skillFx,skillAge;
    public static final int ULTIMATE_COOLDOWN=SurvivalBalance.ULTIMATE_MS;
    public int levelFx,transformFx;
    public int shield,specialDefense,criticalChance;
    public int gearFx,gearFxColor;private int temporaryShield,temporaryShieldLife,gloveHits,kingHits;private boolean reviveUsed;
    private final int[] gearCooldown=new int[SurvivalShop.GEARS],stunTime=new int[MAX_ENEMIES];
    /** Milliseconds left; -1 means the once-per-run revive is spent. */
    public int gearCooldownRemaining(int gear){if(gear<0||gear>=SurvivalShop.GEARS||!shop.has(gear))return 0;return gear==16&&reviveUsed?-1:gearCooldown[gear];}
    public int skillX,skillY,skillRadius;
    public final int[] bossFxLife=new int[MAX_ENEMIES],bossFxSp=new int[MAX_ENEMIES],bossFxX=new int[MAX_ENEMIES],bossFxY=new int[MAX_ENEMIES];
    public final int[] bossFxRadius=new int[MAX_ENEMIES];
    public static final int AREA=13;public int areaBonus;public static final int TARGETS=12,MAX_DEATHS=12;public int ultimateZones=1,zoneCount,skillSp,skillType,idleAge,dashCd,dashFx,dashX,dashY,heroDeath;public final int[] zoneX=new int[3],zoneY=new int[3],deathLife=new int[MAX_DEATHS],deathX=new int[MAX_DEATHS],deathY=new int[MAX_DEATHS],enemyRole=new int[MAX_ENEMIES],enemyIdle=new int[MAX_ENEMIES],warning=new int[MAX_ENEMIES],warnX=new int[MAX_ENEMIES],warnY=new int[MAX_ENEMIES];
    public boolean mega,shiny,over,moving;
    public final int[] choices=new int[3];
    public final int[] enemySp=new int[MAX_ENEMIES],ex=new int[MAX_ENEMIES],ey=new int[MAX_ENEMIES],ehp=new int[MAX_ENEMIES],emax=new int[MAX_ENEMIES],ecool=new int[MAX_ENEMIES],eflash=new int[MAX_ENEMIES],edir=new int[MAX_ENEMIES],edamage=new int[MAX_ENEMIES];
    public final int[] lastDamage=new int[MAX_ENEMIES];
    public int prevX,prevY,travel;
    public final int[] prevEx=new int[MAX_ENEMIES],prevEy=new int[MAX_ENEMIES],etravel=new int[MAX_ENEMIES],eswing=new int[MAX_ENEMIES];
    public final boolean[] emoving=new boolean[MAX_ENEMIES];
    private static int distanceTravel(int dx,int dy){dx=Math.abs(dx);dy=Math.abs(dy);return Math.max(dx,dy)+Math.min(dx,dy)*106/256;}
    public final int[] rayAge=new int[MAX_RAYS],prevRayX=new int[MAX_RAYS],prevRayY=new int[MAX_RAYS];
    public int renderRayX(int i){return SurvivalAnimation.interpolate(prevRayX[i],rayX[i],bank);}
    public int renderRayY(int i){return SurvivalAnimation.interpolate(prevRayY[i],rayY[i],bank);}
    public int renderX(){return SurvivalAnimation.interpolate(prevX,x,bank);}
    public int renderY(){return SurvivalAnimation.interpolate(prevY,y,bank);}
    public int renderEnemyX(int i){return SurvivalAnimation.interpolate(prevEx[i],ex[i],bank);}
    public int renderEnemyY(int i){return SurvivalAnimation.interpolate(prevEy[i],ey[i],bank);}
    private int hpBonus,atkBonus,defBonus,speedBonus,rangeBonus,bank,spawnLeft,spawnClock,waveClock=1600,regenClock,invulnerable;
    private final int[] pool=new int[Data.CORE_N];private int poolCount;
    private final Unit stats=new Unit();
    public SurvivalRun(int species,int seed){if(species<0||species>=Data.N)throw new IllegalArgumentException("hero");originalSpecies=species;sp=SurvivalProgress.startSpecies(species);rng=new Rng(seed);for(int i=0;i<MAX_ENEMIES;i++)enemySp[i]=-1;for(int i=0;i<Data.CORE_N;i++)if(Data.isBase(i)&&Data.category[i]<5)pool[poolCount++]=i;rebuild();hp=maxHp;prevX=x;prevY=y;}
    public int xpNeeded(){int lv=Math.min(1000,Math.max(1,level));return 6+lv*4+lv*(lv-1);}
    private void rebuild(){stats.sp=sp;stats.type1=Data.t1[sp];stats.type2=Data.t2[sp];stats.maxHp=Data.hp[sp];stats.atk=Data.atk[sp];stats.def=Data.def[sp];stats.speDef=Data.speDef[sp];stats.speed=Data.speed[sp];stats.range=Data.range[sp];stats.maxMana=Data.mana[sp];stats.mana=stats.skillBonus=stats.shield=stats.shieldDone=stats.crit=0;stats.mega=stats.shiny=false;stats.specialForm=0;if(mega)MegaData.apply(stats);else if(form!=0)SpecialFormData.apply(stats,form);if(shiny)ShinyData.apply(stats);maxHp=stats.maxHp+shop.extra(ItemData.HP)+hpBonus+shop.ranks[0]*20+(shop.has(2)?40:0);atk=stats.atk+shop.extra(ItemData.ATK)+atkBonus+shop.ranks[1]*2+(shop.has(0)?6:0)+(shop.has(5)?5:0);def=stats.def+shop.extra(ItemData.DEF)+defBonus+shop.ranks[2]*2+(shop.has(1)?8:0);specialDefense=stats.speDef+shop.extra(ItemData.SPE_DEF)+defBonus+shop.ranks[3]*2+(shop.has(3)?5:0);criticalChance=stats.crit+shop.extra(ItemData.CRIT);speed=CombatRules.cappedSpeed(stats.speed+shop.extra(ItemData.SPEED)+speedBonus+shop.ranks[4]*5+(shop.has(4)?12:0));range=Math.min(6,stats.range+rangeBonus);maxMana=Math.max(30,stats.maxMana)+shop.extra(ItemData.MP)+(shop.has(3)?30:0);mana=Math.min(mana,maxMana);}
    public int living(){int n=0;for(int i=0;i<MAX_ENEMIES;i++)if(enemySp[i]>=0)n++;return n;}
    public int reward(){return kills/5+completedWaves+completedWaves/5;}
    /** Returns a reward once; the screen owns the actual save write. */
    private boolean rewardClaimed;
    public int claimReward(){if(!over||rewardClaimed)return 0;rewardClaimed=true;return reward();}
    public void finish(){over=true;moving=false;target=-1;burstLeft=burstClock=0;for(int i=0;i<MAX_RAYS;i++)rayLife[i]=0;for(int i=0;i<MAX_FRUIT;i++)fruitLife[i]=0;for(int i=0;i<4;i++)buffTime[i]=0;}
    public int chosenSkillType=-1;public boolean elementPending;
    public int attackType(){return level<2?-1:chosenSkillType>=0&&(chosenSkillType==type1()||chosenSkillType==type2())?chosenSkillType:type1();}
    public int elementCount(){return type2()>=0&&type2()!=type1()?2:1;}
    public boolean chooseElement(int index){if(!elementPending||index<0||index>=elementCount())return false;chosenSkillType=index==0?type1():type2();elementPending=false;return true;}
    public int type1(){return mega?MegaData.type1(sp):form!=0&&!SpecialFormData.evolutionVariant(form)?stats.type1:EvolutionVariantData.type1(sp,form);}
    public int type2(){return mega?MegaData.type2(sp):form!=0&&!SpecialFormData.evolutionVariant(form)?stats.type2:EvolutionVariantData.type2(sp,form);}
    public String name(){return mega?MegaData.formName(sp):form!=0?SpecialFormData.name(form):Data.name[sp];}
    private static int direction(int dx,int dy){return dy>0?(dx>0?1:dx<0?7:0):dy<0?(dx>0?3:dx<0?5:4):dx>0?2:6;}
    public void update(int dt,int dx,int dy){if(over){updateVisuals(Math.max(0,Math.min(250,dt)));return;}if(pendingLevels>0||variantPending>0||elementPending)return;if(dt<0)return;if(dt>250)dt=250;bank+=dt;while(bank>=20&&!over&&pendingLevels==0&&variantPending==0&&!elementPending){bank-=20;tick(dx,dy);}}
    private void tick(int dx,int dy){prevX=x;prevY=y;for(int i=0;i<MAX_ENEMIES;i++){prevEx[i]=ex[i];prevEy[i]=ey[i];eswing[i]=Math.max(0,eswing[i]-20);}elapsed+=20;updateVisuals(20);tickGear();dashCd=Math.max(0,dashCd-20);noticeT=Math.max(0,noticeT-20);updateFruit();updateDrops();normalCd=Math.max(0,normalCd-20);skillCd=Math.max(0,skillCd-20);swing=Math.max(0,swing-20);hurt=Math.max(0,hurt-20);skillFx=Math.max(0,skillFx-20);skillAge+=20;invulnerable=Math.max(0,invulnerable-20);moving=dx!=0||dy!=0;if(moving){if(swing==0)dir=direction(dx,dy);int step=(58+speed/3)*256*20/1000;if(buffTime[0]>0)step=step*130/100;if(dx!=0&&dy!=0)step=step*181/256;x=Math.max(12*256,Math.min((WIDTH-12)*256,x+dx*step));y=Math.max(12*256,Math.min((HEIGHT-12)*256,y+dy*step));}moving=x!=prevX||y!=prevY;travel+=distanceTravel(x-prevX,y-prevY);idleAge=moving?0:idleAge+20;
        regenClock+=20;if(regenClock>=1000){regenClock-=1000;mana=Math.min(maxMana,mana+3);if(shop.has(2))hp=Math.min(maxHp,hp+Math.max(1,maxHp*2/100));}
        if(spawnLeft==0&&living()==0){waveClock-=20;if(waveClock<=0){spawnLeft=wavePopulation(wave);spawnClock=0;waveClock=1600;}}
        if(spawnLeft>0){spawnClock-=20;if(spawnClock<=0&&living()<MAX_ENEMIES){spawnEnemy();spawnLeft--;spawnClock=SurvivalBalance.spawnInterval(wave);}}
        for(int i=0;i<MAX_ENEMIES&&!over&&pendingLevels==0&&variantPending==0&&!elementPending;i++)if(enemySp[i]>=0){slowTime[i]=Math.max(0,slowTime[i]-20);if(burnTime[i]>0){int before=burnTime[i];burnTime[i]=Math.max(0,before-20);if(before/500!=burnTime[i]/500){hit(i,burnDamage[i],false);if(enemySp[i]<0)continue;if(pendingLevels>0||variantPending>0)break;}}if(stunTime[i]>0){stunTime[i]=Math.max(0,stunTime[i]-20);emoving[i]=false;continue;}eflash[i]=Math.max(0,eflash[i]-20);ecool[i]=Math.max(0,ecool[i]-20);int ax=x-ex[i],ay=y-ey[i];edir[i]=direction(ax,ay);int distance=distanceTravel(ax,ay),role=enemyRole[i];if(warning[i]>0){warning[i]=Math.max(0,warning[i]-20);emoving[i]=false;if(warning[i]==0){bossFxLife[i]=650;bossFxRadius[i]=bossRadius(i);bossFxSp[i]=enemySp[i];bossFxX[i]=warnX[i];bossFxY[i]=warnY[i];int wx=(x-warnX[i])/256,wy=(y-warnY[i])/256;int radius=bossRadius(i);if(wx*wx+wy*wy<=radius*radius){damageHero(edamage[i]*2,true);if(Data.t1[enemySp[i]]==Data.T_ELEC)mana=Math.max(0,mana-10);}ecool[i]=bossCooldown(i);eswing[i]=220;}}else{int stop=role==0?85:role==3?75:20;emoving[i]=distance>stop*256;if(emoving[i]){int step=(role==2?58:30+Math.min(40,wave*2))*256*20/1000;if(slowTime[i]>0)step=step*65/100;if(ax!=0&&ay!=0)step=step*181/256;ex[i]+=ax>0?Math.min(step,ax):Math.max(-step,ax);ey[i]+=ay>0?Math.min(step,ay):Math.max(-step,ay);}if(ecool[i]==0){if(role==0&&distance<=130*256){eswing[i]=220;ecool[i]=Math.max(750,1700-wave*20);fireRay(ex[i],ey[i],ax,ay,true,edamage[i],Data.t1[enemySp[i]],180);}else if(role==3&&distance<=160*256){warnX[i]=x;warnY[i]=y;warning[i]=bossWarning(i);}else if((role==1||role==2)&&distance<=24*256){eswing[i]=220;ecool[i]=role==2?1100:1300;damageHero(edamage[i]);}}}enemyIdle[i]=emoving[i]||eswing[i]>0?0:enemyIdle[i]+20;etravel[i]+=distanceTravel(ex[i]-prevEx[i],ey[i]-prevEy[i]);}if(!over&&pendingLevels==0&&variantPending==0&&!elementPending&&burstLeft>0){burstClock-=20;if(burstClock<=0){fireVolley(burstAimX,burstAimY,85);burstLeft--;burstClock=120;swing=220;attackDir=direction(burstAimX,burstAimY);}}if(swing>0)dir=attackDir;updateRays();
    }
    public static int wavePopulation(int wave){return Math.min(48,3+wave*2)+(wave%5==0?8:0);}
    /** Gentle opening, steeper health growth after wave ten; fixed role multipliers. */
    public static int enemyHealth(int species,int wave,int role){return SurvivalBalance.enemyHp(species,wave,role);}
    public static int enemyPower(int species,int wave){return SurvivalBalance.enemyAtk(species,wave);}
    public int attackCooldown(){return Math.max(400,CombatRules.cooldownTicks(700,speed)*100)+(burstCount-1)*80;}
    private int legendaryBoss(){int count=0;for(int i=0;i<Data.CORE_N;i++)if(SurvivalProgress.legendary(i))count++;if(count==0)return pool[0];int pick=rng.nextInt(count);for(int i=0;i<Data.CORE_N;i++)if(SurvivalProgress.legendary(i)&&pick--==0)return i;return pool[0];}
    public int bossRadius(int i){int type=Data.t1[enemySp[i]];return type==Data.T_FIRE?40:type==Data.T_ICE||type==Data.T_WATER?46:type==Data.T_ELEC?26:34;}
    public int bossWarning(int i){return SurvivalBalance.bossWarning(Data.t1[enemySp[i]]);}
    public int bossCooldown(int i){return SurvivalBalance.bossCooldown(Data.t1[enemySp[i]],wave);}
    private void spawnEnemy(){int slot=-1;for(int i=0;i<MAX_ENEMIES;i++)if(enemySp[i]<0){slot=i;break;}if(slot<0)return;int s=poolCount>0?pool[(wave*7+rng.nextInt(Math.min(6,poolCount)))%poolCount]:0;if(wave%5==0&&spawnLeft==1)s=legendaryBoss();enemySp[slot]=s;enemyRole[slot]=wave%5==0&&spawnLeft==1?3:(wave+spawnLeft)%3;enemyIdle[slot]=warning[slot]=0;burnTime[slot]=slowTime[slot]=burnDamage[slot]=stunTime[slot]=0;for(int r=0;r<MAX_RAYS;r++)raySeen[r]&=~(1<<slot);int side=rng.nextInt(4),radius=(200+rng.nextInt(81))*256;int along=(rng.nextInt(401)-200)*256;ex[slot]=Math.max(8*256,Math.min((WIDTH-8)*256,x+(side==0?-radius:side==1?radius:along)));ey[slot]=Math.max(8*256,Math.min((HEIGHT-8)*256,y+(side==2?-radius:side==3?radius:along)));emax[slot]=ehp[slot]=enemyHealth(s,wave,enemyRole[slot]);if(enemyRole[slot]==3){notice=Lang.t("BOSS: ","BOSS: ")+Data.name[s];noticeT=2200;}edamage[slot]=enemyPower(s,wave);prevEx[slot]=ex[slot];prevEy[slot]=ey[slot];etravel[slot]=eswing[slot]=0;emoving[slot]=false;ecool[slot]=700;eflash[slot]=0;edir[slot]=direction(x-ex[slot],y-ey[slot]);}
    private boolean fireRay(int sx,int sy,int dx,int dy,boolean enemy,int damage,int type,int velocity){int slot=-1;for(int i=enemy?PLAYER_RAYS:0;i<(enemy?MAX_RAYS:PLAYER_RAYS);i++)if(rayLife[i]==0){slot=i;break;}if(slot<0)return false;int norm=Math.max(1,distanceTravel(dx,dy));rayTier[slot]=enemy?1:skillTier();raySeen[slot]=0;rayPierce[slot]=!enemy&&rayTier[slot]>=3&&(SurvivalProgress.effect(type)==2||mega||form!=0&&!SpecialFormData.evolutionVariant(form))?2:0;rayBounce[slot]=!enemy&&rayTier[slot]>=3&&SurvivalProgress.effect(type)==3?1:0;rayAge[slot]=0;prevRayX[slot]=rayX[slot]=sx;prevRayY[slot]=rayY[slot]=sy;rayVX[slot]=(int)((long)dx*velocity*256/norm);rayVY[slot]=(int)((long)dy*velocity*256/norm);rayDamage[slot]=damage;rayType[slot]=type;rayEnemy[slot]=enemy;rayLife[slot]=enemy?2400:Math.max(100,attackRadius()*1000/velocity);return true;}
    private boolean rayTouches(int i,int tx,int ty){int dx=(rayX[i]-tx)/256,dy=(rayY[i]-ty)/256;return dx*dx+dy*dy<=(12+rayTier[i]*2)*(12+rayTier[i]*2);}
    private void updateRays(){for(int i=0;i<MAX_RAYS&&!over&&pendingLevels==0&&variantPending==0&&!elementPending;i++)if(rayLife[i]>0){prevRayX[i]=rayX[i];prevRayY[i]=rayY[i];rayAge[i]+=20;rayX[i]+=rayVX[i]*20/1000;rayY[i]+=rayVY[i]*20/1000;rayLife[i]=Math.max(0,rayLife[i]-20);if(rayEnemy[i]){if(rayTouches(i,x,y)){rayLife[i]=0;damageHero(rayDamage[i]);}}else for(int j=0;j<MAX_ENEMIES;j++)if(enemySp[j]>=0&&(raySeen[i]&(1<<j))==0&&rayTouches(i,ex[j],ey[j])){raySeen[i]|=1<<j;int effect=rayType[i]<0?0:SurvivalProgress.effect(rayType[i]);if(rayTier[i]>=3){if(effect==1){burnTime[j]=2000;burnDamage[j]=Math.max(1,rayDamage[i]/5);}else if(effect==4)slowTime[j]=1800;else if(effect==5){ex[j]=Math.max(12*256,Math.min((WIDTH-12)*256,ex[j]+rayVX[i]/20));ey[j]=Math.max(12*256,Math.min((HEIGHT-12)*256,ey[j]+rayVY[i]/20));}}hit(j,CombatRules.physicalDamage(rayDamage[i],Data.def[enemySp[j]]));if(rayBounce[i]>0){int next=-1,best=65*65;for(int k=0;k<MAX_ENEMIES;k++)if(enemySp[k]>=0&&(raySeen[i]&(1<<k))==0){int dx=(ex[k]-rayX[i])/256,dy=(ey[k]-rayY[i])/256,d=dx*dx+dy*dy;if(d<best){best=d;next=k;}}if(next>=0){int dx=ex[next]-rayX[i],dy=ey[next]-rayY[i],norm=Math.max(1,distanceTravel(dx,dy));rayVX[i]=(int)((long)dx*320*256/norm);rayVY[i]=(int)((long)dy*320*256/norm);rayLife[i]=250;rayBounce[i]--;}else rayLife[i]=0;}else if(rayPierce[i]>0)rayPierce[i]--;else rayLife[i]=0;break;}if(rayX[i]<0||rayY[i]<0||rayX[i]>WIDTH*256||rayY[i]>HEIGHT*256)rayLife[i]=0;}}
    private void gearPulse(int color,String name){gearFx=600;gearFxColor=color;notice=name;noticeT=1200;}
    private void grantGearShield(int amount,int life){int add=Math.max(0,amount-temporaryShield);shield+=add;temporaryShield+=add;temporaryShieldLife=Math.max(temporaryShieldLife,life);}
    private void tickGear(){for(int i=0;i<gearCooldown.length;i++)gearCooldown[i]=Math.max(0,gearCooldown[i]-20);if(temporaryShieldLife>0){temporaryShieldLife=Math.max(0,temporaryShieldLife-20);if(temporaryShieldLife==0){shield=Math.max(0,shield-temporaryShield);temporaryShield=0;}}if(shop.has(9)&&gearCooldown[9]==0){gearCooldown[9]=15000;grantGearShield(Math.max(60,maxHp/5),5000);gearPulse(0x80E8FF,"Protective Pads");}}
    private void damageHero(int power){damageHero(power,false);}
    private void damageHero(int power,boolean special){if(invulnerable>0||buffTime[3]>0||over)return;int damage=special?CombatRules.specialDamage(power,specialDefense):CombatRules.physicalDamage(power,def);if(shop.has(1))damage=Math.max(1,damage*90/100);if(special&&shop.has(17))damage=Math.max(1,damage*75/100);
        if(shop.has(14)&&gearCooldown[14]==0&&hp-Math.max(0,damage-shield)<=Math.max(1,maxHp/10)){gearCooldown[14]=45000;hp=Math.min(maxHp,hp+Math.max(1,maxHp*15/100));grantGearShield(Math.max(1,maxHp*40/100),5000);invulnerable=1000;gearPulse(0x80FFB0,"Gracidea Flower");return;}
        int absorbed=Math.min(shield,damage);shield-=absorbed;temporaryShield=Math.max(0,temporaryShield-absorbed);hp=Math.max(0,hp-(damage-absorbed));hurt=180;invulnerable=260;mana=Math.min(maxMana,mana+CombatRules.ON_DAMAGE_MANA);
        if(hp==0){if(shop.has(11)&&gearCooldown[11]==0){gearCooldown[11]=60000;hp=1;invulnerable=2000;gearPulse(0xFFE0F0,"Poke Doll");}else if(shop.has(16)&&!reviveUsed){reviveUsed=true;hp=Math.max(1,maxHp/2);mana=maxMana/2;invulnerable=3000;transformFx=1000;gearPulse(0xFFFFFF,"Max Revive");}else{heroDeath=650;addDeath(x,y);finish();return;}}
        if(shop.has(10)&&damage>absorbed){int enemy=closest(100);if(enemy>=0)hit(enemy,Math.max(1,(damage-absorbed)/4),false);}
    }
    private void addDeath(int px,int py){int slot=0;for(int i=0;i<MAX_DEATHS;i++)if(deathLife[i]<deathLife[slot])slot=i;deathLife[slot]=550;deathX[slot]=px;deathY[slot]=py;}
    private void updateVisuals(int dt){gearFx=Math.max(0,gearFx-dt);levelFx=Math.max(0,levelFx-dt);transformFx=Math.max(0,transformFx-dt);for(int i=0;i<MAX_ENEMIES;i++)bossFxLife[i]=Math.max(0,bossFxLife[i]-dt);goldFx=Math.max(0,goldFx-dt);heroDeath=Math.max(0,heroDeath-dt);dashFx=Math.max(0,dashFx-dt);for(int i=0;i<MAX_DEATHS;i++)deathLife[i]=Math.max(0,deathLife[i]-dt);}
public boolean dash(int dx,int dy){if(over||pendingLevels>0||variantPending>0||elementPending||dashCd>0||mana<shop.dashCost()||(dx==0&&dy==0))return false;dx=dx>0?1:dx<0?-1:0;dy=dy>0?1:dy<0?-1:0;dashX=x;dashY=y;int step=64*256;if(dx!=0&&dy!=0)step=step*181/256;x=Math.max(12*256,Math.min((WIDTH-12)*256,x+dx*step));y=Math.max(12*256,Math.min((HEIGHT-12)*256,y+dy*step));if(x==dashX&&y==dashY)return false;mana-=shop.dashCost();prevX=x;prevY=y;dir=direction(dx,dy);dashCd=900;dashFx=240;invulnerable=Math.max(invulnerable,160);return true;}
    public int impactRadius(){return 28+skillTier()*4+areaBonus;}
    public int skillTier(){return SurvivalProgress.skillTier(level);}public int ultimateRadius(){return 110+skillTier()*15+(mega||form!=0&&!SpecialFormData.evolutionVariant(form)?25:0);}public int attackPower(){int power=atk*(100+(skillTier()-1)*15)/100;return buffTime[1]>0?power*125/100:power;}
    public boolean targetValid(){return target>=0&&target<MAX_ENEMIES&&enemySp[target]>=0;}
    public void cycleTarget(){if(over||pendingLevels>0||variantPending>0||elementPending)return;int start=targetValid()?target:-1;for(int n=1;n<=MAX_ENEMIES;n++){int i=(start+n)%MAX_ENEMIES;if(enemySp[i]>=0){target=i;return;}}target=-1;}
    public void gainXp(int amount){if(over||amount<=0)return;xp+=amount;boolean changed=false;while(xp>=xpNeeded()){xp-=xpNeeded();level++;if(level==2)elementPending=true;pendingLevels++;changed=true;int next=level==5||level==10?evolutionNext():sp;if(next>=0&&next!=sp&&!mega){int oldForm=form;sp=next;form=LaterFormData.contains(oldForm)?LaterFormData.evolutionForm(sp,oldForm):GenThreeFormData.regional(oldForm)?EvolutionVariantData.formFor(sp):0;rebuild();notice=Lang.t("Tiến hóa: ","Evolved: ")+name();noticeT=2200;if(form==0&&EvolutionBranchData.available(choiceRoot(sp))){evolutionChoiceSpecies=choiceRoot(sp);variantPending=EvolutionVariantData.formFor(sp);if(variantPending==0)variantPending=1;}}hp=maxHp;mana=maxMana;}if(changed){normalCd=0;levelFx=700;rollChoices();}}
    private int evolutionChoiceSpecies=-1;
    private int evolutionNext(){if(SurvivalProgress.legendary(sp))return sp;if(SpecialFormData.evolutionVariant(form))return GenTwoFormData.evolved(sp,form);if(level==10&&form==0&&sp==SurvivalProgress.startSpecies(originalSpecies))return SurvivalProgress.speciesAt(originalSpecies,level);return SurvivalProgress.nextSpecies(sp,originalSpecies);}
    private int choiceRoot(int species){for(int i=0;i<Data.N;i++){int root=Data.evo[i];if(root<0||Data.fam[root]!=Data.fam[species]||Data.tier[root]!=Data.tier[species]||!EvolutionBranchData.available(root))continue;for(int n=0;n<EvolutionBranchData.count(root);n++)if(EvolutionBranchData.choiceSpecies(root,n)==species)return root;}return species;}
    public int variantCount(){return EvolutionBranchData.count(evolutionChoiceSpecies>=0?evolutionChoiceSpecies:sp);}
    public int variantSpecies(int index){return EvolutionBranchData.choiceSpecies(evolutionChoiceSpecies>=0?evolutionChoiceSpecies:sp,index);}
    public int variantForm(int index){return EvolutionBranchData.choiceForm(evolutionChoiceSpecies>=0?evolutionChoiceSpecies:sp,index);}
    public boolean chooseVariant(boolean regional){return chooseVariant(regional?1:0);}
    public boolean chooseVariant(int index){if(variantPending==0||over||index<0||index>=variantCount())return false;sp=variantSpecies(index);form=variantForm(index);variantPending=0;evolutionChoiceSpecies=-1;rebuild();chosenSkillType=attackType();hp=maxHp;mana=maxMana;return true;}
    private void dropFruit(int px,int py){if(rng.nextInt(100)>=18)return;for(int i=0;i<MAX_FRUIT;i++)if(fruitLife[i]==0){fruitX[i]=px;fruitY[i]=py;int roll=rng.nextInt(100);fruitKind[i]=roll<32?0:roll<64?1:roll<94?2:3;fruitLife[i]=12000;break;}}
    public void eatFruit(int kind){if(kind<0||kind>=4||over)return;buffTime[kind]=kind==3?3000:kind==2?6000:8000;notice=fruitName(kind);noticeT=1200;}
    public static String fruitName(int kind){return kind==0?Lang.t("Tốc chạy +30%","Move +30%"):kind==1?Lang.t("Công +25%","Attack +25%"):kind==2?Lang.t("Tốc bắn +20%","Fire rate +20%"):Lang.t("Bất tử","Invincible");}
    private void updateFruit(){for(int i=0;i<4;i++)buffTime[i]=Math.max(0,buffTime[i]-20);for(int i=0;i<MAX_FRUIT;i++)if(fruitLife[i]>0){fruitLife[i]=Math.max(0,fruitLife[i]-20);int dx=(fruitX[i]-x)/256,dy=(fruitY[i]-y)/256;if(fruitLife[i]>0&&dx*dx+dy*dy<=18*18){eatFruit(fruitKind[i]);fruitLife[i]=0;}}}
    private int closest(int radius){int target=-1,best=radius*radius;for(int i=0;i<MAX_ENEMIES;i++)if(enemySp[i]>=0){int dx=(ex[i]-x)/256,dy=(ey[i]-y)/256,d=dx*dx+dy*dy;if(d<=best){best=d;target=i;}}return target;}
    public int attackRadius(){return 47+range*16+(skillTier()-1)*8;} public boolean attack(){if(over||pendingLevels>0||variantPending>0||elementPending||normalCd>0)return false;if(!targetValid())target=closest(attackRadius());int ax,ay;if(target>=0){ax=ex[target]-x;ay=ey[target]-y;dir=direction(ax,ay);}else{ax=dir==1||dir==2||dir==3?256:dir==5||dir==6||dir==7?-256:0;ay=dir==0||dir==1||dir==7?256:dir==3||dir==4||dir==5?-256:0;}if(ax==0&&ay==0)ax=256;if(!fireVolley(ax,ay,100))return false;attackDir=dir=direction(ax,ay);burstAimX=ax;burstAimY=ay;burstLeft=burstCount-1;burstClock=120;normalCd=attackCooldown();if(buffTime[2]>0)normalCd=Math.max(400,normalCd*100/120);swing=220;mana=Math.min(maxMana,mana+8);return true;}
    /** Fixed fan around the locked aim; no allocation and no extra mana per pellet. */
    private boolean fireVolley(int ax,int ay,int percent){int norm=Math.max(1,distanceTravel(ax,ay));ax=(int)((long)ax*256/norm);ay=(int)((long)ay*256/norm);int power=Math.max(1,attackPower()*percent/100);boolean guaranteed=shop.has(13)&&gearCooldown[13]==0;if(guaranteed){power=power*CombatRules.CRIT_POWER_PERCENT/100;}else if(criticalChance>0&&rng.nextInt(100)<criticalChance)power=power*CombatRules.CRIT_POWER_PERCENT/100;boolean fired=fireRay(x,y,ax,ay,false,power,attackType(),320);if(!fired)return false;if(guaranteed){gearCooldown[13]=8000;gearPulse(0xFFE080,"Xray Vision");}for(int n=1;n<shotCount;n++){int offset=(n+1)/2*64;if((n&1)==0)offset=-offset;fireRay(x,y,ax-ay*offset/256,ay+ax*offset/256,false,Math.max(1,power*60/100),attackType(),320);}return true;}
    public int ultimateBonusPercent(){return (100+stats.skillBonus+shop.extra(ItemData.AP))*(shop.has(5)?125:100)/100-100;}
    public int ultimatePower(){return CombatRules.specialDamage((int)((long)attackPower()*(2+skillTier())*(100+stats.skillBonus+shop.extra(ItemData.AP))/100*(shop.has(5)?125:100)/100),0);}
    public boolean ultimate(){if(over||pendingLevels>0||variantPending>0||elementPending||skillCd>0||mana<maxMana)return false;if(!targetValid())target=closest(ultimateRadius());if(!targetValid())return false;int dx=(ex[target]-x)/256,dy=(ey[target]-y)/256;if(dx*dx+dy*dy>ultimateRadius()*ultimateRadius())return false;attackDir=dir=direction(ex[target]-x,ey[target]-y);zoneX[0]=skillX=ex[target];zoneY[0]=skillY=ey[target];zoneCount=1;for(int z=1;z<ultimateZones;z++){int best=-1,dist=ultimateRadius()*ultimateRadius();for(int i=0;i<MAX_ENEMIES;i++)if(enemySp[i]>=0){int ax=(ex[i]-x)/256,ay=(ey[i]-y)/256,d=ax*ax+ay*ay;boolean apart=true;for(int q=0;q<zoneCount;q++){ax=(ex[i]-zoneX[q])/256;ay=(ey[i]-zoneY[q])/256;if(ax*ax+ay*ay<=impactRadius()*impactRadius())apart=false;}if(apart&&d<dist){dist=d;best=i;}}if(best<0)break;zoneX[zoneCount]=ex[best];zoneY[zoneCount++]=ey[best];}int power=ultimatePower(),radius=impactRadius(),seen=0;skillRadius=radius;skillSp=sp;skillType=attackType();mana=0;skillCd=shop.ultiCooldown();skillFx=650;skillAge=0;swing=500;for(int z=0;z<zoneCount;z++)for(int i=0;i<MAX_ENEMIES;i++)if(enemySp[i]>=0&&(seen&(1<<i))==0){dx=(ex[i]-zoneX[z])/256;dy=(ey[i]-zoneY[z])/256;if(dx*dx+dy*dy<=radius*radius){seen|=1<<i;hit(i,CombatRules.specialDamage(z==0?power:power*65/100,Data.speDef[enemySp[i]]));}}if(shop.has(12)){mana=Math.min(maxMana,mana+Math.max(1,maxMana/5));gearPulse(0xA0C0FF,"Power Lens");}return true;}
    private void hit(int i,int damage){hit(i,damage,true);}
    private void hit(int i,int damage,boolean proc){if(enemySp[i]<0)return;if(proc){if(shop.has(7)&&ehp[i]*2<=emax[i])damage=damage*120/100;if(shop.has(8)&&++gloveHits>=5){gloveHits=0;damage=damage*150/100;gearPulse(0xFFD080,"Punching Glove");}if(shop.has(6)){burnTime[i]=3000;burnDamage[i]=Math.max(1,damage/5);}if(shop.has(15)&&++kingHits>=6){kingHits=0;stunTime[i]=1000;gearPulse(0xFFE080,"King's Rock");}}lastDamage[i]=damage;if(shop.has(0)&&hp>0)hp=Math.min(maxHp,hp+Math.max(1,Math.min(ehp[i],damage)*8/100));ehp[i]-=damage;eflash[i]=220;if(ehp[i]>0)return;addDeath(ex[i],ey[i]);dropFruit(ex[i],ey[i]);enemySp[i]=-1;burnTime[i]=slowTime[i]=stunTime[i]=0;if(target==i){target=-1;target=closest(attackRadius());}lastGold=SurvivalBalance.killGold(wave,enemyRole[i]==3);gold+=lastGold;if(enemyRole[i]==3){bossKills++;dropBossParts(ex[i],ey[i]);}goldX=ex[i];goldY=ey[i];goldFx=650;kills++;gainXp(SurvivalBalance.killXp(wave,enemyRole[i]==3));if(spawnLeft==0&&living()==0){completedWaves++;wave++;hp=Math.min(maxHp,hp+Math.max(3,maxHp/12));}}
    private boolean usefulBuff(int id){return id==MULTISHOT?shotCount<MAX_SHOTS:id==BURST?burstCount<MAX_BURST:id==AREA?areaBonus<18&&level>=5:id==TARGETS?ultimateZones<3&&level>=5:id==HASTE?speed<CombatRules.MAX_SPEED:id==REACH?range<6&&rangeBonus<3:id==HEAL?hp<maxHp:id==ENERGY?mana<maxMana:true;}
    private static final int[] BUFF_POOL={VITALITY,POWER,ARMOR,HASTE,REACH,TARGETS,AREA,MULTISHOT,BURST};
    public boolean canMega(){return !mega&&MegaData.available(sp)&&(form==0||SpecialFormData.zygarde(sp)&&form==SpecialFormData.ZYGARDE_100);}
    private void rollChoices(){for(int i=0;i<3;i++){int count=0;for(int p=0;p<BUFF_POOL.length;p++){int id=BUFF_POOL[p];boolean used=false;for(int j=0;j<i;j++)if(choices[j]==id)used=true;if(!used&&usefulBuff(id))count++;}int pick=rng.nextInt(count);for(int p=0;p<BUFF_POOL.length;p++){int id=BUFF_POOL[p];boolean used=false;for(int j=0;j<i;j++)if(choices[j]==id)used=true;if(!used&&usefulBuff(id)&&pick--==0){choices[i]=id;break;}}}if(canMega()&&level>=15)choices[2]=MEGA;else if(form==0&&!mega&&(SpecialFormData.memoryAvailable(sp)||SpecialFormData.zygarde(sp))&&level>=15)choices[2]=MEMORY;else if(!shiny&&ShinyData.available(sp)&&level>=12)choices[2]=SHINY;}
    public boolean choose(int index){if(over||pendingLevels<=0||variantPending>0||elementPending||index<0||index>=3)return false;int id=choices[index];switch(id){case MULTISHOT:if(shotCount>=MAX_SHOTS)return false;shotCount++;break;case BURST:if(burstCount>=MAX_BURST)return false;burstCount++;break;case AREA:if(level<5||areaBonus>=18)return false;areaBonus+=6;break;case TARGETS:if(ultimateZones>=3||level<5)return false;ultimateZones++;break;case VITALITY:hpBonus+=30;break;case POWER:atkBonus+=3;break;case ARMOR:defBonus+=3;break;case HASTE:if(!usefulBuff(HASTE))return false;speedBonus+=8;break;case REACH:if(!usefulBuff(REACH))return false;rangeBonus=Math.min(3,rangeBonus+1);break;case HEAL:hp=Math.min(maxHp,hp+Math.max(20,maxHp/3));break;case ENERGY:mana=maxMana;break;case EVOLVE:if(Data.evo[sp]<0)return false;sp=Data.evo[sp];break;case MEGA:if(level<15||!canMega())return false;mega=true;form=0;break;case SHINY:if(level<12||shiny||!ShinyData.available(sp))return false;shiny=true;break;case MEMORY:if(level<15||form!=0||mega||!(SpecialFormData.zygarde(sp)||SpecialFormData.memoryAvailable(sp)))return false;form=SpecialFormData.zygarde(sp)?SpecialFormData.ZYGARDE_100:SpecialFormData.memoryForm(sp);if(form==0)return false;break;case VARIANT:int nextForm=EvolutionVariantData.formFor(sp);if(mega||nextForm==0||nextForm==form)return false;form=nextForm;break;default:return false;}if(id==MEGA||id==SHINY||id==MEMORY)transformFx=1000;rebuild();if(id==SHINY&&ShinyData.role(sp)==0)shield=Math.max(0,shield-temporaryShield)+Math.max(1,maxHp/10)+temporaryShield;hp=maxHp;mana=maxMana;pendingLevels--;if(pendingLevels>0)rollChoices();return true;}
    public String choiceName(int id){switch(id){case MULTISHOT:return Lang.t("Đa tia: ","Fan: ")+(shotCount+1)+"/"+MAX_SHOTS;case BURST:return Lang.t("Liên xạ: ","Burst: ")+(burstCount+1)+"/"+MAX_BURST;case AREA:return Lang.t("Vùng chiêu +6 (tối đa +18)","Area +6 (max +18)");case TARGETS:return Lang.t("Vùng tuyệt kỹ +1 (tối đa 3)","Ultimate zone +1 (max 3)");case MEMORY:return SpecialFormData.name(SpecialFormData.zygarde(sp)?SpecialFormData.ZYGARDE_100:SpecialFormData.memoryForm(sp));case VITALITY:return Lang.t("Sinh lực +30","Vitality +30");case POWER:return Lang.t("Công +3","Attack +3");case ARMOR:return Lang.t("Thủ +3","Defense +3");case HASTE:return Lang.t("Tốc +8","Speed +8");case REACH:return Lang.t("Tầm +1 (tối đa 6, +3 buff)","Range +1 (max 6, +3 buffs)");case HEAL:return Lang.t("Hồi 33% máu","Heal 33% HP");case ENERGY:return Lang.t("Nạp tuyệt kỹ","Charge ultimate");case EVOLVE:return Lang.t("Tiến hóa: ","Evolve: ")+(Data.evo[sp]>=0?Data.name[Data.evo[sp]]:"?");case MEGA:return MegaData.formName(sp);case SHINY:return Lang.t("Tỏa sáng","Shiny");case VARIANT:return SpecialFormData.name(EvolutionVariantData.formFor(sp));default:return"";}}
}
