package pac;
import javax.microedition.lcdui.Graphics;

/** Manual endless defence using the selected profile Pokemon. */
public final class SurvivalScreen extends Screen {
 private SurvivalRun run;private int hero=-1,clock,select,moveKey,moveT,messageT,paidReward,rangeT;private final int[] spriteBounds=new int[4];
 private final SurvivalGearIcons gearIcons=new SurvivalGearIcons(),quickIcons=new SurvivalGearIcons();
 private final SurvivalTap touchTaps=new SurvivalTap();
 private final javax.microedition.lcdui.Image[] smallTypes=new javax.microedition.lcdui.Image[Data.NT];private final boolean[] smallTypeTried=new boolean[Data.NT];
 private void infoType(Graphics g,int type,int x,int y,boolean small){if(!small){Art.typeIcon(g,type,x,y);return;}if(type<0||type>=Data.NT)return;if(!smallTypeTried[type]){smallTypeTried[type]=true;try{javax.microedition.lcdui.Image source=javax.microedition.lcdui.Image.createImage("/type/"+Data.TNAME[type].toUpperCase()+".png");int w=source.getWidth(),h=source.getHeight();int[] pixels=new int[w*h],scaled=new int[100];source.getRGB(pixels,0,w,0,0,w,h);for(int yy=0;yy<10;yy++)for(int xx=0;xx<10;xx++)scaled[yy*10+xx]=pixels[yy*h/10*w+xx*w/10];smallTypes[type]=javax.microedition.lcdui.Image.createRGBImage(scaled,10,10,true);}catch(Exception e){}}if(smallTypes[type]!=null)g.drawImage(smallTypes[type],x,y,Graphics.TOP|Graphics.LEFT);else{g.setColor(Data.TCOL[type]);g.fillArc(x,y,10,10,0,360);}}
 private boolean touchMoving;private int touchX,touchY;
 private boolean buffAsk;private int buffIndex;
 private boolean started,paused,summary,exitAsk;private String message="";
 public SurvivalScreen(Game game){super(game);for(int i=0;i<Data.N;i++)if(Data.nationalDex(i)==Save.profileAvatarDex&&Save.ownsDex(Save.profileAvatarDex)&&!Save.inCamp(i)){hero=i;break;}if(hero>=0)run=new SurvivalRun(hero,(int)System.currentTimeMillis());}
 public SurvivalScreen(Game game,int species){super(game);if(species>=0&&species<Data.N&&Save.ownsDex(Data.nationalDex(species))&&!Save.inCamp(species)){hero=species;run=new SurvivalRun(hero,(int)System.currentTimeMillis());}}
 private void start(){run=new SurvivalRun(hero,(int)System.currentTimeMillis());started=true;buffAsk=false;touchMoving=false;paused=summary=exitAsk=false;select=paidReward=moveT=rangeT=messageT=clock=moveKey=0;message="";ghostLife=0;touchTaps.reset();resetTouchChoice();game.resetArenaInput();}
 private void say(String s){message=s;messageT=1500;}
 public void resumeArena(){paused=false;moveT=0;touchMoving=false;touchTaps.reset();resetTouchChoice();game.resetArenaInput();}
 public void endFromShop(){paused=false;exitAsk=true;select=0;game.resetArenaInput();}
 private void paintHeader(Graphics g){g.setClip(0,0,game.W,game.H);g.setColor(0x101827);g.fillRect(0,0,game.W,header());String wave=Lang.t("Đợt: ","Wave: ")+run.wave;Art.textCompact(g,wave,4,3,0xFFE080);String ko="KO: "+run.kills;Art.textCompact(g,ko,Art.compactWidth(wave)+12,3,0xFF5050);String gold="$ "+run.gold;Art.textCompact(g,gold,game.W-4-Art.compactWidth(gold),3,0xFFD040);if(quickOffer()){int gear=run.shop.quickTarget(run),y=quickY();Art.box(g,game.W-148,y,146,20,0x305C46,0x80E0A0);quickIcons.draw(g,gear,game.W-146,y+1,18,false);panelLine(g,Lang.t("Mua ","Buy ")+run.shop.quickName(gear),game.W-125,y+5,82,0xFFFFFF);panelLine(g,"$"+run.shop.quickPrice(gear),game.W-40,y+5,38,0xFFD070);}}
 private void healthBar(Graphics g,int x,int y,int w,int h,int value,int max,int color){Art.bar(g,x,y,w,h,value,max,color);g.setColor(0x1A2930);int marks=Math.max(1,w/5),step=Math.max(50,((max+marks*50-1)/(marks*50))*50);for(int amount=step;amount<max;amount+=step){int xx=x+(int)((long)amount*w/Math.max(1,max));g.drawLine(xx,y+1,xx,y+h-2);}}
 private void panelLine(Graphics g,String label,int x,int y,int w,int color){g.setClip(x,y,w,Art.compactHeight()+1);Art.textCompact(g,label,x,y,color);g.setClip(0,0,game.W,game.H);}
 private int skillSize(){return game.W<260?18:22;}
private int skillsX(){int slot=Math.max(12,Math.min(22,game.W/14)),mapW=Math.max(28,Math.min(60,game.W/6));return game.W<260?game.W-4-skillSize()*4:game.W-mapW-9-slot*3-skillSize()*4;}
 private void skillIcon(Graphics g,int i,int x,int y){int size=skillSize(),cd=i==0?run.normalCd:i==1?run.skillCd:i==3?run.dashCd:0;g.setColor(0x22374E);g.fillRect(x,y,size-2,size-2);g.setColor(cd>0||i==1&&run.mana<run.maxMana||i==3&&run.mana<20?0x667382:0x80D8FF);g.drawRect(x,y,size-3,size-3);int cx=x+size/2-1,cy=y+8;g.setColor(0xFFFFFF);if(i==0){g.drawLine(cx-6,cy+4,cx+5,cy-4);g.drawLine(cx+5,cy-4,cx+1,cy-4);g.drawLine(cx+5,cy-4,cx+5,cy);}else if(i==1){g.drawArc(cx-5,cy-5,10,10,0,360);g.drawLine(cx-7,cy,cx+7,cy);g.drawLine(cx,cy-7,cx,cy+7);}else if(i==2){g.drawArc(cx-5,cy-5,10,10,0,360);g.fillRect(cx-1,cy-1,3,3);}else{g.drawLine(cx-6,cy+4,cx,cy-4);g.drawLine(cx,cy-4,cx+5,cy+4);g.drawLine(cx-7,cy+1,cx-3,cy+1);}String label=cd>0?""+((cd+99)/100)/10+"."+((cd+99)/100)%10:i==0?"5":i==1?"#":i==2?"*":""+run.shop.dashCost();Art.textCompact(g,label,x+(size-2-Art.compactWidth(label))/2,y+12,cd>0?0xFFD070:0xFFFFFF);}
 private void paintPetPanels(Graphics g){int W=game.W,H=game.H,y=H-footer(),slot=Math.max(12,Math.min(22,W/14)),mapW=Math.max(28,Math.min(60,W/6)),mapX=W-mapW-2,gearX=mapX-slot*3-2,bx=40,bw=gearX-bx-5;
 g.setClip(0,0,W,H);g.setColor(0x101B2C);g.fillRect(0,y,W,footer());Art.bar(g,0,y,W,3,run.xp,run.xpNeeded(),0xE8BB40);int nameX=40,nameW=Math.max(1,skillsX()-nameX-29),textW=Art.compactWidth(run.name()),cycle=Math.max(1,textW-nameW+24),scroll=textW>nameW?Math.max(0,Math.min(textW-nameW,((clock/90)%cycle)-12)):0;g.setClip(nameX,y+5,nameW,12);Art.textCompact(g,run.name(),nameX-scroll,y+6,0xFFFFFF);if(textW>nameW)Art.textCompact(g,run.name(),nameX-scroll+textW+nameW+16,y+6,0xFFFFFF);g.setClip(0,0,W,H);infoType(g,run.type1(),skillsX()-26,y+5,true);if(run.type2()>=0)infoType(g,run.type2(),skillsX()-14,y+5,true);for(int i=0;i<4;i++)skillIcon(g,i,skillsX()+i*skillSize(),y+5);
 int py=y+25,avatarY=y+7;g.setClip(4,avatarY,32,32);PetAvatar.draw(g,run.sp,run.form,run.mega,run.shiny,4,avatarY,32);g.setClip(0,0,W,H);panelLine(g,Lang.t("Cấp: ","Lv: ")+run.level,4,avatarY+35,36,0xFFE080);
 healthBar(g,bx,py+5,bw,10,run.hp,run.maxHp,0x40CD70);if(run.shield>0){g.setColor(0xA0E9FF);g.fillRect(bx,py+5,Math.min(bw,Math.max(1,(int)((long)run.shield*bw/run.maxHp))),2);}String hp=""+run.hp;panelLine(g,hp,bx+(bw-Art.compactWidth(hp))/2,py+6,Art.compactWidth(hp)+1,0xFFFFFF);Art.bar(g,bx,py+19,bw,9,run.mana,run.maxMana,0x4898EF);String mp=""+run.mana;panelLine(g,mp,bx+(bw-Art.compactWidth(mp))/2,py+20,Art.compactWidth(mp)+1,0xFFFFFF);
for(int i=0;i<6;i++){int gx=gearX+(i%3)*slot,gy=(W<260?py:y+5)+(i/3)*slot;g.setColor(0x080F1A);g.fillRect(gx,gy,slot-2,slot-2);g.setColor(0x536680);g.drawRect(gx,gy,slot-3,slot-3);if(run.shop.slots[i]>=0){int gear=run.shop.slots[i],cd=run.gearCooldownRemaining(gear);gearIcons.draw(g,gear,gx+1,gy+1,slot-4,cd!=0);if(cd!=0){String label=cd<0?"X":""+((cd+999)/1000);int tw=Art.compactWidth(label),tx=gx+(slot-2-tw)/2,ty=gy+slot-12;g.setColor(0x101827);g.fillRect(tx-1,ty-1,tw+2,10);panelLine(g,label,tx,ty,tw+1,cd<0?0xFF9090:0xFFE080);}g.setClip(0,0,W,H);}}int mapY=W<260?py:y+5,mh=H-mapY-2;g.setColor(0x203B31);g.fillRect(mapX-2,mapY,mapW+4,mh);g.setColor(0x536680);g.drawRect(mapX-2,mapY,mapW+3,mh-1);for(int i=0;i<SurvivalRun.MAX_ENEMIES;i++)if(run.enemySp[i]>=0){g.setColor(run.target==i?0xFFE060:0xEF7060);g.fillRect(mapX+1+run.ex[i]/256*(mapW-4)/SurvivalRun.WIDTH,mapY+1+run.ey[i]/256*(mh-4)/SurvivalRun.HEIGHT,2,2);}g.setColor(0xFFFFFF);g.fillRect(mapX+1+run.x/256*(mapW-4)/SurvivalRun.WIDTH,mapY+1+run.y/256*(mh-4)/SurvivalRun.HEIGHT,2,2);g.setClip(0,0,W,H);
 }
 private int[] ghostPixels=new int[48*64];private int ghostLife,ghostX,ghostY;private boolean ghostDash;private final int[] ghostCapture=new int[48*64];private javax.microedition.lcdui.Image ghostImage;
 private void prepareGhost(){if(ghostImage==null)ghostImage=javax.microedition.lcdui.Image.createImage(48,64);Graphics gg=ghostImage.getGraphics();gg.setColor(0xFF00FF);gg.fillRect(0,0,48,64);int action=run.hurt>0?RawAtlas.HURT:run.swing>0?RawAtlas.ATTACK:run.moving?RawAtlas.WALK:RawAtlas.IDLE;int age=action==RawAtlas.IDLE?run.idleAge:run.hurt>0?180-run.hurt:run.skillFx>0?500-run.swing:220-run.swing;model(gg,run.sp,run.form,run.mega,run.shiny,24,56,action,run.dir,SurvivalAnimation.clock(action,age,run.travel));ghostImage.getRGB(ghostCapture,0,48,0,0,48,64);}
 private void captureGhost(boolean dash){for(int yy=0;yy<64;yy++)for(int xx=0;xx<48;xx++){int i=yy*48+xx,c=ghostCapture[i]&0xFFFFFF;if(c==0xFF00FF||c==0x345032){ghostPixels[i]=0;continue;}boolean edge=xx==0||xx==47||yy==0||yy==63;if(!edge){int up=ghostCapture[i-48]&0xFFFFFF,down=ghostCapture[i+48]&0xFFFFFF,left=ghostCapture[i-1]&0xFFFFFF,right=ghostCapture[i+1]&0xFFFFFF;edge=up==0xFF00FF||down==0xFF00FF||left==0xFF00FF||right==0xFF00FF||up==0x345032||down==0x345032;}ghostPixels[i]=0xDC000000|(edge?0xBCEEFF:0xFFFFFF);}ghostX=dash?run.dashX:run.x;ghostY=dash?run.dashY:run.y;if(!dash){int d=run.dir;ghostX-=(d==1||d==2||d==3?1:d==5||d==6||d==7?-1:0)*5*256;ghostY-=(d==0||d==1||d==7?1:d==3||d==4||d==5?-1:0)*5*256;}ghostLife=dash?320:220;ghostDash=dash;}
 private void blink(int dx,int dy){if(run.dashCd==0&&run.mana>=run.shop.dashCost())prepareGhost();if(run.dash(dx,dy))captureGhost(true);else if(run.mana<run.shop.dashCost())say(Lang.t("Cần MP để lướt: ","Blink needs MP: ")+run.shop.dashCost());}
 private void paintGhost(Graphics g,int ox,int oy,int camX,int camY,int px,int py){if(ghostLife<=0)return;int x=ox+ghostX/256-camX,y=oy+ghostY/256-camY;int alpha=220*ghostLife/(ghostDash?320:220);for(int i=0;i<ghostPixels.length;i++)if(ghostPixels[i]!=0)ghostPixels[i]=(alpha<<24)|(ghostPixels[i]&0xFFFFFF);g.drawRGB(ghostPixels,0,48,x-24,y-56,48,64,true);if(ghostDash){g.setColor(0xB8F0FF);for(int i=1;i<=4;i++){int xx=x+(px-x)*i/5,yy=y+(py-y)*i/5;g.drawLine(xx-3,yy-14,xx+3,yy-20);}int r=6+(320-ghostLife)/20;g.drawArc(x-r,y-12-r,r*2,r*2,0,360);g.drawArc(px-10,py-22,20,20,0,360);}else{g.setColor(Data.TCOL[run.type1()]);g.drawArc(x-13,y-27,26,24,20,120);g.drawLine(x-15,y-20,x-19,y-23);g.drawLine(x+15,y-20,x+19,y-23);}}

 private static int dx(int k){return k==Game.K_LEFT||k==Game.K_1||k==Game.K_7?-1:k==Game.K_RIGHT||k==Game.K_3||k==Game.K_9?1:0;}
 private static int dy(int k){return k==Game.K_UP||k==Game.K_1||k==Game.K_3?-1:k==Game.K_DOWN||k==Game.K_7||k==Game.K_9?1:0;}
 private void settle(){if(summary)return;run.finish();paidReward=run.claimReward();Save.balls+=paidReward;Save.save();summary=true;paused=exitAsk=false;select=0;}
 public void update(int dt){clock+=dt;if(paused||summary||exitAsk||run!=null&&(run.pendingLevels>0||run.variantPending>0||run.elementPending)){touchMoving=false;moveT=0;}ghostLife=Math.max(0,ghostLife-dt);messageT=Math.max(0,messageT-dt);if(!started||summary||paused||exitAsk||run.pendingLevels>0||run.variantPending>0||run.elementPending)return;rangeT=Math.max(0,rangeT-dt);int k=game.heldDirection();if(k==Game.K_NONE&&(touchMoving||moveT>0))k=moveKey;moveT=Math.max(0,moveT-dt);run.update(dt,dx(k),dy(k));if(run.over&&run.heroDeath==0)settle();}
 public void key(int k){
  if(k!=Game.K_FIRE&&k!=Game.K_SOFT1)resetTouchChoice();
  if(buffAsk){if(k==Game.K_0||k==Game.K_SOFT2){buffAsk=false;select=buffIndex;resetTouchChoice();}else if(k==Game.K_UP||k==Game.K_DOWN||k==Game.K_LEFT||k==Game.K_RIGHT)select=1-select;else if(k==Game.K_FIRE||k==Game.K_SOFT1){if(select==1){if(run.choose(buffIndex)){buffAsk=false;select=0;}else{buffAsk=false;select=buffIndex;}}else{buffAsk=false;select=buffIndex;}moveT=0;game.resetArenaInput();touchTaps.reset();resetTouchChoice();}return;}
  if(!started){if(k==Game.K_0||k==Game.K_SOFT2)game.setScreen(new SurvivalPickScreen(game));else if(k==Game.K_FIRE||k==Game.K_SOFT1){if(hero>=0)start();else game.setScreen(new SurvivalPickScreen(game));}return;}
  if(summary){if(k==Game.K_LEFT||k==Game.K_UP)select=0;else if(k==Game.K_RIGHT||k==Game.K_DOWN)select=1;else if(k==Game.K_0||k==Game.K_SOFT2)game.setScreen(new ExploreHubScreen(game));else if(k==Game.K_FIRE||k==Game.K_SOFT1){if(select==0)start();else game.setScreen(new ExploreHubScreen(game));}return;}
  if(exitAsk){if(k==Game.K_UP||k==Game.K_LEFT)select=0;else if(k==Game.K_DOWN||k==Game.K_RIGHT)select=1;else if(k==Game.K_0||k==Game.K_SOFT2)exitAsk=false;else if(k==Game.K_FIRE||k==Game.K_SOFT1){if(select==1)settle();else exitAsk=false;}return;}
  if(paused){if(k==Game.K_UP||k==Game.K_DOWN||k==Game.K_LEFT||k==Game.K_RIGHT)select=1-select;else if(k==Game.K_0||k==Game.K_SOFT2)paused=false;else if(k==Game.K_FIRE||k==Game.K_SOFT1){if(select==1){paused=false;exitAsk=true;select=0;}else paused=false;}game.resetArenaInput();touchTaps.reset();return;}
  if(k==Game.K_0||k==Game.K_SOFT2){paused=true;game.resetArenaInput();touchTaps.reset();select=0;moveT=0;touchMoving=false;game.setScreen(new SurvivalShopScreen(game,this,run));return;}
  if(run.variantPending>0){if(k==Game.K_LEFT||k==Game.K_RIGHT||k==Game.K_UP||k==Game.K_DOWN)select=(select+(k==Game.K_LEFT||k==Game.K_UP?run.variantCount()-1:1))%run.variantCount();else if(k==Game.K_FIRE||k==Game.K_SOFT1){run.chooseVariant(select);select=0;game.resetArenaInput();touchTaps.reset();}return;}

  if(run.elementPending){if(k==Game.K_UP||k==Game.K_DOWN||k==Game.K_LEFT||k==Game.K_RIGHT)select=(select+1)%run.elementCount();else if(k==Game.K_FIRE||k==Game.K_SOFT1){run.chooseElement(select);select=0;moveT=0;game.resetArenaInput();touchTaps.reset();}return;}
  if(run.pendingLevels>0){if(k==Game.K_UP||k==Game.K_LEFT)select=(select+2)%3;else if(k==Game.K_DOWN||k==Game.K_RIGHT)select=(select+1)%3;else if(k==Game.K_FIRE||k==Game.K_SOFT1){buffIndex=select;buffAsk=true;select=0;moveT=0;game.resetArenaInput();touchTaps.reset();resetTouchChoice();}return;}
  if(k>Game.K_DASH_BASE&&k<=Game.K_DASH_BASE+Game.K_9){int direction=k-Game.K_DASH_BASE;blink(dx(direction),dy(direction));return;}
  if(k==Game.K_STAR){run.cycleTarget();return;}  if(dx(k)!=0||dy(k)!=0){moveKey=k;moveT=game.heldDirection()==Game.K_NONE?120:0;}else if(k==Game.K_FIRE||k==Game.K_SOFT1){rangeT=650;if(run.attack()){prepareGhost();captureGhost(false);}}else if(k==Game.K_POUND){if(!run.ultimate())say(run.mana<run.maxMana?Lang.t("Chưa đủ năng lượng","Not enough energy"):Lang.t("Tuyệt kỹ chưa sẵn sàng","Ultimate not ready"));}
 }
 private boolean quickOffer(){return run!=null&&!paused&&!summary&&!exitAsk&&!buffAsk&&run.shop.quickBuyAvailable(run);}
 private int quickY(){return Art.compactHeight()+6;}
 private int header(){return quickY()+(quickOffer()?22:0);}private int footer(){int slot=Math.max(12,Math.min(22,game.W/14));return game.W<260?Math.max(54,27+slot*2):54;}
public boolean pointer(int x,int y){if(buffAsk){if(modalHit(x,y,135,49,34,2)&&confirmTouch(700+select))key(Game.K_FIRE);return true;}if(!started||summary){if(summary){if(modalHit(x,y,186,111,30,2)&&confirmTouch(100+select))key(Game.K_FIRE);}else key(Game.K_FIRE);return true;}if(paused||exitAsk){if(modalHit(x,y,exitAsk?135:115,exitAsk?49:29,34,2)&&confirmTouch((exitAsk?200:300)+select))key(Game.K_FIRE);return true;}if(run.variantPending>0){if(y>=modalY(140)+118&&y<modalY(140)+140&&x>=(game.W-modalWidth())/2&&x<(game.W+modalWidth())/2){select=(select+(x<game.W/2?run.variantCount()-1:1))%run.variantCount();touchTaps.reset();return true;}int page=select/2;if(modalHit(x,y,140,29,45,Math.min(2,run.variantCount()-page*2))){select+=page*2;if(confirmTouch(400+select))key(Game.K_FIRE);}return true;}if(run.elementPending){int left=(game.W-elementWidth())/2,top=elementTop()+29,index=(y-top)/34;if(x>=left+7&&x<left+elementWidth()-7&&y>=top&&index<run.elementCount()&&(y-top)%34<29){select=index;if(confirmTouch((run.elementPending?500:600)+select))key(Game.K_FIRE);}return true;}if(run.pendingLevels>0){int top=choiceTop()+29,w=Math.min(game.W-16,300),left=(game.W-w)/2,index=(y-top)/choiceRow();if(y>=top&&index<3&&(y-top)%choiceRow()<29&&x>=left+7&&x<left+w-7){select=index;if(confirmTouch(600+select))key(Game.K_FIRE);}return true;}if(quickOffer()&&y>=quickY()&&y<quickY()+20&&x>=game.W-148){if(run.shop.quickPurchase(run)){say(Lang.t("Đã mua vào túi.","Purchased into bag."));touchMoving=false;moveKey=moveT=0;game.resetArenaInput();}return true;}if(y>=game.H-footer()+5&&y<game.H-footer()+27&&x>=skillsX()&&x<skillsX()+skillSize()*4){int index=Math.min(3,(x-skillsX())/skillSize());if(index==3){int d=run.dir;blink(d==1||d==2||d==3?1:d==5||d==6||d==7?-1:0,d==0||d==1||d==7?1:d==3||d==4||d==5?-1:0);}else key(index==0?Game.K_FIRE:index==1?Game.K_POUND:Game.K_STAR);return true;}if(y<header()){key(Game.K_0);return true;}if(y>=game.H-footer())return true;touchMoving=true;touchX=x;touchY=y;int ax=x-game.W/2,ay=y-(header()+(game.H-header()-footer())/2);moveKey=ay<-12?(ax<-12?Game.K_1:ax>12?Game.K_3:Game.K_UP):ay>12?(ax<-12?Game.K_7:ax>12?Game.K_9:Game.K_DOWN):ax<0?Game.K_LEFT:Game.K_RIGHT;if(touchTaps.press(moveKey,clock))blink(dx(moveKey),dy(moveKey));moveT=0;return true;}
 public void pointerDrag(int x,int y){if(!touchMoving)return;int ax=x-touchX,ay=y-touchY;if(Math.abs(ax)<8&&Math.abs(ay)<8)return;moveKey=ay<-8?(ax<-8?Game.K_1:ax>8?Game.K_3:Game.K_UP):ay>8?(ax<-8?Game.K_7:ax>8?Game.K_9:Game.K_DOWN):ax<0?Game.K_LEFT:Game.K_RIGHT;}
 public void pointerRelease(int x,int y){touchMoving=false;moveT=0;moveKey=Game.K_NONE;}
 private void drawFruit(Graphics g,int kind,int x,int y){int color=kind==0?0x55DDF0:kind==1?0xF08060:kind==2?0xEED050:0xCE80FF;g.setColor(0x25402A);g.fillArc(x-6,y+2,12,4,0,360);g.setColor(color);g.fillArc(x-5,y-6,10,10,0,360);g.setColor(0xFFFFFF);g.fillRect(x-2,y-4,2,2);g.setColor(0x58C060);g.drawLine(x,y-6,x+3,y-9);}
 private int modalWidth(){return Math.min(game.W-16,300);}
 private int modalY(int h){return Math.max(4,(game.H-h)/2);}
 private void modal(Graphics g,String title,int h){int w=modalWidth(),x=(game.W-w)/2,y=modalY(h);g.setClip(0,0,game.W,game.H);Art.box(g,x,y,w,h,0x101B2C,0x59728E);g.setColor(0x21364F);g.fillRect(x+1,y+1,w-2,23);panelLine(g,title,x+9,y+8,w-18,0xFFE080);}
 private void card(Graphics g,int index,int y,int h,String label){int w=modalWidth(),x=(game.W-w)/2;g.setColor(index==select?0x304A68:0x19293D);g.fillRect(x+7,y,w-14,h);g.setColor(index==select?0xFFFFFF:0x40536A);g.drawRect(x+7,y,w-15,h-1);panelLine(g,label,x+14,y+(h-Art.compactHeight())/2,w-28,0xFFFFFF);}
 private boolean modalHit(int x,int y,int h,int first,int row,int count){int w=modalWidth(),left=(game.W-w)/2,top=modalY(h)+first,index=(y-top)/row;if(x<left+7||x>=left+w-7||y<top||index>=count||(y-top)%row>=row-5)return false;select=index;return true;}
 private void paintVariant(Graphics g){int h=140,y=modalY(h),w=modalWidth(),x=(game.W-w)/2,page=select/2;modal(g,Lang.t("CHỌN DẠNG TIẾN HÓA","CHOOSE EVOLUTION"),h);for(int row=0;row<2;row++){int i=page*2+row;if(i>=run.variantCount())break;int ry=y+29+row*45,s=run.variantSpecies(i),f=run.variantForm(i);card(g,i,ry,40,"");if(f==0)Art.avatar(g,s,x+13,ry+4);else SpecialFormAtlas.avatar(g,f,x+13,ry+4,false,false);panelLine(g,f==0?Data.name[s]:SpecialFormData.name(f),x+50,ry+6,w-63,0xFFFFFF);int t1=EvolutionVariantData.type1(s,f),t2=EvolutionVariantData.type2(s,f);Art.typeIcon(g,t1,x+50,ry+19);if(t2>=0)Art.typeIcon(g,t2,x+68,ry+19);}panelLine(g,(select+1)+"/"+run.variantCount()+"  2/8: "+Lang.t("chọn","select")+"  5: OK",x+9,y+h-12,w-18,0x80D8FF);}

 private int model(Graphics g,int sp,int form,boolean mega,boolean shiny,int x,int y,int action,int direction,int phase){boolean bounded=form!=0?SpecialFormAtlas.bounds(form,0,0,36,36,action,direction,phase,spriteBounds,shiny):mega?MegaAtlas.bounds(sp,0,0,36,36,action,direction,phase,spriteBounds,shiny):sp>=Data.CORE_N?CollectionAtlas.bounds(Data.collectionIndex(sp),0,0,36,36,action,direction,phase,spriteBounds,shiny):RawAtlas.bounds(sp,0,0,36,36,action,direction,phase,spriteBounds,shiny);int height=bounded?spriteBounds[3]:24,sw=bounded?Math.max(12,Math.min(24,spriteBounds[2])):16;g.setColor(0x345032);g.fillArc(x-sw/2,y-2,sw,5,0,360);int ax=bounded?x-spriteBounds[0]-spriteBounds[2]/2:x-18,ay=bounded?y-spriteBounds[1]-spriteBounds[3]:y-32;boolean drawn=form!=0?SpecialFormAtlas.draw(g,form,ax,ay,36,36,action,direction,phase,shiny):mega?MegaAtlas.draw(g,sp,ax,ay,36,36,action,direction,phase,shiny):sp>=Data.CORE_N?CollectionAtlas.draw(g,Data.collectionIndex(sp),ax,ay,36,36,action,direction,phase,shiny):RawAtlas.draw(g,sp,ax,ay,36,36,action,direction,phase,shiny);if(!drawn)Art.sprite(g,sp,x-12,y-24,24);return height;}
 public void paint(Graphics g){int W=game.W,H=game.H,fh=Art.fh;g.setColor(0x101827);g.fillRect(0,0,W,H);if(run==null){paintIntro(g);return;}int top=header(),sh=Math.max(1,H-top-footer()),vw=Math.min(W,SurvivalRun.WIDTH),vh=Math.min(sh,SurvivalRun.HEIGHT),ox=(W-vw)/2,oy=top+(sh-vh)/2,camX=Math.max(0,Math.min(SurvivalRun.WIDTH-vw,run.renderX()/256-vw/2)),camY=Math.max(0,Math.min(SurvivalRun.HEIGHT-vh,run.renderY()/256-vh/2));
  SurvivalMap.draw(g,ox,oy,vw,vh,camX,camY);int px=ox+run.renderX()/256-camX,py=oy+run.renderY()/256-camY;if(rangeT>0){int radius=run.attackRadius();g.setColor(rangeT>180?0xFFE080:0xACBA74);g.drawArc(px-radius,py-radius,radius*2,radius*2,0,360);g.drawArc(px-radius+1,py-radius+1,radius*2-2,radius*2-2,0,360);}
  for(int i=0;i<SurvivalRun.MAX_DROPS;i++)if(run.dropLife[i]>0){int xx=ox+run.dropX[i]/256-camX,yy=oy+run.dropY[i]/256-camY;if(xx>=ox-16&&xx<ox+vw+16&&yy>=oy-16&&yy<oy+vh+16)Art.itemIconTiny(g,SurvivalShop.ICON[run.dropPart[i]],xx-8,yy-8);}
  for(int i=0;i<SurvivalRun.MAX_FRUIT;i++)if(run.fruitLife[i]>0){int fx=ox+run.fruitX[i]/256-camX,fy=oy+run.fruitY[i]/256-camY;if(run.fruitLife[i]<2000&&(clock/200)%2==0)continue;drawFruit(g,run.fruitKind[i],fx,fy);}
  for(int i=0;i<SurvivalRun.MAX_ENEMIES;i++)if(run.enemySp[i]>=0){int x=ox+run.renderEnemyX(i)/256-camX,y=oy+run.renderEnemyY(i)/256-camY;if(x<-40||x>W+40||y<top-40||y>top+sh+40)continue;int action=run.eflash[i]>0?RawAtlas.HURT:run.eswing[i]>0?RawAtlas.ATTACK:run.emoving[i]?RawAtlas.WALK:RawAtlas.IDLE;int age=action==RawAtlas.IDLE?run.enemyIdle[i]:run.eflash[i]>0?220-run.eflash[i]:220-run.eswing[i];int bodyHeight=model(g,run.enemySp[i],0,false,false,x,y,action,run.edir[i],SurvivalAnimation.clock(action,age,run.etravel[i]));healthBar(g,x-14,y-bodyHeight-9,28,6,run.ehp[i],run.emax[i],run.enemyRole[i]==3?0xD078F0:0xE86060);if(run.target==i){g.setColor(0xFF6060);g.drawArc(x-12,y-3,24,7,0,360);g.drawLine(x-15,y-12,x-10,y-7);g.drawLine(x+15,y-12,x+10,y-7);}if(run.eflash[i]>0)Art.textSmallC(g,"-"+run.lastDamage[i],x,y-bodyHeight-18-(220-run.eflash[i])/35,0xFFF090);}
  if(run.levelFx>0){int age=700-run.levelFx,radius=6+age*64/700;g.setColor(run.levelFx>240?0xFFFFFF:0x80D8FF);g.drawArc(px-radius,py-radius,radius*2,radius*2,0,360);g.drawArc(px-radius-1,py-radius-1,radius*2+2,radius*2+2,0,360);}
  paintGhost(g,ox,oy,camX,camY,px,py);if(run.hp>0){  g.setColor(0xA8F4EF);g.drawArc(px-9,py-2,18,5,0,360);int action=run.hurt>0?RawAtlas.HURT:run.swing>0?RawAtlas.ATTACK:run.moving?RawAtlas.WALK:RawAtlas.IDLE;int age=action==RawAtlas.IDLE?run.idleAge:run.hurt>0?180-run.hurt:run.skillFx>0?500-run.swing:220-run.swing;int bodyHeight=model(g,run.sp,run.form,run.mega,run.shiny,px,py,action,run.dir,SurvivalAnimation.clock(action,age,run.travel));healthBar(g,px-14,py-bodyHeight-9,28,6,run.hp,run.maxHp,0x40CD70);}
  if(run.gearFx>0){int radius=10+(600-run.gearFx)/25;g.setColor(run.gearFxColor);g.drawArc(px-radius,py-18-radius,radius*2,radius*2,0,360);g.drawArc(px-radius+2,py-16-radius,radius*2-4,radius*2-4,0,360);}
  if(run.transformFx>0)Art.megaTransformFx(g,px,py-18,1000-run.transformFx);
  for(int i=0;i<SurvivalRun.MAX_RAYS;i++)if(run.rayLife[i]>0){int rx=ox+run.renderRayX(i)/256-camX,ry=oy+run.renderRayY(i)/256-camY-12;if(rx<-32||rx>W+32||ry<top-32||ry>top+sh+32)continue;int vx=run.rayVX[i],vy=run.rayVY[i],ax=Math.abs(vx),ay=Math.abs(vy),direction=ax>ay*2?(vx>0?2:6):ay>ax*2?(vy>0?0:4):vy>0?(vx>0?1:7):(vx>0?3:5);SurvivalBolt.draw(g,run.rayType[i],direction,run.rayAge[i],rx,ry);if(!run.rayEnemy[i]&&run.rayType[i]>=0)SurvivalElementFx.draw(g,run.rayType[i],run.rayAge[i],rx,ry);}if(run.skillFx>0)for(int z=0;z<run.zoneCount;z++){int sx=ox+run.zoneX[z]/256-camX,sy=oy+run.zoneY[z]/256-camY;int radius=run.skillRadius;g.setColor(run.skillType<0?0xFFFFFF:Data.TCOL[run.skillType]);g.drawArc(sx-radius,sy-radius,radius*2,radius*2,0,360);g.setColor(0xFFFFFF);g.drawArc(sx-radius+3,sy-radius+3,radius*2-6,radius*2-6,0,360);SurvivalSkillFx.draw(g,run.skillSp,sx,sy,run.skillRadius,run.skillAge/75);}
  for(int i=0;i<SurvivalRun.MAX_ENEMIES;i++)if(run.enemySp[i]>=0&&run.warning[i]>0){int wx=ox+run.warnX[i]/256-camX,wy=oy+run.warnY[i]/256-camY;g.setColor((run.warning[i]/100)%2==0?0xFF6050:0xFFD070);int radius=run.bossRadius(i);g.drawArc(wx-radius,wy-radius,radius*2,radius*2,0,360);g.setColor(Data.TCOL[Data.t1[run.enemySp[i]]]);g.drawArc(wx-radius+2,wy-radius+2,radius*2-4,radius*2-4,0,360);g.drawLine(wx-8,wy,wx+8,wy);g.drawLine(wx,wy-8,wx,wy+8);}for(int i=0;i<SurvivalRun.MAX_DEATHS;i++)if(run.deathLife[i]>0){int fx=ox+run.deathX[i]/256-camX,fy=oy+run.deathY[i]/256-camY;Art.spawnFx(g,fx-24,fy-40,run.deathLife[i]);}if(run.dashFx>0){int fx=ox+run.dashX/256-camX,fy=oy+run.dashY/256-camY;g.setColor(0xA0EDFF);g.drawArc(fx-12,fy-18,24,24,0,360);g.drawArc(px-12,py-18,24,24,0,360);}paintBossSkills(g,ox,oy,camX,camY);paintHeader(g);

  if(run.goldFx>0){int gx=ox+run.goldX/256-camX,gy=oy+run.goldY/256-camY-28-(650-run.goldFx)/50;Art.textCompact(g,"+$"+run.lastGold,gx,gy,0xFFD040);}paintPetPanels(g);

  int buffX=8;for(int i=0;i<4;i++)if(run.buffTime[i]>0){drawFruit(g,i,buffX+5,top+8);Art.textSmall(g,""+((run.buffTime[i]+999)/1000),buffX+13,top+2,0xFFFFFF);buffX+=36;}if(messageT>0||run.noticeT>0){g.setColor(0x142132);g.fillRect(0,top+18,W,Art.compactHeight()+6);Art.textCompact(g,messageT>0?message:run.notice,(W-Art.compactWidth(messageT>0?message:run.notice))/2,top+21,0xFFD070);}if(!started)paintIntro(g);else if(summary)paintSummary(g);else if(exitAsk)paintExit(g);else if(paused)paintPause(g);else if(run.variantPending>0)paintVariant(g);else if(run.elementPending)paintElement(g);else if(buffAsk)paintBuffConfirm(g);else if(run.pendingLevels>0)paintChoices(g);
 }
 private int elementWidth(){return Math.min(game.W-16,280);}
 private int elementTop(){return Math.max(header()+3,(game.H-footer()-(47+run.elementCount()*34))/2);}
 private void paintElement(Graphics g){int w=elementWidth(),x=(game.W-w)/2,y=elementTop(),h=47+run.elementCount()*34;g.setClip(0,0,game.W,game.H);Art.box(g,x,y,w,h,0x101B2C,0x59728E);g.setColor(0x21364F);g.fillRect(x+1,y+1,w-2,23);Art.textCompact(g,Lang.t("CẤP 2 · CHỌN HỆ CHIÊU","LEVEL 2 · CHOOSE ELEMENT"),x+9,y+8,0xFFFFFF);for(int i=0;i<run.elementCount();i++){int type=i==0?run.type1():run.type2(),ry=y+29+i*34;g.setColor(select==i?0x304A68:0x19293D);g.fillRect(x+7,ry,w-14,29);g.setColor(select==i?0xFFFFFF:0x40536A);g.drawRect(x+7,ry,w-15,28);Art.typeIcon(g,type,x+14,ry+6);Art.textCompact(g,Lang.typeName(type),x+38,ry+6,0xFFFFFF);Art.textCompact(g,Lang.t("Chiêu hệ ","Element: ")+Lang.typeName(type),x+38,ry+17,0x9ACBE7);if(select==i){g.setColor(Data.TCOL[type]);g.fillRect(x+8,ry+1,3,27);Art.textCompact(g,"5",x+w-24,ry+10,0xFFE080);}}Art.textCompact(g,Lang.t("2/8: chọn   5: xác nhận","2/8: select   5: confirm"),x+9,y+h-12,0x80D8FF);}
 private void paintBossSkills(Graphics g,int ox,int oy,int camX,int camY){for(int i=0;i<SurvivalRun.MAX_ENEMIES;i++)if(run.bossFxLife[i]>0){int x=ox+run.bossFxX[i]/256-camX,y=oy+run.bossFxY[i]/256-camY;SurvivalSkillFx.draw(g,run.bossFxSp[i],x,y,run.bossFxRadius[i],(650-run.bossFxLife[i])/75);}}
 private void paintIntro(Graphics g){int W=game.W,H=game.H,fh=Art.fh;Art.box(g,5,5,W-10,H-10,0x111B2D,0xFFE060);Art.textBC(g,Lang.t("POKEMON NỔI LOẠN","POKEMON UPRISING"),W/2,12,0xFFE060);if(hero>=0){Art.avatar(g,run.sp,12,fh+24);Art.textB(g,run.name(),50,fh+26,0xFFFFFF);}String text=Lang.t("Giữ hướng để đi, bấm 5 bắn cùng lúc. Nhấn đúp hướng để lướt.\n*: đổi mục tiêu. #: tuyệt kỹ (hồi 30 giây). R/0: tạm dừng.\nLv 5/10: tự tiến hóa; chiêu nâng ở 5/10/15.\nLên cấp hồi đầy Máu/MP, chọn 1 buff. Mega từ Lv 15, Shiny từ Lv 12.\nNhặt quả để nhận buff ngắn.\nThua: 1 \uE000/5 KO +1/đợt hoàn thành.","Hold directions and press 5 to fire. Double-tap a direction to blink.\n*: target. #: ultimate (30s cooldown). R/0: pause.\nLv 5/10: evolve; skills upgrade at 5/10/15.\nLevel up restores HP/MP; choose a buff. Mega Lv 15, Shiny Lv 12.\nCollect fruit for temporary buffs.\nReward: 1 \uE000/5 KOs +1/cleared wave.");Art.para(g,text,12,fh+65,W-24,0xB0D0EE,Math.max(1,(H-fh*3-78)/fh));Art.textSmallC(g,Lang.t("5: bắt đầu · R/0: đổi pet","5: start · R/0: change pet"),W/2,H-fh-12,0x80D8FF);}
 private int choiceRow(){return 34;}
 private int choiceTop(){return Math.max(4,(game.H-149)/2);}
 private void paintChoices(Graphics g){int w=Math.min(game.W-16,300),x=(game.W-w)/2,y=choiceTop();Art.box(g,x,y,w,149,0x101B2C,0x59728E);g.setColor(0x21364F);g.fillRect(x+1,y+1,w-2,23);Art.textCompact(g,Lang.t("LÊN CẤP ","LEVEL UP ")+run.level,x+9,y+8,0xFFE080);for(int i=0;i<3;i++){int ry=y+29+i*choiceRow();g.setColor(i==select?0x304A68:0x19293D);g.fillRect(x+7,ry,w-14,29);g.setColor(i==select?0xFFFFFF:0x40536A);g.drawRect(x+7,ry,w-15,28);g.setClip(x+12,ry+3,w-24,25);Art.textCompact(g,run.choiceName(run.choices[i]),x+14,ry+10,0xFFFFFF);g.setClip(0,0,game.W,game.H);}Art.textCompact(g,Lang.t("2/8: chọn   5: xác nhận","2/8: select   5: confirm"),x+9,y+137,0x80D8FF);}
 private void paintBuffConfirm(Graphics g){int h=135,y=modalY(h),x=(game.W-modalWidth())/2;modal(g,Lang.t("NHẬN BUFF NÀY?","TAKE THIS BUFF?"),h);panelLine(g,run.choiceName(run.choices[buffIndex]),x+9,y+29,modalWidth()-18,0xFFFFFF);card(g,0,y+49,29,Lang.t("Không, chọn lại","No, go back"));card(g,1,y+83,29,Lang.t("Có, nhận buff","Yes, take buff"));panelLine(g,Lang.t("5: xác nhận   R/0: quay lại","5: confirm   R/0: back"),x+9,y+123,modalWidth()-18,0x80D8FF);}
 private void paintPause(Graphics g){int h=115,y=modalY(h),x=(game.W-modalWidth())/2;modal(g,Lang.t("TẠM DỪNG","PAUSED"),h);card(g,0,y+29,29,Lang.t("Tiếp tục","Continue"));card(g,1,y+63,29,Lang.t("Kết thúc lượt","End attempt"));panelLine(g,Lang.t("5: chọn   R/0: tiếp tục","5: select   R/0: resume"),x+9,y+103,modalWidth()-18,0x80D8FF);}
 private void paintExit(Graphics g){int h=135,y=modalY(h),x=(game.W-modalWidth())/2;modal(g,Lang.t("KẾT THÚC LƯỢT?","END ATTEMPT?"),h);panelLine(g,Lang.t("Nhận \uE000; buff không lưu.","Claim \uE000; buffs not saved."),x+9,y+29,modalWidth()-18,0x9ACBE7);card(g,0,y+49,29,Lang.t("Tiếp tục","Continue"));card(g,1,y+83,29,Lang.t("Tổng kết","Summary"));panelLine(g,Lang.t("5: chọn   R/0: quay lại","5: select   R/0: back"),x+9,y+123,modalWidth()-18,0x80D8FF);}
 private void paintSummary(Graphics g){int h=186,y=modalY(h),w=modalWidth(),x=(game.W-w)/2;modal(g,Lang.t("TỔNG KẾT NỔI LOẠN","UPRISING SUMMARY"),h);panelLine(g,run.hp<=0?Lang.t("Pokémon đã gục","Pokemon fainted"):Lang.t("Đã kết thúc lượt","Attempt ended"),x+9,y+29,w-18,0x9ACBE7);panelLine(g,Lang.t("Đợt: ","Waves: ")+run.completedWaves+"   KO: "+run.kills,x+9,y+44,w-18,0xFF9090);panelLine(g,"Boss: "+run.bossKills+"   $"+run.gold,x+9,y+59,w-18,0xFFD040);int sec=run.elapsed/1000;panelLine(g,Lang.t("Cấp: ","Level: ")+run.level+"   "+sec/60+":"+(sec%60<10?"0":"")+sec%60,x+9,y+74,w-18,0xFFFFFF);Art.textSmall(g,"+",x+9,y+92,0x80E8A0);BallArt.amount(g,BallArt.NORMAL,paidReward,x+23,y+92,0x80E8A0);card(g,0,y+111,25,Lang.t("Chơi lại","Retry"));card(g,1,y+141,25,Lang.t("Về khám phá","Explore"));panelLine(g,Lang.t("2/8: chọn   5: xác nhận","2/8: select   5: confirm"),x+9,y+174,w-18,0x80D8FF);}
}
