package pac;
import javax.microedition.lcdui.Graphics;

/** Paused stats and unified equipment shop. Column selection is also touch hover. */
public final class SurvivalShopScreen extends Screen {
 private final SurvivalScreen parent;private final SurvivalRun run;
 private final SurvivalGearIcons icons=new SurvivalGearIcons(),equippedIcons=new SurvivalGearIcons();
 private int tab=1,area=1,index,lastTouch=-1,clock,messageT;private String message="",lastTitle="",lastBody="";
 public SurvivalShopScreen(Game g,SurvivalScreen p,SurvivalRun r){super(g);parent=p;run=r;index=r.shop.plannedGear>=0?r.shop.plannedGear:0;}
 public void update(int dt){clock=(clock+Math.max(0,Math.min(250,dt)))%3600000;messageT=Math.max(0,messageT-dt);}
 private int listTop(){return 84;}
 private int rows(){return Math.max(1,(game.H-24-listTop())/20);}
 private int columnWidth(){return (game.W*60/100-14)/2;}
 private int columnX(int c){return 4+c*(columnWidth()+8);}
 private int detailX(){return game.W*60/100;}
 private int first(int c){if(c==0&&selectedGear()>=0){int gear=selectedGear(),lo=Math.min(SurvivalShop.A[gear],SurvivalShop.B[gear]),hi=Math.max(SurvivalShop.A[gear],SurvivalShop.B[gear]);return Math.max(0,Math.min(lo,hi-rows()+1));}return UiLayout.firstVisible(area==c?index:c==1&&area==-1?Math.max(0,selectedGear()):0,c==0?SurvivalShop.PARTS:SurvivalShop.GEARS,rows());}
 private void select(int a,int i){if(area!=a||index!=i){clock=0;messageT=0;lastTouch=-1;}area=a;index=i;}
 private void tell(boolean ok){message=ok?Lang.t("Thành công!","Done!"):Lang.t("Thiếu vàng, trùng đồ hoặc túi đầy.","Not enough gold, duplicate gear or full bag.");messageT=1500;lastTouch=-1;}
 private void act(){if(tab==0){tell(run.shop.upgrade(run,index));return;}if(area==-1)sell();else if(area==0)tell(run.shop.buyAndEquip(run,SurvivalShop.GEARS+index));else tell(run.shop.buyAndEquip(run,index));}
 private void plan(){if(tab==1&&area==1){run.shop.plan(index);lastTouch=-1;}}
 private void sell(){if(tab!=1)return;int target=area==-1?run.shop.slots[index]:area==0?SurvivalShop.GEARS+index:index;tell(run.shop.sell(run,target,area==-1?index:-1));}
 public void key(int k){if(k==Game.K_0||k==Game.K_SOFT2){parent.resumeArena();game.setScreen(parent);return;}if(k==Game.K_STAR){parent.endFromShop();game.setScreen(parent);return;}if(k==Game.K_7||k==Game.K_9){tab=1-tab;select(tab==0?0:1,0);return;}if(k==Game.K_POUND){plan();return;}if(k==Game.K_3){sell();return;}if(k==Game.K_FIRE||k==Game.K_SOFT1){act();return;}if(k==Game.K_LEFT||k==Game.K_RIGHT){if(tab==1){int a=area==-1?-1:1-area;select(a,Math.min(index,a==-1?5:a==0?5:SurvivalShop.GEARS-1));}return;}if(k==Game.K_UP){if(tab==1&&index==0&&area>=0)select(-1,0);else select(area,Math.max(0,index-1));}else if(k==Game.K_DOWN){if(tab==1&&area==-1)select(1,0);else select(area,Math.min(tab==0?4:area==0?SurvivalShop.PARTS-1:SurvivalShop.GEARS-1,index+1));}}
 private boolean confirm(int id){boolean ready=id==lastTouch;lastTouch=id;return ready;}
 public boolean pointer(int x,int y){int W=game.W,H=game.H;if(x<0||y<0||x>=W||y>=H)return true;if(y>=H-24){key(x<W/2?Game.K_0:Game.K_STAR);return true;}if(y>=22&&y<40){tab=x<W/2?0:1;select(tab==0?0:1,tab==1&&run.shop.plannedGear>=0?run.shop.plannedGear:0);return true;}
  if(tab==0){int i=SurvivalShopLayout.hitStat(x,y,W,H,index);if(i>=0){boolean ready=area==0&&index==i&&confirm(100+i);select(0,i);lastTouch=100+i;if(ready)act();}return true;}
  if(y>=44&&y<44+Math.min(26,SurvivalShopLayout.cell(W,H))){for(int i=0;i<6;i++){int size=Math.min(26,SurvivalShopLayout.cell(W,H)),xx=(W-(size*6+15))/2+i*(size+3);if(x>=xx&&x<xx+size){select(-1,i);lastTouch=200+i;return true;}}}
  if(x>=detailX()+3&&x< W-7&&y>=H-83){int delta=y-(H-83);if(delta<17)plan();else if(delta>=19&&delta<36&&area>=0)act();else if(delta>=38&&delta<55){if(confirm(900+area*100+index))sell();};return true;}
  for(int c=0;c<2;c++){int xx=columnX(c),w=columnWidth(),count=c==0?SurvivalShop.PARTS:SurvivalShop.GEARS;if(x>=xx+w-10&&x<xx+w){if(y>=73&&y<83&&first(c)>0){select(c,Math.max(0,first(c)-1));return true;}if(y>=H-34&&y<H-24&&first(c)+rows()<count){select(c,Math.min(count-1,first(c)+rows()));return true;}}}
  if(y>=listTop()&&y<H-24&&(y-listTop())%20<19){for(int c=0;c<2;c++){int xx=columnX(c),w=columnWidth();if(x>=xx&&x<xx+w){int i=first(c)+(y-listTop())/20;if(i<(c==0?SurvivalShop.PARTS:SurvivalShop.GEARS)){boolean ready=area==c&&index==i&&confirm(300+c*100+i);select(c,i);lastTouch=300+c*100+i;if(ready)act();}return true;}}}return true;
 }
 private void text(Graphics g,String s,int x,int y,int w,int color,boolean scroll){g.setClip(x,y,Math.max(1,w),10);int offset=scroll?SurvivalShopLayout.marqueeOffset(Art.compactWidth(s),w,clock):0;Art.textCompact(g,s,x-offset,y,color);g.setClip(0,0,game.W,game.H);}
 private void box(Graphics g,String s,int x,int y,int w,int color){Art.box(g,x,y,w,17,color,0x526A85);text(g,s,x+3,y+4,w-6,0xFFFFFF,false);}
 private void lock(Graphics g,int x,int y){g.setColor(0xFFD040);g.drawArc(x+1,y,5,6,0,180);g.fillRect(x,y+4,8,6);g.setColor(0x403010);g.drawLine(x+4,y+6,x+4,y+8);}
 private void paintStats(Graphics g){int W=game.W,H=game.H;Art.box(g,4,44,W-8,62,0x192B40,0x526A85);PetAvatar.draw(g,run.sp,run.form,run.mega,run.shiny,8,49,28);text(g,Lang.t("Cấp ","Lv ")+run.level,8,82,30,0xFFD070,false);text(g,run.name(),42,48,W-50,0xFFFFFF,true);int split=42+(W-50)/2,width=(W-50)/2;text(g,Lang.t("Máu ","HP ")+run.hp+"/"+run.maxHp,42,60,width,0x80E0A0,false);text(g,"MP "+run.mana+"/"+run.maxMana,split,60,width,0x90C8FF,false);text(g,Lang.t("Công ","ATK ")+run.atk,42,70,width,0xCCDCEF,false);text(g,Lang.t("Giáp ","Armor ")+run.def,split,70,width,0xCCDCEF,false);text(g,Lang.t("Kháng ","Resist ")+run.specialDefense,42,80,width,0xCCDCEF,false);text(g,Lang.t("Tốc ","Speed ")+run.speed,split,80,width,0xCCDCEF,false);text(g,Lang.t("Tầm ","Range ")+run.range,42,90,width,0xCCDCEF,false);text(g,Lang.t("Chí mạng ","Crit ")+run.criticalChance+"%",split,90,width,0xCCDCEF,false);
  Art.box(g,4,106,W-8,16,0x192B40,0x526A85);text(g,Lang.t("Ulti +","Ultimate +")+run.ultimateBonusPercent()+"% · CD "+(run.shop.ultiCooldown()/1000)+"s · "+Lang.t("Khiên ","Shield ")+run.shield,9,110,W-18,0xFFD070,true);
  int row=SurvivalShopLayout.statsRow(H),first=SurvivalShopLayout.statsFirst(index,H),visible=SurvivalShopLayout.statsVisible(H);for(int r=0;r<visible&&first+r<5;r++){int i=first+r,y=SurvivalShopLayout.statsTop(H)+r*row,rank=run.shop.ranks[i],cost=run.shop.price(i),amount=i==0?20:i==4?5:2;Art.box(g,4,y,W-8,row-2,index==i?0x304D70:0x192B40,index==i?0xFFFFFF:0x526A85);String price=cost<0?"MAX":"$"+cost;int pw=Art.compactWidth(price);text(g,SurvivalShop.statName(i)+" +"+amount+"  "+rank+"/10",9,y+2,W-27-pw,0xFFFFFF,false);text(g,price,W-9-pw,y+2,pw+1,cost<0||run.gold>=cost?0xFFD070:0x93AAC5,false);Art.bar(g,9,y+row-4,W-18,1,rank,10,0x70DCA0);}
 }
 private static String quantity(int n){return n>0?"x"+n+" ":"";}
 private int wrapEnd(String s,int start,int width){int end=start;while(end<s.length()&&Art.compactWidth(s.substring(start,end+1))<=width)end++;if(end==start)return Math.min(s.length(),start+1);if(end<s.length()){int space=s.lastIndexOf(' ',end);if(space>start)end=space;}return end;}
 private void wrapped(Graphics g,String s,int x,int y,int width,int height){int count=0,pos=0;while(pos<s.length()){pos=wrapEnd(s,pos,width);while(pos<s.length()&&s.charAt(pos)==' ')pos++;count++;}int visible=height<7?0:1+(height-7)/10;if(visible<=0)return;int first=count<=visible?0:Math.max(0,(clock/3000)%(count-visible+3)-1);first=Math.min(first,Math.max(0,count-visible));pos=0;for(int line=0;pos<s.length();line++){int end=wrapEnd(s,pos,width);if(line>=first&&line<first+visible)text(g,s.substring(pos,end),x,y+(line-first)*10,width,0xCCDCEF,false);pos=end;while(pos<s.length()&&s.charAt(pos)==' ')pos++;}if(count>visible){g.setColor(0x90D4F0);g.fillRect(x+width-2,y,2,Math.max(2,height*visible/count));}}
 private int selectedGear(){int gear=area==1?index:area==-1?run.shop.slots[index]:-1;return gear<SurvivalShop.GEARS?gear:-1;}
 private String title(){if(tab==0)return SurvivalShop.statName(index);int gear=selectedGear();if(area==-1&&run.shop.slots[index]>=SurvivalShop.GEARS)return ItemData.name(SurvivalShop.ICON[run.shop.slots[index]-SurvivalShop.GEARS]);return area==0?ItemData.name(SurvivalShop.ICON[index]):gear<0?Lang.t("Ô trống","Empty slot"):SurvivalShop.gearName(gear);}
 private String body(){if(messageT>0)return message;if(tab==0){int value=index==0?run.maxHp:index==1?run.atk:index==2?run.def:index==3?run.specialDefense:run.speed;return Lang.t("Hiện tại: ","Current: ")+value+"\n"+run.shop.ranks[index]+"/10 · $"+run.shop.price(index);}if(area==0||area==-1&&run.shop.slots[index]>=SurvivalShop.GEARS){int p=area==0?index:run.shop.slots[index]-SurvivalShop.GEARS;return Lang.t("Chỉ số: ","Stats: ")+SurvivalShop.componentStats(p)+"\n"+Lang.t("Nội tại: Không có.","Passive: None.");}int gear=selectedGear();return gear<0?"":SurvivalShop.gearDesc(gear);}
 private void description(Graphics g){int x=detailX(),w=game.W-x-4,y=84,h=game.H-24-y;Art.box(g,x,y,w,h,0x192B40,0x526A85);String title=title(),body=body();if(!title.equals(lastTitle)||!body.equals(lastBody)){clock=0;lastTitle=title;lastBody=body;}text(g,title,x+4,y+5,w-8,0xFFD070,true);int split=body.indexOf('\n');text(g,split<0?body:body.substring(0,split),x+4,y+19,w-8,0xCCDCEF,true);if(split>=0)wrapped(g,body.substring(split+1),x+4,y+31,w-8,Math.max(0,game.H-86-(y+31)));
  if(tab==1){int by=game.H-83;box(g,area==1?(run.shop.plannedGear==index?Lang.t("Hủy soạn","Cancel plan"):Lang.t("Soạn đồ","Plan")):"",x+3,by,w-6,run.shop.plannedGear==index&&area==1?0x665020:0x304D70);if(area==1&&run.shop.plannedGear==index){g.setColor(0xFFD040);g.drawRect(x+3,by,w-7,16);lock(g,x+w-15,by+3);}int cost=area==1?run.shop.remainingPrice(index):area==0?15:0;box(g,area==-1?"":Lang.t("Mua $","Buy $")+cost,x+3,by+19,w-6,run.gold>=cost?0x305C46:0x304D70);int target=area==-1?run.shop.slots[index]:area==0?SurvivalShop.GEARS+index:index;box(g,target>=0?(lastTouch==900+area*100+index?Lang.t("Xác nhận $","Confirm $"):Lang.t("Bán $","Sell $"))+run.shop.sellPrice(target):"",x+3,by+38,w-6,0x304D70);}
 }
 public void paint(Graphics g){int W=game.W,H=game.H;g.setColor(0x101827);g.fillRect(0,0,W,H);text(g,Lang.t("TẠM DỪNG","PAUSED"),5,6,W-85,0xFFD070,false);text(g,"$"+run.gold,W-75,6,70,0xFFD070,false);if(tab==0&&messageT>0)text(g,message,90,6,W-170,0xFFD070,true);for(int i=0;i<2;i++)box(g,i==0?Lang.t("Chỉ số","Stats"):"Shop",i*W/2,22,W/2,tab==i?0x304D70:0x192B40);
  if(tab==0)paintStats(g);
  else{int size=Math.min(26,SurvivalShopLayout.cell(W,H));for(int i=0;i<6;i++){int xx=(W-(size*6+15))/2+i*(size+3),gear=run.shop.slots[i];Art.box(g,xx,44,size,size,0x091320,area==-1&&index==i?0xFFFFFF:0x526A85);if(gear>=0){int cd=run.gearCooldownRemaining(gear);equippedIcons.draw(g,gear,xx+1,45,size-2,cd!=0);if(cd!=0)text(g,cd<0?"X":""+((cd+999)/1000),xx+2,44+size-10,size-4,0xFFD070,false);}}
   for(int c=0;c<2;c++){int xx=columnX(c),w=columnWidth(),f=first(c),count=c==0?SurvivalShop.PARTS:SurvivalShop.GEARS;text(g,c==0?Lang.t("Mảnh","Parts"):Lang.t("Trang bị","Gear"),xx,73,w,0x90D4F0,false);for(int r=0;r<rows()&&f+r<count;r++){int i=f+r,yy=listTop()+r*20;Art.box(g,xx,yy,w,19,area==c&&index==i?0x304D70:0x192B40,0x30445C);if(c==0)Art.itemIconMedium(g,SurvivalShop.ICON[i],xx+1,yy+1);else icons.draw(g,i,xx+1,yy+1,17,false);text(g,c==0?ItemData.name(SurvivalShop.ICON[i]):SurvivalShop.gearName(i),xx+20,yy+1,w-22-(c==1&&run.shop.plannedGear==i?10:0),0xFFFFFF,area==c&&index==i);text(g,quantity(c==0?run.shop.parts[i]:run.shop.bag[i])+"$"+(c==0?15:run.shop.remainingPrice(i)),xx+20,yy+10,w-22,0xFFD070,false);if(c==1&&run.shop.plannedGear==i){g.setColor(0xFFD040);g.drawRect(xx,yy,w-1,18);lock(g,xx+w-10,yy+3);}}if(f>0)text(g,"^",xx+w-8,73,8,0xFFD070,false);if(f+rows()<count)text(g,"v",xx+w-8,H-34,8,0xFFD070,false);}
   if(selectedGear()>=0){int gear=selectedGear(),root=listTop()+(gear-first(1))*20+9,gap=columnX(1)-4;g.setClip(0,listTop(),detailX(),Math.max(1,H-24-listTop()));g.setColor(0xFFFFFF);for(int n=0;n<2;n++){int part=n==0?SurvivalShop.A[gear]:SurvivalShop.B[gear],r=part-first(0);if(r>=0&&r<rows()){int yy=listTop()+r*20+9;g.drawLine(columnX(0)+columnWidth()-1,yy,gap,yy);g.drawLine(gap,yy,gap,root);g.drawLine(gap,root,columnX(1),root);}}}else if(area==0){int yy=listTop()+(index-first(0))*20+9,gap=columnX(1)-4;g.setClip(0,listTop(),detailX(),Math.max(1,H-24-listTop()));g.setColor(0xFFFFFF);for(int r=0;r<rows()&&first(1)+r<SurvivalShop.GEARS;r++){int gear=first(1)+r;if(SurvivalShop.A[gear]==index||SurvivalShop.B[gear]==index){int root=listTop()+r*20+9;g.drawLine(columnX(0)+columnWidth()-1,yy,gap,yy);g.drawLine(gap,yy,gap,root);g.drawLine(gap,root,columnX(1),root);}}}g.setClip(0,0,W,H);description(g);
  }
  g.setColor(0x0B1422);g.fillRect(0,H-24,W,24);text(g,Lang.t("7/9: tab  2/8: chọn  5: mua  3: bán  #: soạn","7/9: tab  2/8: select  5: buy  3: sell  #: plan"),4,H-23,W-8,0x91BBD8,false);text(g,Lang.t("0: tiếp tục","0: resume"),4,H-11,W/2-8,0x80E0A0,false);text(g,Lang.t("*: kết thúc","*: end"),W/2+4,H-11,W/2-8,0xFF9090,false);
 }
}
