package pac;

/** Movement, map navigation and caught-list regression checks. */
public final class Explore181Test {
 private static void check(boolean b,String m){if(!b)throw new RuntimeException(m);}
 public static void run(){
  ExploreMotion anim=new ExploreMotion(3,3);byte[] free=new byte[100];int[] none=new int[0];int startX=anim.x;anim.update(20,1,0,free,10,10,none,none,0);check(anim.moving&&anim.dir==2&&anim.renderX()==startX,"walk state/facing/interpolation mismatch");anim.update(10,1,0,free,10,10,none,none,0);check(anim.moving&&anim.renderX()==startX+10,"substep frame lost WALK or interpolation");long travel=anim.travel;anim.update(30,0,0,free,10,10,none,none,0);check(!anim.moving&&anim.travel==travel&&anim.idleAge==40,"idle anim advances travel");anim.reset();check(anim.renderX()==anim.x&&!anim.moving,"reset left interpolation drift");int oldAvatar=Save.profileAvatarDex;int later=-1;for(int s=Data.CORE_N;s<Data.N;s++)if(Data.isBase(s)&&Data.generation(s)==4){later=s;break;}check(later>=0,"Gen4 actor absent");int family=Data.fam[later];boolean owned=Save.unlocked[family];Save.unlocked[family]=true;Save.profileAvatarDex=Data.nationalDex(later);check(WorldScreen.profileSpecies()==later,"profile actor lost later-gen dex mapping");Save.profileAvatarDex=oldAvatar;Save.unlocked[family]=owned;
  byte[] open=new byte[100];int[] empty=new int[0];ExploreMotion a=new ExploreMotion(3,3),b=new ExploreMotion(3,3);for(int i=0;i<50;i++)a.update(20,1,0,open,10,10,empty,empty,0);for(int i=0;i<10;i++)b.update(100,1,0,open,10,10,empty,empty,0);check(a.x==b.x&&a.y==b.y&&a.x==3*256+128+1000,"movement depends on render cadence");ExploreMotion diagonal=new ExploreMotion(3,3);diagonal.update(100,1,1,open,10,10,empty,empty,0);check(diagonal.x-3*256-128==70&&diagonal.y-3*256-128==70,"diagonal speed not normalized");
  open[3*10+5]=WorldScreen.T_TREE;a=new ExploreMotion(3,3);for(int i=0;i<30;i++)a.update(100,1,0,open,10,10,empty,empty,0);check(a.x+72<5*256,"crossed tree collision");a.update(100,0,1,open,10,10,empty,empty,0);check(a.y>3*256+128,"blocked actor could not slide/move away");
  int[] wx={4},wy={3};a=new ExploreMotion(3,3);for(int i=0;i<20;i++)a.update(100,1,0,new byte[100],10,10,wx,wy,1);check(a.x<4*256+128-143,"overlapped wild Pokemon");a.reset();int x=a.x;a.update(100,0,0,open,10,10,empty,empty,0);check(a.x==x&&!a.moving,"released motion drifted");
  for(int gen=1;gen<=9;gen++){int w=56,h=44;byte[] tiles=new byte[w*h],zones=new byte[w*h];ExploreMapLayout.build(tiles,zones,w,h,gen);boolean[] seen=new boolean[w*h];int[] queue=new int[w*h];int head=0,tail=0,start=h/2*w+w/2;queue[tail++]=start;seen[start]=true;while(head<tail){int p=queue[head++],xx=p%w,yy=p/w;for(int d=0;d<4;d++){int nx=xx+(d==0?1:d==1?-1:0),ny=yy+(d==2?1:d==3?-1:0);if(!ExploreMapLayout.walkable(tiles,w,h,nx,ny))continue;int q=ny*w+nx;if(!seen[q]){seen[q]=true;queue[tail++]=q;}}}int walk=0;boolean[] reachableZones=new boolean[4];for(int i=0;i<tiles.length;i++){if(ExploreMapLayout.walkable(tiles,w,h,i%w,i/w))walk++;if(seen[i])reachableZones[zones[i]]=true;}check(tail*100/walk>=75,"too many disconnected walkable cells");for(int z=0;z<4;z++)check(reachableZones[z],"unreachable encounter zone");}
  int[] signatures=new int[9];for(int gen=1;gen<=9;gen++){byte[] tiles=new byte[56*44],zones=new byte[tiles.length];ExploreMapLayout.build(tiles,zones,56,44,gen);int sig=1;for(int i=0;i<tiles.length;i++)sig=sig*31+tiles[i]*5+zones[i];for(int prev=0;prev<gen-1;prev++)check(sig!=signatures[prev],"reused map layout for Gen "+gen);signatures[gen-1]=sig;}
  int[] backup=new int[Save.exploreSpeciesCaught.length];System.arraycopy(Save.exploreSpeciesCaught,0,backup,0,backup.length);for(int i=0;i<backup.length;i++)Save.exploreSpeciesCaught[i]=0;Save.exploreSpeciesCaught[0]=2;Save.exploreSpeciesCaught[1]=1;Save.exploreSpeciesCaught[151]=3;check(ExploreCaught.count(1)==2&&ExploreCaught.count(2)==1&&ExploreCaught.at(1,0)==0&&ExploreCaught.at(1,1)==1&&ExploreCaught.at(1,-1)==-1,"caught list lost duplicate counts / generation filtering");System.arraycopy(backup,0,Save.exploreSpeciesCaught,0,backup.length);
  for(int gen=1;gen<=9;gen++){int count=0,ordinary=0;for(int sp=0;sp<Data.N;sp++)if(Data.isBase(sp)&&Data.generation(sp)==gen){count++;if(Data.category[sp]!=6)ordinary++;check(ExploreRules.gen(sp)==gen,"later-gen filter mismatch");}check(count==ExploreRules.mapSpeciesCount(gen)&&ordinary>0,"empty/wrong capture generation");check(Save.exploreMapCaught.length>=gen&&Save.exploreQuestCaught.length>=gen*Data.NT,"save capacity missing generation");for(int type=0;type<18;type++){int sp=ExploreRules.legendaryForType(gen,type);if(sp>=0)check(Data.generation(sp)==gen,"legend from wrong generation");}}
  System.out.println("Explore181Test OK: fixed-step free movement, diagonals, blockers, wild collision, nine connected regional map slots and caught-list counts");
 }
 public static void main(String[] args){System.out.print("{\"columns\":56,\"rows\":44,\"tilePixels\":20,\"tileset\":\"res/map/explore-20.png\",\"pipeline\":\"tile_mode / project-native / tile_collision\",\"sceneHooks\":{\"playerSpawn\":{\"tileX\":28,\"tileY\":22},\"exit\":\"0 opens trip summary\",\"encounters\":\"walkable cells, region zone IDs 0-3\"},\"collision\":{\"walkableTiles\":[0,1,2,3],\"blockers\":[4,5,6,7],\"actorRadiusTiles\":0.28125},\"regions\":[");for(int gen=1;gen<=9;gen++){if(gen>1)System.out.print(",");byte[] t=new byte[56*44],z=new byte[t.length];ExploreMapLayout.build(t,z,56,44,gen);System.out.print("{\"generation\":"+gen+",\"tiles\":[");for(int y=0;y<44;y++){if(y>0)System.out.print(",");System.out.print("[");for(int x=0;x<56;x++){if(x>0)System.out.print(",");System.out.print(t[y*56+x]);}System.out.print("]");}System.out.print("],\"zones\":[");for(int y=0;y<44;y++){if(y>0)System.out.print(",");System.out.print("[");for(int x=0;x<56;x++){if(x>0)System.out.print(",");System.out.print(z[y*56+x]);}System.out.print("]");}System.out.print("]}");}System.out.print("]}");}
}
