package pac;
import javax.microedition.lcdui.Graphics;
/** Pure geometry, touch state, balance and bounded desktop simulation checks. */
public final class ReleasePolishTest {
 private static void check(boolean b,String m){if(!b)throw new RuntimeException(m);}
 private static final class TouchProbe extends Screen {TouchProbe(){super(null);}public void update(int dt){}public void paint(Graphics g){}public void key(int k){}boolean tap(int n){return confirmTouch(n);}}
 private static int rays(SurvivalRun r,boolean enemy){int n=0;for(int i=0;i<SurvivalRun.MAX_RAYS;i++)if(r.rayLife[i]>0&&r.rayEnemy[i]==enemy)n++;return n;}
 private static void target(SurvivalRun r,int slot,int dx,int dy,int role){r.enemySp[slot]=0;r.ehp[slot]=r.emax[slot]=100000000;r.ex[slot]=r.prevEx[slot]=r.x+dx*256;r.ey[slot]=r.prevEy[slot]=r.y+dy*256;r.enemyRole[slot]=role;r.ecool[slot]=0;r.edamage[slot]=5;}
 public static void run(){
  int[] widths={176,240,241,320,360,640};for(int n=0;n<widths.length;n++){int w=widths[n],fh=12,left=GachaControls.ballLeft(w),cell=GachaControls.ballWidth(w);for(int i=0;i<3;i++){check(GachaControls.ballAt(left+i*cell,fh+3,w,fh)==i,"ball left edge");check(GachaControls.ballAt(left+(i+1)*cell-1,fh+16,w,fh)==i,"ball right edge");}check(GachaControls.ballAt(left-1,fh+3,w,fh)==-1&&GachaControls.ballAt(w,fh+3,w,fh)==-1,"ball outside");for(int i=0;i<4;i++)check(GachaControls.actionAt(w*i/4,310,w,320,fh)==i,"action draw/hit mismatch");check(GachaControls.actionAt(-1,310,w,320,fh)==-1,"outside action");}
  TouchProbe p=new TouchProbe();check(!p.tap(1)&&p.tap(1),"two-tap confirmation");check(!p.tap(1)&&!p.tap(2)&&p.tap(2),"selection switch");check(!p.tap(1),"first tap");p.onShow();check(!p.tap(1),"stale tap after show");
  SurvivalRun r=new SurvivalRun(3,1713);for(int i=0;i<SurvivalRun.PLAYER_RAYS;i++){r.rayLife[i]=1000;r.rayX[i]=r.rayY[i]=256;}target(r,0,100,0,0);r.update(20,0,0);check(rays(r,true)==1,"player pool starved enemy fire");
  r=new SurvivalRun(3,1714);for(int i=SurvivalRun.PLAYER_RAYS;i<SurvivalRun.MAX_RAYS;i++){r.rayLife[i]=1000;r.rayEnemy[i]=true;}check(r.attack()&&rays(r,false)==1,"enemy pool starved player");
  r=new SurvivalRun(3,1715);int base=r.attackCooldown();r.burstCount=3;check(r.attackCooldown()==base+160,"burst cooldown scaling");r.shotCount=5;r.dir=2;check(r.attack(),"max volley");int first=r.rayDamage[0];r.update(120,0,0);check(r.rayDamage[5]==Math.max(1,first*85/100),"follow-up damage");
  r=new SurvivalRun(3,1716);r.elementPending=true;r.pendingLevels=1;r.choices[0]=SurvivalRun.POWER;check(!r.choose(0),"buff bypassed element popup");r.elementPending=false;r.enemySp[0]=0;r.ex[0]=r.x;r.ey[0]=r.y;r.ehp[0]=1000;r.target=0;r.pendingLevels=0;check(r.attack()&&r.rayVX[0]!=0,"zero-direction projectile");
  for(int wave=1;wave<=100;wave++){check(SurvivalRun.enemyHealth(0,wave,0)>SurvivalRun.enemyHealth(0,wave-1,0)||wave==1,"health progression");check(SurvivalRun.enemyHealth(0,wave,3)==SurvivalRun.enemyHealth(0,wave,0)*3,"boss hp");check(SurvivalRun.enemyPower(0,wave)>=SurvivalRun.enemyPower(0,wave-1),"damage progression");check(SurvivalRun.wavePopulation(wave)<=56,"unbounded waves");}
  r=new SurvivalRun(3,1717);r.level=15;r.shotCount=5;r.burstCount=3;r.range=6;r.buffTime[3]=1000000;for(int i=0;i<SurvivalRun.MAX_ENEMIES;i++)target(r,i,(i%7-3)*28,(i/7-2)*28,i%3);long began=System.currentTimeMillis();int peak=0;for(int i=0;i<10000;i++){r.update(20,0,0);r.attack();int player=rays(r,false),enemy=rays(r,true);check(player<=SurvivalRun.PLAYER_RAYS&&enemy<=SurvivalRun.MAX_RAYS-SurvivalRun.PLAYER_RAYS,"projectile partition overflow");peak=Math.max(peak,player+enemy);check(!r.over&&r.pendingLevels==0,"stress simulation interrupted");}
  long firingMs=System.currentTimeMillis()-began;for(int i=0;i<SurvivalRun.MAX_RAYS;i++){r.rayLife[i]=1000000;r.rayX[i]=r.prevRayX[i]=256;r.rayY[i]=r.prevRayY[i]=256;r.rayVX[i]=r.rayVY[i]=0;r.rayEnemy[i]=i>=SurvivalRun.PLAYER_RAYS;}began=System.currentTimeMillis();for(int i=0;i<10000;i++){r.update(20,0,0);check(rays(r,false)==56&&rays(r,true)==16&&r.living()==28,"saturated stress pool changed");}
  System.out.println("ReleasePolishTest OK: Gacha hit geometry, fresh touch state, ray reservations, burst balance, wave curve; 10000 firing ticks="+firingMs+"ms peak rays="+peak+"; 10000 saturated ticks="+(System.currentTimeMillis()-began)+"ms (28 enemies/72 rays; not device FPS)");
 }
}
