package pac;

/** Transactions and passives never modify global ownership or the chess run. */
public final class SurvivalShopTest{
 private static void check(boolean b,String m){if(!b)throw new RuntimeException(m);}
 public static void run(){SurvivalRun r=new SurvivalRun(0,719);int baseAtk=r.atk,baseHp=r.maxHp,baseDef=r.def;
  check(!r.shop.upgrade(r,1)&&r.atk==baseAtk,"free upgrade");r.gold=10000;r.hp=3;
  check(r.shop.upgrade(r,0)&&r.maxHp==baseHp+20&&r.hp==3,"upgrade heals or loses HP");
  for(int i=0;i<10;i++)check(r.shop.upgrade(r,1),"valid ATK rank rejected");int gold=r.gold;check(r.atk==baseAtk+20&&!r.shop.upgrade(r,1)&&r.gold==gold,"rank cap or double charge");
  check(!r.shop.upgrade(r,-1)&&!r.shop.buy(r,6),"invalid shop index");
  int speed=r.speed;r.speed=CombatRules.MAX_SPEED;gold=r.gold;check(!r.shop.upgrade(r,4)&&r.gold==gold,"speed cap charged gold");r.speed=speed;
  gold=r.gold;check(r.shop.buyGear(r,1)&&r.shop.bag[1]==1&&r.gold==gold-SurvivalShop.gearPrice(1),"finished gear purchase");r.shop.bag[1]=0;r.gold=0;check(!r.shop.buyGear(r,1)&&r.shop.bag[1]==0,"free finished gear");r.gold=10000;
  check(r.shop.buy(r,0)&&r.shop.parts[0]==1,"buy component");gold=r.gold;check(!r.shop.craft(r,0)&&r.shop.parts[0]==1&&r.gold==gold,"same component recipe needs two");
  r.shop.buy(r,0);check(r.shop.craft(r,0)&&r.shop.parts[0]==0&&r.shop.bag[0]==1,"recipe transaction");check(r.shop.equip(r,0)&&r.atk==baseAtk+26,"gear stats missing");r.shop.bag[0]=1;check(!r.shop.equip(r,0)&&r.shop.bag[0]==1,"duplicate passive equipped");check(r.shop.unequip(r,0)&&r.atk==baseAtk+20,"unequip left stats");
  for(int gear=0;gear<6;gear++){check(SurvivalShop.gearIcon(gear)>=0,"missing gear icon");r.shop.bag[gear]=1;check(r.shop.equip(r,gear),"six slots not equipable");}
  check(r.def==baseDef+8&&r.maxHp==baseHp+60&&r.shop.dashCost()==15&&r.shop.ultiCooldown()==24000,"passive stats/cooldown");
  r.pendingLevels=0;r.variantPending=0;r.elementPending=false;r.mana=15;check(r.dash(1,0)&&r.mana==0,"dash passive not applied");
  int ulti=r.ultimatePower();r.shop.unequip(r,5);check(ulti>r.ultimatePower(),"ultimate damage passive missing");r.shop.equip(r,5);
  r.hp=10;r.mana=0;r.update(250,0,0);r.update(250,0,0);r.update(250,0,0);r.update(250,0,0);check(r.hp>10,"regen passive missing");
  r.dropBossParts(r.x,r.y);int drops=0;for(int i=0;i<SurvivalRun.MAX_DROPS;i++)if(r.dropLife[i]>0)drops++;check(drops>=2&&drops<=4,"boss drop count");r.update(20,0,0);int got=0;for(int i=0;i<6;i++)got+=r.shop.parts[i];check(got==drops,"boss pickup lost");
  int hp=r.hp;for(int i=0;i<6;i++)r.shop.unequip(r,i);check(r.hp<=hp,"unequip heals");SurvivalRun fresh=new SurvivalRun(0,719);check(fresh.gold==0&&fresh.shop.ranks[1]==0&&fresh.shop.slots[0]==-1,"retry kept economy");
  check(SurvivalRun.WIDTH==1280&&SurvivalRun.HEIGHT==960&&SurvivalMapData.tile(39,29)>=0&&SurvivalMapData.walkable(1268,948)&&!SurvivalMapData.walkable(1270,950),"expanded map bounds");
  int[] heights={160,208,240,320,640};for(int h=0;h<heights.length;h++)for(int fh=8;fh<=16;fh+=2){int top=fh*3+12,row=Math.max(26,fh+14),visible=UiLayout.visibleRows(heights[h],top,fh*5+26,row);if(heights[h]>=208)check(top+visible*row<=heights[h]-fh*5-22,"shop list overlaps description");}
  r.finish();gold=r.gold;check(!r.shop.buy(r,0)&&!r.shop.upgrade(r,2)&&r.gold==gold,"finished run allows purchases");
int[][] sizes={{320,240},{240,320},{176,208},{360,640}};for(int i=0;i<sizes.length;i++){int w=sizes[i][0],h=sizes[i][1],cell=SurvivalShopLayout.cell(w,h);check(SurvivalShopLayout.detailY(w,h)+SurvivalShopLayout.detailH(w,h)<=SurvivalShopLayout.partsY(w,h)-11,"detail overlaps parts label");check(SurvivalShopLayout.partsY(w,h)+cell<=SurvivalShopLayout.gearsY(w,h)-11,"bag rows overlap");for(int rr=0;rr<3;rr++)for(int c=0;c<6;c++){int xx=SurvivalShopLayout.gridX(w,h,c),yy=rr==0?SurvivalShopLayout.slotY():rr==1?SurvivalShopLayout.partsY(w,h):SurvivalShopLayout.gearsY(w,h);check(SurvivalShopLayout.hitGrid(xx+2,yy+2,w,h,rr)==c,"slot draw/hit mismatch");check(SurvivalShopLayout.hitGrid(xx+cell,yy+2,w,h,rr)==-1,"slot gutter clickable");}}
  for(int gear=0;gear<6;gear++)check(SurvivalShopLayout.recipe(SurvivalShop.A[gear],SurvivalShop.B[gear])==gear&&SurvivalShopLayout.recipe(SurvivalShop.B[gear],SurvivalShop.A[gear])==gear,"explicit crafting preview mismatch");check(SurvivalShopLayout.recipe(-1,0)==-1,"empty crafting input produces gear");
for(int a=0;a<6;a++)for(int b=a;b<6;b++){int gear=SurvivalShopLayout.recipe(a,b);check(gear>=0,"missing component pair preview");SurvivalRun craftRun=new SurvivalRun(0,723);craftRun.gold=10000;craftRun.shop.parts[a]++;craftRun.shop.parts[b]++;check(craftRun.shop.craftParts(craftRun,a,b)&&craftRun.shop.parts[a]==0&&craftRun.shop.parts[b]==0&&craftRun.shop.bag[gear]==1,"preview/craft output mismatch");}
  for(int g=0;g<SurvivalShop.GEARS;g++){SurvivalRun direct=new SurvivalRun(0,729),staged=new SurvivalRun(0,729);int total=SurvivalShop.gearPrice(g);direct.gold=staged.gold=total;check(direct.shop.purchaseUpgrade(direct,g)&&direct.gold==0,"direct item price");check(staged.shop.plan(g)&&staged.shop.plannedGear==g,"plan target missing");check(staged.shop.buy(staged,SurvivalShop.A[g])&&staged.shop.remainingPrice(g)==total-15,"first component credit");check(staged.shop.buy(staged,SurvivalShop.B[g])&&staged.shop.remainingPrice(g)==total-30,"second component credit");check(staged.shop.purchaseUpgrade(staged,g)&&staged.gold==0&&staged.shop.bag[g]==1&&staged.shop.plannedGear==-1,"staged purchase mismatch");check(staged.shop.parts[SurvivalShop.A[g]]==0&&staged.shop.parts[SurvivalShop.B[g]]==0,"components not consumed");}
  SurvivalRun partial=new SurvivalRun(0,729);partial.shop.parts[0]=1;partial.gold=74;check(!partial.shop.purchaseUpgrade(partial,0)&&partial.gold==74&&partial.shop.parts[0]==1,"failed purchase mutated inventory");partial.gold=75;check(partial.shop.purchaseUpgrade(partial,0)&&partial.gold==0&&partial.shop.parts[0]==0,"one of two identical components credit");SurvivalRun freeDrop=new SurvivalRun(0,729);freeDrop.shop.parts[0]=3;freeDrop.gold=60;check(freeDrop.shop.purchaseUpgrade(freeDrop,0)&&freeDrop.shop.parts[0]==1,"free drops credit or spare ingredient lost");SurvivalRun noFee=new SurvivalRun(0,729);noFee.shop.parts[0]=2;check(!noFee.shop.craft(noFee,0)&&noFee.shop.parts[0]==2,"legacy crafting bypassed upgrade fee");
  check("POKEMONOMICON".equals(SurvivalShop.GEAR_ID[SurvivalShopLayout.recipe(0,2)]),"charcoal/spoon result missing");
  int[] sparse={0,2,0,1,0,3};check(SurvivalShopLayout.ownedCount(sparse)==3,"sparse bag count");check(SurvivalShopLayout.ownedAt(sparse,0)==1&&SurvivalShopLayout.ownedAt(sparse,1)==3&&SurvivalShopLayout.ownedAt(sparse,2)==5&&SurvivalShopLayout.ownedAt(sparse,3)==-1,"bag must pack owned items in catalogue order");sparse[1]=0;check(SurvivalShopLayout.ownedAt(sparse,0)==3&&SurvivalShopLayout.ownedAt(sparse,1)==5,"bag must repack after item removal");check(SurvivalShopLayout.ownedCount(new int[8])==0&&SurvivalShopLayout.ownedAt(new int[8],0)==-1,"empty bag mapping");
  SurvivalRun quick=new SurvivalRun(0,730);quick.shop.plan(0);quick.gold=14;check(!quick.shop.quickBuyAvailable(quick),"quick buy without gold");quick.gold=15;check(quick.shop.quickTarget(quick)==SurvivalShop.GEARS&&quick.shop.quickPurchase(quick)&&quick.gold==0&&quick.shop.parts[0]==1&&quick.shop.plannedGear==0,"planned component quick purchase");quick.shop.parts[0]=0;quick.gold=89;quick.shop.parts[0]=1;check(quick.shop.quickBuyAvailable(quick),"quick buy must credit owned ingredients");quick.pendingLevels=1;check(!quick.shop.quickBuyAvailable(quick),"quick buy during buff selection");quick.pendingLevels=0;check(quick.shop.purchaseUpgrade(quick,quick.shop.plannedGear)&&!quick.shop.quickBuyAvailable(quick)&&quick.shop.plannedGear==-1,"quick buy did not clear target");quick.shop.plan(0);quick.shop.slots[0]=0;quick.gold=1000;check(!quick.shop.quickBuyAvailable(quick),"quick offer for already equipped gear");
  for(int gear=0;gear<SurvivalShop.GEARS;gear++){SurvivalRun wear=new SurvivalRun(0,731);wear.gold=SurvivalShop.gearPrice(gear);check(wear.shop.buyAndEquip(wear,SurvivalShop.GEARS+SurvivalShop.A[gear]),"buy/wear first component");check(wear.shop.buyAndEquip(wear,SurvivalShop.GEARS+SurvivalShop.B[gear]),"buy/wear second component");check(wear.shop.slots[0]>=SurvivalShop.GEARS&&wear.shop.slots[1]>=SurvivalShop.GEARS,"components missing from HUD slots");check(wear.shop.remainingPrice(gear)==SurvivalShop.upgradeFee(gear),"recipe fee mismatch");check(wear.shop.buyAndEquip(wear,gear)&&wear.gold==0&&wear.shop.slots[0]==gear&&wear.shop.slots[1]==-1&&wear.shop.bag[gear]==0,"upgrade must replace worn components");check(wear.shop.sell(wear,gear,0)&&wear.gold==SurvivalShop.gearPrice(gear)/2&&wear.shop.slots[0]==-1,"sell equipped half price");check(!wear.shop.sell(wear,gear,0),"double sale");}
  SurvivalRun resale=new SurvivalRun(0,731);resale.gold=15;check(resale.shop.buyAndEquip(resale,SurvivalShop.GEARS)&&resale.shop.sell(resale,SurvivalShop.GEARS,0)&&resale.gold==7&&resale.shop.parts[0]==0,"sell worn component");
  int[] statHeights={160,208,240,320,640};for(int i=0;i<statHeights.length;i++)for(int selected=0;selected<5;selected++){int h=statHeights[i],row=SurvivalShopLayout.statsRow(h),first=SurvivalShopLayout.statsFirst(selected,h),visible=SurvivalShopLayout.statsVisible(h);check(selected>=first&&selected<first+visible,"selected upgrade not visible");for(int rr=0;rr<visible&&first+rr<5;rr++){int y=SurvivalShopLayout.statsTop(h)+rr*row;check(y+row<=h-24,"upgrade overlaps footer");check(SurvivalShopLayout.hitStat(10,y+2,320,h,selected)==first+rr,"upgrade draw/touch mismatch");check(SurvivalShopLayout.hitStat(10,y+row-1,320,h,selected)==-1,"upgrade gap clickable");}check(SurvivalShopLayout.hitStat(10,90,320,h,selected)==-1,"Pokemon info should not upgrade");}
  check(SurvivalShopLayout.bagVisible(320,240)==8,"landscape bag should show eight slots");
  for(int i=0;i<sizes.length;i++){int w=sizes[i][0],h=sizes[i][1],n=SurvivalShopLayout.bagVisible(w,h),size=SurvivalShopLayout.cell(w,h);check(SurvivalShopLayout.bagX(w,h,0)>=14&&SurvivalShopLayout.bagX(w,h,n-1)+size<=w-14,"bag overlaps arrows");for(int c=1;c<n;c++)check(SurvivalShopLayout.bagX(w,h,c)-SurvivalShopLayout.bagX(w,h,c-1)==size+4,"bag gaps inconsistent");}
  System.out.println("SurvivalShopTest OK: gold, rank caps, recipes, six slots, responsive bag slots, duplicate passives, dash/regen/ultimate, boss drops, retry and expanded map");
 }
}
