package pac;
import java.lang.reflect.Method;
import java.lang.reflect.Field;
/** Desktop checks for real combat hooks, not a rendering/FPS test. */
public final class SurvivalGearTest {
 private static void check(boolean b,String m){if(!b)throw new RuntimeException(m);}
 private static Object call(SurvivalRun r,String name,Class[] types,Object[] args){try{Method m=SurvivalRun.class.getDeclaredMethod(name,types);m.setAccessible(true);return m.invoke(r,args);}catch(Exception e){throw new RuntimeException(name,e);}}
 private static Object field(SurvivalRun r,String name){try{Field f=SurvivalRun.class.getDeclaredField(name);f.setAccessible(true);return f.get(r);}catch(Exception e){throw new RuntimeException(name,e);}}
 private static void clearImmunity(SurvivalRun r){try{Field f=SurvivalRun.class.getDeclaredField("invulnerable");f.setAccessible(true);f.setInt(r,0);}catch(Exception e){throw new RuntimeException(e);}}
 private static void damage(SurvivalRun r,int power,boolean special){clearImmunity(r);call(r,"damageHero",new Class[]{Integer.TYPE,Boolean.TYPE},new Object[]{new Integer(power),Boolean.valueOf(special)});}
 private static void hit(SurvivalRun r,int power){call(r,"hit",new Class[]{Integer.TYPE,Integer.TYPE},new Object[]{new Integer(0),new Integer(power)});}
 private static void tick(SurvivalRun r){call(r,"tickGear",new Class[0],new Object[0]);}
 private static SurvivalRun run(int gear){SurvivalRun r=new SurvivalRun(0,726);r.shop.slots[0]=gear;r.maxHp=r.hp=100;r.maxMana=100;r.mana=0;r.def=r.specialDefense=0;r.enemySp[0]=0;r.ehp[0]=r.emax[0]=1000;r.ex[0]=r.x+10*256;r.ey[0]=r.y;return r;}
 public static void run(){
  for(int target=0;target<SurvivalShop.GEARS+SurvivalShop.PARTS;target++){SurvivalRun wearing=new SurvivalRun(0,734);int hp=wearing.maxHp,atk=wearing.atk,def=wearing.def,res=wearing.specialDefense,mp=wearing.maxMana,spd=wearing.speed;wearing.gold=10000;check(wearing.shop.buyAndEquip(wearing,target)&&wearing.shop.slots[0]==target,"purchase must wear immediately");int item=target>=SurvivalShop.GEARS?SurvivalShop.ICON[target-SurvivalShop.GEARS]:target>=6?SurvivalShop.gearIcon(target):-1;int dh=item>=0?ItemData.HP[item]:target==2?40:0,da=item>=0?ItemData.ATK[item]:target==0?6:target==5?5:0,dd=item>=0?ItemData.DEF[item]:target==1?8:0,dr=item>=0?ItemData.SPE_DEF[item]:target==3?5:0,dm=item>=0?ItemData.MP[item]:target==3?30:0,ds=item>=0?ItemData.SPEED[item]:target==4?12:0;check(wearing.maxHp==hp+dh&&wearing.atk==atk+da&&wearing.def==def+dd&&wearing.specialDefense==res+dr&&wearing.maxMana==mp+dm&&wearing.speed==CombatRules.cappedSpeed(spd+ds),"worn stats mismatch for "+target);if(target<SurvivalShop.GEARS)check(wearing.shop.activePassives().indexOf(SurvivalShop.passiveDesc(target))>=0,"equipped passive missing from stats tab");check(wearing.shop.sell(wearing,target,0)&&wearing.maxHp==hp&&wearing.atk==atk&&wearing.def==def&&wearing.specialDefense==res&&wearing.maxMana==mp&&wearing.speed==spd,"selling must remove stat effects");}
  int[] icon={0,0,0,0,0,0xFFFF0000,0xFF00FF00,0,0,0xFF0000FF,0xFFFFFFFF,0,0,0,0,0};int[] fitted=SurvivalGearIcons.fit(icon,4,4,20,false),gray=SurvivalGearIcons.fit(icon,4,4,20,true);check(fitted[0]==0xFFFF0000&&fitted[399]==0xFFFFFFFF,"icon must crop transparent padding and fill slot");for(int i=0;i<gray.length;i++){int c=gray[i];check(((c>>16)&255)==((c>>8)&255)&&((c>>8)&255)==(c&255),"cooldown icon not grayscale");}check(SurvivalGearIcons.fit(new int[4],2,2,12,false)[0]==0,"empty icon transparency");
  SurvivalRun timer=run(11);check(timer.gearCooldownRemaining(11)==0,"ready gear timer");damage(timer,10000,false);check(timer.gearCooldownRemaining(11)==60000,"HUD cooldown mismatch");tick(timer);check(timer.gearCooldownRemaining(11)==59980,"HUD timer not ticking");timer.shop.slots[0]=-1;check(timer.gearCooldownRemaining(11)==0,"unequipped timer visible");timer=run(16);damage(timer,10000,false);check(timer.gearCooldownRemaining(16)==-1,"spent revive must stay gray");check(run(16).gearCooldownRemaining(16)==0,"retry kept spent icon");
  for(int g=0;g<SurvivalShop.GEARS;g++){check(SurvivalShop.passiveDesc(g).length()>0,"missing passive description");String desc=SurvivalShop.gearDesc(g);int split=desc.indexOf('\n');check(split>0&&desc.indexOf('\n',split+1)<0,"description must have two lines");check(desc.indexOf("5:")<0&&desc.indexOf("5/#")<0&&desc.indexOf("+0")<0,"irrelevant description text");}
  check(SurvivalShop.componentDesc().indexOf('\n')>0,"component description must have two lines");
  check(SurvivalShopLayout.marqueeOffset(80,100,8000)==0,"short line should not scroll");check(SurvivalShopLayout.marqueeOffset(200,100,1000)==0,"marquee should initially hold");check(SurvivalShopLayout.marqueeOffset(200,100,2950)==50,"marquee speed");check(SurvivalShopLayout.marqueeOffset(200,100,5000)==100,"marquee end hold");check(SurvivalShopLayout.marqueeOffset(200,100,5900)==0,"marquee should loop");
  SurvivalRun r=run(6);hit(r,20);check(((int[])field(r,"burnTime"))[0]==3000&&((int[])field(r,"burnDamage"))[0]==4,"burn missing");call(r,"hit",new Class[]{Integer.TYPE,Integer.TYPE,Boolean.TYPE},new Object[]{new Integer(0),new Integer(4),Boolean.FALSE});check(((int[])field(r,"burnTime"))[0]==3000,"DoT refreshed burn");
  r=run(7);r.ehp[0]=500;hit(r,20);check(r.lastDamage[0]==24,"execution bonus");
  r=run(8);for(int i=0;i<5;i++)hit(r,20);check(r.lastDamage[0]==30,"fifth hit bonus");
  r=run(9);tick(r);check(r.shield==60,"protective shield");r.shield=0;r.shop.slots[0]=-1;r.shop.slots[0]=9;tick(r);check(r.shield==0,"reequip reset shield cooldown");r=run(9);tick(r);for(int i=0;i<250;i++)tick(r);check(r.shield==0,"temporary shield did not expire");
  r=run(10);damage(r,20,false);check(r.lastDamage[0]>0&&r.ehp[0]<1000,"reflection missing");
  r=run(11);damage(r,10000,false);check(r.hp==1&&!r.over&&((Integer)field(r,"invulnerable")).intValue()==2000,"death guard missing");int hp=r.hp;call(r,"damageHero",new Class[]{Integer.TYPE,Boolean.TYPE},new Object[]{new Integer(10000),Boolean.FALSE});check(r.hp==hp,"guard immunity missing");r.shop.slots[0]=-1;r.shop.slots[0]=11;damage(r,10000,false);check(r.over,"guard cooldown reset on re-equip");
  r=run(12);r.mana=100;r.target=0;check(r.ultimate()&&r.mana==20,"ultimate refund missing");
  r=run(13);check(((Boolean)call(r,"fireVolley",new Class[]{Integer.TYPE,Integer.TYPE,Integer.TYPE},new Object[]{new Integer(256),new Integer(0),new Integer(100)})).booleanValue(),"critical volley failed");check(((int[])field(r,"gearCooldown"))[13]==8000,"critical cooldown missing");
  r=run(14);r.hp=10;damage(r,10000,false);check(!r.over&&r.hp==25&&r.shield==40&&((int[])field(r,"gearCooldown"))[14]==45000,"low HP protection missing");
  r=run(15);for(int i=0;i<6;i++)hit(r,10);check(((int[])field(r,"stunTime"))[0]==1000,"stun missing");
  r=run(16);damage(r,10000,false);check(!r.over&&r.hp==50&&r.mana==50,"revive missing");r.shop.slots[0]=-1;r.shop.slots[0]=16;damage(r,10000,false);check(r.over,"revive repeat exploit");SurvivalRun retry=run(16);damage(retry,10000,false);check(!retry.over,"retry failed to reset revive");
  SurvivalRun plain=run(-1);r=run(17);damage(plain,40,true);damage(r,40,true);check(r.hp>plain.hp,"spell resistance missing");
  for(int sp=0;sp<Data.CORE_N;sp++)if(ShinyData.available(sp)&&ShinyData.role(sp)==0){r=new SurvivalRun(sp,1740);r.sp=sp;r.shop.slots[0]=9;r.shopRebuild();tick(r);int gearShield=r.shield;r.level=12;r.pendingLevels=1;r.choices[0]=SurvivalRun.SHINY;check(r.choose(0)&&r.shield==gearShield+Math.max(1,r.maxHp/10),"Shiny overwrote temporary equipment shield");for(int i=0;i<250;i++)tick(r);check(r.shield==Math.max(1,r.maxHp/10),"equipment shield expiry removed Shiny shield");break;}
  r=run(11);damage(r,10000,false);int cooldown=((int[])field(r,"gearCooldown"))[11];r.pendingLevels=1;r.update(250,0,0);check(((int[])field(r,"gearCooldown"))[11]==cooldown,"buff pause advanced cooldown");
  r=run(11);r.shop.slots[1]=16;r.shop.slots[2]=14;damage(r,10000,false);check(((int[])field(r,"gearCooldown"))[14]>0,"low HP guard priority");damage(r,10000,false);check(r.hp==1&&!r.over,"death guard priority");damage(r,10000,false);check(r.hp==50&&!r.over,"revive fallback priority");damage(r,10000,false);check(r.over,"stacked defenses are immortal");
  System.out.println("SurvivalGearTest OK: twelve passives, cooldowns, temporary shields, lethal guards, one-run revive, stacking priority, pause and retry");
 }
}
