package pac;

/** Desktop-only arena regressions; never shipped inside the phone JAR. */
public final class SurvivalSmokeTest {
 private static void check(boolean ok,String s){if(!ok)throw new RuntimeException(s);}
 private static int named(String name){for(int i=0;i<Data.N;i++)if(name.equals(Data.name[i]))return i;throw new RuntimeException(name);}
 private static void enemy(SurvivalRun r,int slot,int hp,int offset){r.enemySp[slot]=0;r.ehp[slot]=r.emax[slot]=hp;r.ex[slot]=r.x+offset*256;r.ey[slot]=r.y;r.edamage[slot]=5;r.ecool[slot]=1000;}
 public static void run(){
  check(Game.combinedHeldDirection(16)==Game.K_1&&Game.combinedHeldDirection(32)==Game.K_3&&Game.combinedHeldDirection(64)==Game.K_7&&Game.combinedHeldDirection(128)==Game.K_9,"held diagonal key mapping failed");
  check(Game.combinedHeldDirection(1|16)==Game.K_1&&Game.combinedHeldDirection(1)==Game.K_UP,"releasing diagonal lost independent up input");
  check(SurvivalAnimation.interpolate(0,256,10)==128&&SurvivalAnimation.interpolate(256,0,10)==128,"render interpolation failed");
  check(SurvivalAnimation.clock(RawAtlas.IDLE,1000,99999)==8&&SurvivalAnimation.clock(RawAtlas.WALK,1000,6*256)==2&&SurvivalAnimation.clock(RawAtlas.ATTACK,65,0)==2,"arena animation cadence failed");
  check(SurvivalMapData.GROUND.length==15&&SurvivalMapData.walkable(320,240)&&!SurvivalMapData.walkable(0,0),"map geometry failed");for(int row=0;row<15;row++){check(SurvivalMapData.GROUND[row].length()==20,"map row width mismatch");for(int col=0;col<20;col++)check(SurvivalMapData.tile(col,row)>=0&&SurvivalMapData.tile(col,row)<8,"bad terrain tile");}
  int starter=named("Charmander");SurvivalRun r=new SurvivalRun(starter,17301);check(r.originalSpecies==starter&&r.hp==Data.hp[starter],"arena did not use selected profile species");check(r.attackRadius()==47+r.range*16,"attack ring differs from hit radius");
  SurvivalRun diagonal=new SurvivalRun(starter,17302),straight=new SurvivalRun(starter,17302);diagonal.update(200,1,1);straight.update(200,1,0);int dd=diagonal.x-SurvivalRun.WIDTH*128,sd=straight.x-SurvivalRun.WIDTH*128;check(dd>0&&dd<sd&&diagonal.y>SurvivalRun.HEIGHT*128,"diagonal movement not normalized");int x=r.x,y=r.y;r.update(200,0,0);check(r.x==x&&r.y==y,"idle position drift");r.x=12*256;r.y=12*256;r.update(200,-1,-1);check(r.x==12*256&&r.y==12*256,"arena boundary collision failed");
  r=new SurvivalRun(starter,17303);enemy(r,0,100,20);r.update(200,0,0);check(r.ehp[0]==100,"normal attacks fired automatically");check(r.attack()&&r.ehp[0]==100&&!r.attack(),"manual ray launch/cooldown failed");r.update(60,0,0);check(r.ehp[0]<100,"hero ray did not hit");check(!r.ultimate(),"ultimate cast without energy");r.mana=r.maxMana;check(r.ultimate()&&r.mana==0&&r.skillFx>0&&!r.ultimate(),"manual ultimate/cooldown failed");
  r=new SurvivalRun(starter,17304);enemy(r,0,1000,20);r.pendingLevels=1;r.choices[0]=SurvivalRun.EVOLVE;r.choices[1]=SurvivalRun.POWER;r.choices[2]=SurvivalRun.VITALITY;int elapsed=r.elapsed,hp=r.hp;r.update(250,1,0);check(r.elapsed==elapsed&&r.hp==hp&&!r.attack()&&!r.ultimate(),"level selection did not pause combat");check(r.choose(0)&&r.sp==Data.evo[starter]&&r.originalSpecies==starter&&r.hp>0,"evolution failed or mutated original hero");
  int power=r.atk;r.pendingLevels=1;r.choices[0]=SurvivalRun.POWER;check(r.choose(0)&&r.atk==power+3,"selected buff not applied");r.pendingLevels=1;r.choices[0]=SurvivalRun.HASTE;r.speed=CombatRules.MAX_SPEED;check(!r.choose(0)&&r.speed==CombatRules.MAX_SPEED,"capped speed buff accepted");
  SurvivalRun upgraded=new SurvivalRun(named("Charizard"),17305);check(upgraded.sp==starter,"final form did not start at first evolution");upgraded.level=15;upgraded.sp=named("Charizard");upgraded.pendingLevels=1;upgraded.choices[0]=SurvivalRun.MEGA;check(upgraded.choose(0)&&upgraded.mega&&!upgraded.shiny&&upgraded.type2()==Data.T_DRAGON,"arena Mega form/types failed");upgraded.pendingLevels=1;upgraded.choices[0]=SurvivalRun.SHINY;check(upgraded.choose(0)&&upgraded.shiny&&upgraded.mega,"shiny lost Mega");
  SurvivalRun regional=new SurvivalRun(named("Raichu"),17306);regional.level=9;regional.hp=1;regional.mana=0;regional.gainXp(regional.xpNeeded());check(regional.sp==named("Raichu")&&regional.variantPending>0&&regional.hp==regional.maxHp&&regional.mana==regional.maxMana,"automatic evolution/variant/full restoration failed");check(regional.chooseVariant(true)&&regional.type2()==Data.T_PSY,"arena regional form failed");
  r=new SurvivalRun(starter,17307);r.xp=r.xpNeeded()-1;enemy(r,0,1,10);check(r.attack(),"kill ray launch failed");r.update(20,0,0);check(r.kills==1&&r.pendingLevels==1&&r.level==2,"kill XP/level choice failed");check(r.choices[0]!=r.choices[1]&&r.choices[1]!=r.choices[2]&&r.choices[0]!=r.choices[2],"duplicate level options");
  check(r.claimReward()==0,"reward claimed before defeat");r.kills=17;r.completedWaves=4;r.finish();check(r.reward()==7&&r.claimReward()==7&&r.claimReward()==0,"reward duplicate or incorrect");int time=r.elapsed;r.update(250,1,0);check(r.elapsed==time&&!r.attack()&&!r.choose(0),"finished run still mutable");
  r=new SurvivalRun(starter,17308);for(int i=0;i<10000&&!r.over;i++)r.update(20,0,0);check(r.over&&r.hp==0&&r.living()<=SurvivalRun.MAX_ENEMIES,"idle player never lost / enemy pool exceeded bound");
  SurvivalRun a=new SurvivalRun(starter,17309),b=new SurvivalRun(starter,17309);for(int i=0;i<50;i++){a.update(100,0,0);for(int j=0;j<5;j++)b.update(20,0,0);}check(a.elapsed==b.elapsed&&a.hp==b.hp&&a.living()==b.living(),"fixed-step arena depends on frame rate");for(int i=0;i<SurvivalRun.MAX_ENEMIES;i++)check(a.enemySp[i]==b.enemySp[i]&&a.ex[i]==b.ex[i]&&a.ey[i]==b.ey[i],"deterministic spawn/movement mismatch");
  SurvivalRun fresh=new SurvivalRun(starter,17310);enemy(fresh,0,1000,80);fresh.ecool[0]=0;int health=fresh.hp;fresh.update(20,0,0);check(fresh.hp==health,"enemy shot caused instant damage");fresh.update(250,0,0);fresh.update(250,0,0);check(fresh.hp<health,"enemy projectile failed to damage on contact");fresh.finish();for(int i=0;i<SurvivalRun.MAX_RAYS;i++)check(fresh.rayLife[i]==0,"finished run kept rays");SurvivalRun retry=new SurvivalRun(starter,17310);check(retry.hp==retry.maxHp&&retry.kills==0&&retry.mana==0&&!retry.over,"retry inherited old run state");
  SurvivalRun dodge=new SurvivalRun(starter,17311);enemy(dodge,0,1000,80);dodge.ecool[0]=0;health=dodge.hp;dodge.update(20,0,0);dodge.y+=80*256;dodge.prevY=dodge.y;dodge.ecool[0]=10000;for(int i=0;i<12;i++)dodge.update(100,0,0);check(dodge.hp==health,"enemy ray tracked hero after launch / missed ray damaged hero");check(retry.attack(),"empty arena cannot fire a normal ray");retry.finish();for(int i=0;i<SurvivalRun.MAX_RAYS;i++)check(retry.rayLife[i]==0,"retry ray cleanup failed");
  System.out.println("SurvivalSmokeTest OK: manual projectiles, enemy hit/miss, retry reset, smooth movement, bounds, buff pause, evolution/Mega/Shiny/regional, waves, defeat, deterministic steps and exactly-once rewards");
 }
}
