package pac;

/** Progression, projectile mechanics, lock-on and short-lived pickups. */
public final class SurvivalSystemTest {
 private static void check(boolean b,String m){if(!b)throw new RuntimeException(m);}
 private static int named(String n){for(int i=0;i<Data.N;i++)if(n.equals(Data.name[i]))return i;throw new RuntimeException(n);}
 private static void enemy(SurvivalRun r,int i,int dx,int dy){r.enemySp[i]=0;r.ehp[i]=r.emax[i]=10000;r.ex[i]=r.prevEx[i]=r.x+dx*256;r.ey[i]=r.prevEy[i]=r.y+dy*256;r.ecool[i]=10000;}
 public static void run(){
  int c=named("Charizard"),a=named("Charmander");check(SurvivalProgress.startSpecies(c)==a&&SurvivalProgress.speciesAt(c,5)==named("Charmeleon")&&SurvivalProgress.speciesAt(c,10)==c,"evolution milestones wrong");check(SurvivalProgress.startSpecies(named("Moltres"))==named("Moltres"),"legendary reverted");check(SurvivalProgress.startSpecies(named("Vaporeon"))==named("Eevee")&&SurvivalProgress.speciesAt(named("Vaporeon"),5)==named("Vaporeon"),"selected Eevee branch lost");
  for(int sp=0;sp<Data.N;sp++){int base=SurvivalProgress.startSpecies(sp);check(base>=0&&base<Data.N,"bad starter");check(SurvivalProgress.speciesAt(sp,10)>=0,"bad final evolution");}
  SurvivalRun r=new SurvivalRun(c,17401);r.level=4;r.hp=1;r.gainXp(r.xpNeeded());check(r.level==5&&r.skillTier()==2&&r.sp==named("Charmeleon")&&r.hp==r.maxHp&&r.mana==r.maxMana,"level refill/evolution failed");int time=r.elapsed;r.update(100,1,0);check(r.elapsed==time,"upgrade pause failed");r.choices[0]=SurvivalRun.POWER;check(r.choose(0),"buff selection failed");r.level=9;r.gainXp(r.xpNeeded());check(r.sp==c&&r.skillTier()==3,"second evolution failed");
  r=new SurvivalRun(a,17402);enemy(r,0,35,0);enemy(r,1,20,25);r.target=0;check(r.attack()&&r.target==0,"lock-on failed");r.update(100,0,1);check(r.y>SurvivalRun.HEIGHT*128&&r.ehp[0]<10000&&r.target==0,"movement interrupted shooting or lock switched");r.cycleTarget();check(r.target==1,"star target cycle failed");r.enemySp[1]=-1;r.normalCd=0;check(r.attack()&&r.target==0,"dead lock recovery failed");r.ex[0]=r.x+200*256;r.normalCd=0;check(r.attack()&&r.target==0,"out-of-range lock unexpectedly switched");
  r=new SurvivalRun(a,17403);r.eatFruit(0);r.update(200,1,0);check(r.buffTime[0]==7800,"buff duration incorrect");r.eatFruit(0);check(r.buffTime[0]==8000,"same fruit stacked instead of refreshed");r.pendingLevels=1;time=r.buffTime[0];r.update(200,0,0);check(r.buffTime[0]==time,"buff decayed while paused");r.pendingLevels=0;r.fruitLife[0]=12000;r.fruitKind[0]=1;r.fruitX[0]=r.x;r.fruitY[0]=r.y;r.update(20,0,0);check(r.fruitLife[0]==0&&r.buffTime[1]==8000&&r.attackPower()>r.atk,"fruit pickup failed");
  r=new SurvivalRun(a,17404);enemy(r,0,20,0);r.ecool[0]=0;r.eatFruit(3);int hp=r.hp;r.update(250,0,0);check(r.hp==hp,"invincibility failed");r.finish();for(int i=0;i<4;i++)check(r.buffTime[i]==0,"buff persisted after finish");
  r=new SurvivalRun(named("Squirtle"),17405);r.level=10;enemy(r,0,20,0);enemy(r,1,40,0);r.target=0;check(r.attack(),"pierce ray launch failed");r.update(120,0,0);check(r.ehp[0]<10000&&r.ehp[1]<10000,"water ray did not pierce");
  r=new SurvivalRun(named("Pikachu"),17406);r.level=10;r.sp=named("Pikachu");enemy(r,0,20,0);enemy(r,1,25,30);r.target=0;r.attack();r.update(200,0,0);check(r.ehp[0]<10000&&r.ehp[1]<10000,"electric ray did not chain");
  r=new SurvivalRun(named("Vulpix"),17407);r.level=10;enemy(r,0,20,0);r.target=0;r.attack();r.update(40,0,0);int after=r.ehp[0];for(int i=0;i<8;i++)r.update(100,0,0);check(r.ehp[0]<after,"fire damage over time failed");
  r=new SurvivalRun(named("Kyogre"),17408);r.level=15;r.pendingLevels=1;r.choices[0]=SurvivalRun.MEMORY;check(r.choose(0)&&r.form==SpecialFormData.PRIMAL_KYOGRE,"Primal upgrade failed");
  r=new SurvivalRun(c,17409);r.pendingLevels=1;r.choices[0]=SurvivalRun.MEGA;check(!r.choose(0),"Mega unlocked before Lv15");check(SurvivalProgress.skillTier(1)==1&&SurvivalProgress.skillTier(5)==2&&SurvivalProgress.skillTier(10)==3&&SurvivalProgress.skillTier(15)==4,"skill tiers wrong");
  r=new SurvivalRun(a,17410);for(int i=0;i<SurvivalRun.PLAYER_RAYS;i++){r.normalCd=0;check(r.attack(),"ray pool prematurely exhausted");}r.normalCd=0;check(!r.attack(),"ray pool grew beyond cap");r.finish();check(!r.targetValid(),"finished run retained target");
  r=new SurvivalRun(a,17411);r.fruitLife[0]=20;r.fruitX[0]=0;r.fruitY[0]=0;r.buffTime[0]=20;r.update(20,0,0);check(r.fruitLife[0]==0&&r.buffTime[0]==0,"fruit/buff expiry failed");
  r=new SurvivalRun(named("Squirtle"),17412);r.level=10;enemy(r,0,20,0);r.target=0;r.attack();r.update(20,0,0);int first=r.ehp[0];r.update(20,0,0);check(r.ehp[0]==first,"piercing ray damaged the same enemy twice");
  r=new SurvivalRun(a,17413);enemy(r,0,25,0);enemy(r,1,45,20);r.target=1;r.mana=r.maxMana;int impactX=r.ex[1],impactY=r.ey[1];check(r.ultimate()&&r.skillX==impactX&&r.skillY==impactY&&r.ehp[0]<10000&&r.ehp[1]<10000,"ultimate did not hit enemies in locked impact area / effect at wrong location");r.update(100,0,1);check(r.skillX==impactX&&r.skillY==impactY,"ultimate impact moved with caster");r.skillCd=0;r.mana=r.maxMana;r.ex[1]=r.x+300*256;check(!r.ultimate()&&r.target==1&&r.mana==r.maxMana,"ultimate silently switched out-of-range target / consumed MP");r.ex[1]=r.x+20*256;r.ey[1]=r.y;r.ehp[1]=1;impactX=r.ex[1];impactY=r.ey[1];check(r.ultimate()&&r.enemySp[1]<0&&r.skillX==impactX&&r.skillY==impactY,"killed target lost ultimate impact position");
  System.out.println("SurvivalSystemTest OK: starter families, legends, auto-evolution, lock-on, move/fire, HP/MP refill, variants, Mega/Primal, pickups, timed buffs/expiry, pierce/chain/DoT, repeat-hit masks, targeted ultimate impacts and bounded pools");
 }
}
