package pac;

public final class Survival174Test {
 private static void check(boolean b,String m){if(!b)throw new RuntimeException(m);}
 private static void enemy(SurvivalRun r,int i,int dx,int dy){r.enemySp[i]=0;r.ehp[i]=r.emax[i]=10000;r.ex[i]=r.prevEx[i]=r.x+dx*256;r.ey[i]=r.prevEy[i]=r.y+dy*256;r.ecool[i]=10000;r.edamage[i]=8;}
 public static void run(){
  SurvivalRun percent=new SurvivalRun(3,705);percent.level=12;percent.pendingLevels=1;percent.choices[0]=SurvivalRun.SHINY;check(percent.choose(0),"Shiny percent setup failed");check(percent.ultimatePower()==CombatRules.specialDamage(percent.attackPower()*(2+percent.skillTier())*125/100,0),"Shiny ultimate is not 25 percent");
  SurvivalRun cooldown=new SurvivalRun(3,702);enemy(cooldown,0,20,0);cooldown.target=0;cooldown.mana=cooldown.maxMana;check(cooldown.ultimate()&&cooldown.skillCd==30000,"ultimate cooldown not 30 seconds");cooldown.mana=cooldown.maxMana;check(!cooldown.ultimate(),"ultimate ignored cooldown");cooldown.update(20,0,0);check(cooldown.skillCd==29980,"cooldown timer not ticking");cooldown.gainXp(cooldown.xpNeeded());check(cooldown.levelFx==700&&cooldown.skillCd==29980,"level shockwave missing / level reset cooldown");cooldown.elementPending=false;cooldown.variantPending=0;cooldown.pendingLevels=0;cooldown.update(100,0,0);check(cooldown.levelFx==600,"level shockwave timer stuck");
  for(int species=0;species<Data.CORE_N;species++)if(MegaData.available(species)){SurvivalRun transform=new SurvivalRun(species,703);transform.sp=species;transform.level=15;transform.pendingLevels=1;transform.choices[0]=SurvivalRun.MEGA;check(transform.choose(0)&&transform.transformFx==1000,"mega transformation effect missing");break;}
  for(int species=0;species<Data.CORE_N;species++)if(ShinyData.available(species)){SurvivalRun transform=new SurvivalRun(species,704);transform.sp=species;transform.level=12;transform.pendingLevels=1;transform.choices[0]=SurvivalRun.SHINY;check(transform.choose(0)&&transform.transformFx==1000,"shiny transformation effect missing");transform.update(100,0,0);check(transform.transformFx==900,"transformation effect timer stuck");break;}
  SurvivalRun facing=new SurvivalRun(3,701);enemy(facing,0,50,0);facing.target=0;int startY=facing.y;check(facing.attack(),"facing attack failed");int aim=facing.dir;facing.update(20,0,1);check(facing.y>startY&&facing.dir==aim,"movement overrode attack facing");facing.mana=facing.maxMana;check(facing.ultimate(),"facing ultimate failed");aim=facing.dir;facing.update(20,-1,0);check(facing.dir==aim,"movement overrode ultimate facing");for(int lv=1;lv<100;lv++){facing.level=lv;int cost=facing.xpNeeded();facing.level=lv+1;check(facing.xpNeeded()>cost,"XP cost does not increase");}check(SurvivalRun.enemyHealth(0,10,0)>SurvivalRun.enemyHealth(0,9,0)*18/10&&SurvivalRun.enemyPower(0,10)>=SurvivalRun.enemyPower(0,9)*15/10,"wave ten enemy boost missing");
  SurvivalRun bossFx=new SurvivalRun(3,700);enemy(bossFx,0,20,0);bossFx.enemyRole[0]=3;bossFx.warning[0]=20;bossFx.warnX[0]=bossFx.x;bossFx.warnY[0]=bossFx.y;bossFx.buffTime[3]=10000;bossFx.update(20,0,0);check(bossFx.bossFxLife[0]==650&&bossFx.bossFxSp[0]==bossFx.enemySp[0]&&bossFx.bossFxX[0]==bossFx.warnX[0],"boss original skill effect missing");bossFx.enemySp[0]=-1;for(int i=0;i<7;i++)bossFx.update(100,0,0);check(bossFx.bossFxLife[0]==0,"boss skill effect did not expire after caster removed");
SurvivalRun area=new SurvivalRun(3,404);area.level=5;int radius=area.impactRadius();for(int n=0;n<3;n++){area.pendingLevels=1;area.choices[0]=SurvivalRun.AREA;check(area.choose(0),"area upgrade failed");}check(area.impactRadius()==radius+18,"area upgrade not reflected in ultimate radius");area.pendingLevels=1;check(!area.choose(0),"area cap exceeded");enemy(area,0,0,0);for(int sp=0;sp<Data.CORE_N;sp++)if(Data.t1[sp]==Data.T_FIRE){area.enemySp[0]=sp;break;}check(area.bossRadius(0)==40&&area.bossWarning(0)>=650,"fire boss warning/radius mismatch");
  SurvivalRun guard=new SurvivalRun(3,303);guard.elementPending=true;check(!guard.chooseVariant(true)&&guard.form==0,"unrelated element menu allowed variant confirmation");guard.elementPending=false;enemy(guard,0,10,0);guard.ehp[0]=1;guard.target=0;guard.attack();guard.update(20,0,0);check(guard.kills==1&&guard.gold==1&&guard.goldFx>0,"kill did not award gold once");guard.update(20,0,0);check(guard.gold==1,"gold awarded twice");
  check(SurvivalRun.wavePopulation(5)>SurvivalRun.wavePopulation(6)&&SurvivalRun.wavePopulation(10)>SurvivalRun.wavePopulation(11),"legendary waves need extra minions");
  SurvivalRun elemental=new SurvivalRun(0,201);check(elemental.attackType()==-1,"level 1 must use white ray");elemental.gainXp(elemental.xpNeeded());check(elemental.level==2&&elemental.elementPending&&elemental.elementCount()==2,"dual-type selection not queued at level 2");int elapsedBefore=elemental.elapsed;check(!elemental.attack()&&!elemental.dash(1,0),"actions active during element choice");elemental.update(100,1,0);check(elemental.elapsed==elapsedBefore,"element menu did not freeze simulation");check(!elemental.chooseElement(2)&&elemental.chooseElement(1)&&elemental.attackType()==elemental.type2(),"secondary type not selected");check(!elemental.chooseElement(0),"element chosen twice");for(int sp=0;sp<Data.CORE_N;sp++){SurvivalRun single=new SurvivalRun(sp,202);if(single.elementCount()!=1)continue;single.gainXp(single.xpNeeded());check(!single.chooseElement(1)&&single.chooseElement(0),"single type offered invalid second element");break;}
  SurvivalRun rayRun=new SurvivalRun(3,17440);rayRun.attack();int ray=-1;for(int i=0;i<SurvivalRun.MAX_RAYS;i++)if(rayRun.rayLife[i]>0){ray=i;break;}check(ray>=0&&rayRun.renderRayX(ray)==rayRun.rayX[ray],"new ray interpolation origin");rayRun.update(25,0,0);check(rayRun.rayAge[ray]==20,"ray frame age must follow fixed simulation");int rendered=rayRun.renderRayY(ray);check(rendered>=Math.min(rayRun.prevRayY[ray],rayRun.rayY[ray])&&rendered<=Math.max(rayRun.prevRayY[ray],rayRun.rayY[ray]),"ray interpolation overshoot");
  SurvivalTap taps=new SurvivalTap();check(!taps.press(Game.K_RIGHT,100)&&taps.press(Game.K_RIGHT,300),"double-tap failed");check(!taps.press(Game.K_RIGHT,350)&&!taps.press(Game.K_RIGHT,700),"slow tap or third tap incorrectly dashed");taps.reset();check(!taps.press(Game.K_UP,800)&&!taps.press(Game.K_RIGHT,900),"different directions dashed");
  SurvivalRun r=new SurvivalRun(3,17441);r.mana=r.maxMana;int beforeMana=r.mana;int x=r.x,y=r.y;check(r.dash(1,1)&&r.x>x&&r.y>y&&r.x-x<64*256&&r.renderX()==r.x,"diagonal blink not normalized / interpolated across teleport");check(r.mana==beforeMana-20,"blink cost not 20 mana");check(!r.dash(1,0)&&r.mana==beforeMana-20,"blink ignored cooldown / charged failed attempt");r.dashCd=0;r.mana=19;check(!r.dash(1,0)&&r.mana==19,"blink allowed insufficient mana");r.mana=r.maxMana;r.pendingLevels=1;check(!r.dash(1,0),"blink active in upgrade menu");r.pendingLevels=0;r.dashCd=0;r.x=12*256;r.y=12*256;check(!r.dash(-1,-1)&&r.x==12*256&&r.y==12*256,"blink escaped bounds");
  r=new SurvivalRun(3,17442);enemy(r,0,25,0);enemy(r,1,45,0);enemy(r,2,25,60);r.target=0;r.mana=r.maxMana;check(r.ultimate()&&r.ehp[0]<10000&&r.ehp[1]<10000&&r.ehp[2]==10000,"AoE hit outside area or missed inside");int damage=10000-r.ehp[1];r.skillCd=0;r.mana=r.maxMana;r.ultimateZones=3;enemy(r,0,25,0);enemy(r,1,45,0);enemy(r,2,25,60);r.ultimate();check(r.zoneCount==2&&r.ehp[2]<10000&&10000-r.ehp[1]==damage&&10000-r.ehp[2]<damage,"extra zones duplicated hits / did not reduce secondary damage");
  r=new SurvivalRun(3,17443);r.level=5;r.pendingLevels=1;r.choices[0]=SurvivalRun.TARGETS;check(r.choose(0)&&r.ultimateZones==2,"zone upgrade failed");r.pendingLevels=1;check(r.choose(0)&&r.ultimateZones==3,"third zone failed");r.pendingLevels=1;check(!r.choose(0),"zone cap exceeded");
  r=new SurvivalRun(3,17444);enemy(r,0,10,0);r.ehp[0]=1;r.target=0;r.attack();r.update(20,0,0);int deaths=0;for(int i=0;i<SurvivalRun.MAX_DEATHS;i++)if(r.deathLife[i]>0)deaths++;check(deaths==1,"KO has no visual event");for(int i=0;i<6;i++)r.update(100,0,0);for(int i=0;i<SurvivalRun.MAX_DEATHS;i++)check(r.deathLife[i]==0,"KO effect never expired");
  r=new SurvivalRun(3,17445);r.hp=1;enemy(r,0,10,0);r.ecool[0]=0;r.enemyRole[0]=1;r.update(20,0,0);check(r.over&&r.heroDeath>0,"player defeat not animated");for(int i=0;i<7;i++)r.update(100,0,0);check(r.heroDeath==0,"player defeat did not finish");
r=new SurvivalRun(3,17446);r.mana=r.maxMana;enemy(r,0,20,0);r.ecool[0]=0;r.enemyRole[0]=3;int hp=r.hp;r.update(20,0,0);check(r.warning[0]>0&&r.hp==hp,"boss has no warning before damage");check(r.dash(0,1),"cannot blink out of boss warning");for(int i=0;i<8;i++)r.update(100,0,0);check(r.hp==hp,"boss warning followed the player / escaped area damaged player");
  r=new SurvivalRun(3,17447);r.wave=5;r.buffTime[3]=100000;boolean boss=false,warning=false;int roles=0;for(int t=0;t<1600;t++){r.update(20,0,0);for(int i=0;i<SurvivalRun.MAX_ENEMIES;i++)if(r.enemySp[i]>=0){roles|=1<<r.enemyRole[i];boss|=r.enemyRole[i]==3;warning|=r.warning[i]>0;}}check(boss&&warning&&(roles&7)==7,"fifth-wave boss or ordinary roles missing");
  r=new SurvivalRun(3,17448);r.update(240,0,0);check(r.idleAge==240&&SurvivalAnimation.clock(RawAtlas.IDLE,r.idleAge,0)==2,"standing animation stuck");r.update(20,1,0);check(r.idleAge==0,"idle cadence did not reset on movement");
  r=new SurvivalRun(3,17449);for(int i=0;i<SurvivalRun.MAX_ENEMIES;i++){enemy(r,i,(i%7)*12,(i/7)*12);r.ecool[i]=1000000;}for(int i=0;i<SurvivalRun.MAX_RAYS;i++){r.rayLife[i]=1000000;r.rayX[i]=r.rayY[i]=256;r.rayTier[i]=1;}r.buffTime[3]=1000000;long began=System.currentTimeMillis();for(int t=0;t<10000;t++){r.update(20,0,0);check(r.living()==28,"stress enemy pool changed");}long ms=System.currentTimeMillis()-began;for(int i=0;i<SurvivalRun.MAX_RAYS;i++)check(r.rayLife[i]>0,"stress ray pool changed");
  System.out.println("Survival174Test OK: AoE/additional zones, blink, death, boss warning, roles, idle; 10000 desktop simulation ticks="+ms+"ms (not emulator FPS)");
 }
}
